// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package casa.siron.forgejo.forgejo.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class RepositorySettingsConfigArgs extends com.pulumi.resources.ResourceArgs {

    public static final RepositorySettingsConfigArgs Empty = new RepositorySettingsConfigArgs();

    /**
     * Whether the actions unit is enabled. Leave unset to avoid managing it.
     * 
     */
    @Import(name="actions")
    private @Nullable Output<Boolean> actions;

    /**
     * @return Whether the actions unit is enabled. Leave unset to avoid managing it.
     * 
     */
    public Optional<Output<Boolean>> actions() {
        return Optional.ofNullable(this.actions);
    }

    /**
     * Whether fast-forward-only merges are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
     * 
     */
    @Import(name="allowFastForwardOnlyMerge")
    private @Nullable Output<Boolean> allowFastForwardOnlyMerge;

    /**
     * @return Whether fast-forward-only merges are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
     * 
     */
    public Optional<Output<Boolean>> allowFastForwardOnlyMerge() {
        return Optional.ofNullable(this.allowFastForwardOnlyMerge);
    }

    /**
     * Whether merge commits are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
     * 
     */
    @Import(name="allowMergeCommits")
    private @Nullable Output<Boolean> allowMergeCommits;

    /**
     * @return Whether merge commits are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
     * 
     */
    public Optional<Output<Boolean>> allowMergeCommits() {
        return Optional.ofNullable(this.allowMergeCommits);
    }

    /**
     * Whether rebase merges are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
     * 
     */
    @Import(name="allowRebase")
    private @Nullable Output<Boolean> allowRebase;

    /**
     * @return Whether rebase merges are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
     * 
     */
    public Optional<Output<Boolean>> allowRebase() {
        return Optional.ofNullable(this.allowRebase);
    }

    /**
     * Whether rebase-merge (rebase with merge commit) is allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
     * 
     */
    @Import(name="allowRebaseMerge")
    private @Nullable Output<Boolean> allowRebaseMerge;

    /**
     * @return Whether rebase-merge (rebase with merge commit) is allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
     * 
     */
    public Optional<Output<Boolean>> allowRebaseMerge() {
        return Optional.ofNullable(this.allowRebaseMerge);
    }

    /**
     * Whether squash merges are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
     * 
     */
    @Import(name="allowSquashMerge")
    private @Nullable Output<Boolean> allowSquashMerge;

    /**
     * @return Whether squash merges are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
     * 
     */
    public Optional<Output<Boolean>> allowSquashMerge() {
        return Optional.ofNullable(this.allowSquashMerge);
    }

    /**
     * Whether the repository is archived. Leave unset to avoid managing it.
     * 
     */
    @Import(name="archived")
    private @Nullable Output<Boolean> archived;

    /**
     * @return Whether the repository is archived. Leave unset to avoid managing it.
     * 
     */
    public Optional<Output<Boolean>> archived() {
        return Optional.ofNullable(this.archived);
    }

    /**
     * Whether Forgejo deletes pull request branches by default after merge. Setting this also enables pull requests unless pullRequests is explicitly set.
     * 
     */
    @Import(name="defaultDeleteBranchAfterMerge")
    private @Nullable Output<Boolean> defaultDeleteBranchAfterMerge;

    /**
     * @return Whether Forgejo deletes pull request branches by default after merge. Setting this also enables pull requests unless pullRequests is explicitly set.
     * 
     */
    public Optional<Output<Boolean>> defaultDeleteBranchAfterMerge() {
        return Optional.ofNullable(this.defaultDeleteBranchAfterMerge);
    }

    /**
     * Default merge style: merge, rebase, rebase-merge, squash, or fast-forward-only. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
     * 
     */
    @Import(name="defaultMergeStyle")
    private @Nullable Output<String> defaultMergeStyle;

    /**
     * @return Default merge style: merge, rebase, rebase-merge, squash, or fast-forward-only. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
     * 
     */
    public Optional<Output<String>> defaultMergeStyle() {
        return Optional.ofNullable(this.defaultMergeStyle);
    }

    /**
     * External issue tracker URL format. Forgejo supports placeholders such as {user}, {repo}, and {index}.
     * 
     */
    @Import(name="externalTrackerFormat")
    private @Nullable Output<String> externalTrackerFormat;

    /**
     * @return External issue tracker URL format. Forgejo supports placeholders such as {user}, {repo}, and {index}.
     * 
     */
    public Optional<Output<String>> externalTrackerFormat() {
        return Optional.ofNullable(this.externalTrackerFormat);
    }

    /**
     * External issue tracker regular expression pattern.
     * 
     */
    @Import(name="externalTrackerRegexPattern")
    private @Nullable Output<String> externalTrackerRegexPattern;

    /**
     * @return External issue tracker regular expression pattern.
     * 
     */
    public Optional<Output<String>> externalTrackerRegexPattern() {
        return Optional.ofNullable(this.externalTrackerRegexPattern);
    }

    /**
     * External issue tracker number style, for example numeric or alphanumeric.
     * 
     */
    @Import(name="externalTrackerStyle")
    private @Nullable Output<String> externalTrackerStyle;

    /**
     * @return External issue tracker number style, for example numeric or alphanumeric.
     * 
     */
    public Optional<Output<String>> externalTrackerStyle() {
        return Optional.ofNullable(this.externalTrackerStyle);
    }

    /**
     * External issue tracker URL. Setting this also enables issues unless issues is explicitly set.
     * 
     */
    @Import(name="externalTrackerUrl")
    private @Nullable Output<String> externalTrackerUrl;

    /**
     * @return External issue tracker URL. Setting this also enables issues unless issues is explicitly set.
     * 
     */
    public Optional<Output<String>> externalTrackerUrl() {
        return Optional.ofNullable(this.externalTrackerUrl);
    }

    /**
     * External wiki URL. Setting this also enables the wiki unless wiki is explicitly set.
     * 
     */
    @Import(name="externalWikiUrl")
    private @Nullable Output<String> externalWikiUrl;

    /**
     * @return External wiki URL. Setting this also enables the wiki unless wiki is explicitly set.
     * 
     */
    public Optional<Output<String>> externalWikiUrl() {
        return Optional.ofNullable(this.externalWikiUrl);
    }

    /**
     * Whether the wiki is globally editable.
     * 
     */
    @Import(name="globallyEditableWiki")
    private @Nullable Output<Boolean> globallyEditableWiki;

    /**
     * @return Whether the wiki is globally editable.
     * 
     */
    public Optional<Output<Boolean>> globallyEditableWiki() {
        return Optional.ofNullable(this.globallyEditableWiki);
    }

    /**
     * Whether only contributors may track time in the internal issue tracker.
     * 
     */
    @Import(name="internalTrackerAllowOnlyContributorsToTrackTime")
    private @Nullable Output<Boolean> internalTrackerAllowOnlyContributorsToTrackTime;

    /**
     * @return Whether only contributors may track time in the internal issue tracker.
     * 
     */
    public Optional<Output<Boolean>> internalTrackerAllowOnlyContributorsToTrackTime() {
        return Optional.ofNullable(this.internalTrackerAllowOnlyContributorsToTrackTime);
    }

    /**
     * Whether issue dependencies are enabled in the internal issue tracker.
     * 
     */
    @Import(name="internalTrackerEnableIssueDependencies")
    private @Nullable Output<Boolean> internalTrackerEnableIssueDependencies;

    /**
     * @return Whether issue dependencies are enabled in the internal issue tracker.
     * 
     */
    public Optional<Output<Boolean>> internalTrackerEnableIssueDependencies() {
        return Optional.ofNullable(this.internalTrackerEnableIssueDependencies);
    }

    /**
     * Whether the internal issue tracker has time tracking enabled.
     * 
     */
    @Import(name="internalTrackerEnableTimeTracker")
    private @Nullable Output<Boolean> internalTrackerEnableTimeTracker;

    /**
     * @return Whether the internal issue tracker has time tracking enabled.
     * 
     */
    public Optional<Output<Boolean>> internalTrackerEnableTimeTracker() {
        return Optional.ofNullable(this.internalTrackerEnableTimeTracker);
    }

    /**
     * Whether the issue tracker unit is enabled. Leave unset to avoid managing it.
     * 
     */
    @Import(name="issues")
    private @Nullable Output<Boolean> issues;

    /**
     * @return Whether the issue tracker unit is enabled. Leave unset to avoid managing it.
     * 
     */
    public Optional<Output<Boolean>> issues() {
        return Optional.ofNullable(this.issues);
    }

    /**
     * Whether the packages unit is enabled. Leave unset to avoid managing it.
     * 
     */
    @Import(name="packages")
    private @Nullable Output<Boolean> packages;

    /**
     * @return Whether the packages unit is enabled. Leave unset to avoid managing it.
     * 
     */
    public Optional<Output<Boolean>> packages() {
        return Optional.ofNullable(this.packages);
    }

    /**
     * Whether the projects unit is enabled. Leave unset to avoid managing it.
     * 
     */
    @Import(name="projects")
    private @Nullable Output<Boolean> projects;

    /**
     * @return Whether the projects unit is enabled. Leave unset to avoid managing it.
     * 
     */
    public Optional<Output<Boolean>> projects() {
        return Optional.ofNullable(this.projects);
    }

    /**
     * Whether the pull request unit is enabled. Leave unset to avoid managing it.
     * 
     */
    @Import(name="pullRequests")
    private @Nullable Output<Boolean> pullRequests;

    /**
     * @return Whether the pull request unit is enabled. Leave unset to avoid managing it.
     * 
     */
    public Optional<Output<Boolean>> pullRequests() {
        return Optional.ofNullable(this.pullRequests);
    }

    /**
     * Whether the releases unit is enabled. Leave unset to avoid managing it.
     * 
     */
    @Import(name="releases")
    private @Nullable Output<Boolean> releases;

    /**
     * @return Whether the releases unit is enabled. Leave unset to avoid managing it.
     * 
     */
    public Optional<Output<Boolean>> releases() {
        return Optional.ofNullable(this.releases);
    }

    /**
     * Whether the wiki unit is enabled. Leave unset to avoid managing it.
     * 
     */
    @Import(name="wiki")
    private @Nullable Output<Boolean> wiki;

    /**
     * @return Whether the wiki unit is enabled. Leave unset to avoid managing it.
     * 
     */
    public Optional<Output<Boolean>> wiki() {
        return Optional.ofNullable(this.wiki);
    }

    /**
     * Branch used for the repository wiki.
     * 
     */
    @Import(name="wikiBranch")
    private @Nullable Output<String> wikiBranch;

    /**
     * @return Branch used for the repository wiki.
     * 
     */
    public Optional<Output<String>> wikiBranch() {
        return Optional.ofNullable(this.wikiBranch);
    }

    private RepositorySettingsConfigArgs() {}

    private RepositorySettingsConfigArgs(RepositorySettingsConfigArgs $) {
        this.actions = $.actions;
        this.allowFastForwardOnlyMerge = $.allowFastForwardOnlyMerge;
        this.allowMergeCommits = $.allowMergeCommits;
        this.allowRebase = $.allowRebase;
        this.allowRebaseMerge = $.allowRebaseMerge;
        this.allowSquashMerge = $.allowSquashMerge;
        this.archived = $.archived;
        this.defaultDeleteBranchAfterMerge = $.defaultDeleteBranchAfterMerge;
        this.defaultMergeStyle = $.defaultMergeStyle;
        this.externalTrackerFormat = $.externalTrackerFormat;
        this.externalTrackerRegexPattern = $.externalTrackerRegexPattern;
        this.externalTrackerStyle = $.externalTrackerStyle;
        this.externalTrackerUrl = $.externalTrackerUrl;
        this.externalWikiUrl = $.externalWikiUrl;
        this.globallyEditableWiki = $.globallyEditableWiki;
        this.internalTrackerAllowOnlyContributorsToTrackTime = $.internalTrackerAllowOnlyContributorsToTrackTime;
        this.internalTrackerEnableIssueDependencies = $.internalTrackerEnableIssueDependencies;
        this.internalTrackerEnableTimeTracker = $.internalTrackerEnableTimeTracker;
        this.issues = $.issues;
        this.packages = $.packages;
        this.projects = $.projects;
        this.pullRequests = $.pullRequests;
        this.releases = $.releases;
        this.wiki = $.wiki;
        this.wikiBranch = $.wikiBranch;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RepositorySettingsConfigArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RepositorySettingsConfigArgs $;

        public Builder() {
            $ = new RepositorySettingsConfigArgs();
        }

        public Builder(RepositorySettingsConfigArgs defaults) {
            $ = new RepositorySettingsConfigArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param actions Whether the actions unit is enabled. Leave unset to avoid managing it.
         * 
         * @return builder
         * 
         */
        public Builder actions(@Nullable Output<Boolean> actions) {
            $.actions = actions;
            return this;
        }

        /**
         * @param actions Whether the actions unit is enabled. Leave unset to avoid managing it.
         * 
         * @return builder
         * 
         */
        public Builder actions(Boolean actions) {
            return actions(Output.of(actions));
        }

        /**
         * @param allowFastForwardOnlyMerge Whether fast-forward-only merges are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
         * 
         * @return builder
         * 
         */
        public Builder allowFastForwardOnlyMerge(@Nullable Output<Boolean> allowFastForwardOnlyMerge) {
            $.allowFastForwardOnlyMerge = allowFastForwardOnlyMerge;
            return this;
        }

        /**
         * @param allowFastForwardOnlyMerge Whether fast-forward-only merges are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
         * 
         * @return builder
         * 
         */
        public Builder allowFastForwardOnlyMerge(Boolean allowFastForwardOnlyMerge) {
            return allowFastForwardOnlyMerge(Output.of(allowFastForwardOnlyMerge));
        }

        /**
         * @param allowMergeCommits Whether merge commits are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
         * 
         * @return builder
         * 
         */
        public Builder allowMergeCommits(@Nullable Output<Boolean> allowMergeCommits) {
            $.allowMergeCommits = allowMergeCommits;
            return this;
        }

        /**
         * @param allowMergeCommits Whether merge commits are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
         * 
         * @return builder
         * 
         */
        public Builder allowMergeCommits(Boolean allowMergeCommits) {
            return allowMergeCommits(Output.of(allowMergeCommits));
        }

        /**
         * @param allowRebase Whether rebase merges are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
         * 
         * @return builder
         * 
         */
        public Builder allowRebase(@Nullable Output<Boolean> allowRebase) {
            $.allowRebase = allowRebase;
            return this;
        }

        /**
         * @param allowRebase Whether rebase merges are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
         * 
         * @return builder
         * 
         */
        public Builder allowRebase(Boolean allowRebase) {
            return allowRebase(Output.of(allowRebase));
        }

        /**
         * @param allowRebaseMerge Whether rebase-merge (rebase with merge commit) is allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
         * 
         * @return builder
         * 
         */
        public Builder allowRebaseMerge(@Nullable Output<Boolean> allowRebaseMerge) {
            $.allowRebaseMerge = allowRebaseMerge;
            return this;
        }

        /**
         * @param allowRebaseMerge Whether rebase-merge (rebase with merge commit) is allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
         * 
         * @return builder
         * 
         */
        public Builder allowRebaseMerge(Boolean allowRebaseMerge) {
            return allowRebaseMerge(Output.of(allowRebaseMerge));
        }

        /**
         * @param allowSquashMerge Whether squash merges are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
         * 
         * @return builder
         * 
         */
        public Builder allowSquashMerge(@Nullable Output<Boolean> allowSquashMerge) {
            $.allowSquashMerge = allowSquashMerge;
            return this;
        }

        /**
         * @param allowSquashMerge Whether squash merges are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
         * 
         * @return builder
         * 
         */
        public Builder allowSquashMerge(Boolean allowSquashMerge) {
            return allowSquashMerge(Output.of(allowSquashMerge));
        }

        /**
         * @param archived Whether the repository is archived. Leave unset to avoid managing it.
         * 
         * @return builder
         * 
         */
        public Builder archived(@Nullable Output<Boolean> archived) {
            $.archived = archived;
            return this;
        }

        /**
         * @param archived Whether the repository is archived. Leave unset to avoid managing it.
         * 
         * @return builder
         * 
         */
        public Builder archived(Boolean archived) {
            return archived(Output.of(archived));
        }

        /**
         * @param defaultDeleteBranchAfterMerge Whether Forgejo deletes pull request branches by default after merge. Setting this also enables pull requests unless pullRequests is explicitly set.
         * 
         * @return builder
         * 
         */
        public Builder defaultDeleteBranchAfterMerge(@Nullable Output<Boolean> defaultDeleteBranchAfterMerge) {
            $.defaultDeleteBranchAfterMerge = defaultDeleteBranchAfterMerge;
            return this;
        }

        /**
         * @param defaultDeleteBranchAfterMerge Whether Forgejo deletes pull request branches by default after merge. Setting this also enables pull requests unless pullRequests is explicitly set.
         * 
         * @return builder
         * 
         */
        public Builder defaultDeleteBranchAfterMerge(Boolean defaultDeleteBranchAfterMerge) {
            return defaultDeleteBranchAfterMerge(Output.of(defaultDeleteBranchAfterMerge));
        }

        /**
         * @param defaultMergeStyle Default merge style: merge, rebase, rebase-merge, squash, or fast-forward-only. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
         * 
         * @return builder
         * 
         */
        public Builder defaultMergeStyle(@Nullable Output<String> defaultMergeStyle) {
            $.defaultMergeStyle = defaultMergeStyle;
            return this;
        }

        /**
         * @param defaultMergeStyle Default merge style: merge, rebase, rebase-merge, squash, or fast-forward-only. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
         * 
         * @return builder
         * 
         */
        public Builder defaultMergeStyle(String defaultMergeStyle) {
            return defaultMergeStyle(Output.of(defaultMergeStyle));
        }

        /**
         * @param externalTrackerFormat External issue tracker URL format. Forgejo supports placeholders such as {user}, {repo}, and {index}.
         * 
         * @return builder
         * 
         */
        public Builder externalTrackerFormat(@Nullable Output<String> externalTrackerFormat) {
            $.externalTrackerFormat = externalTrackerFormat;
            return this;
        }

        /**
         * @param externalTrackerFormat External issue tracker URL format. Forgejo supports placeholders such as {user}, {repo}, and {index}.
         * 
         * @return builder
         * 
         */
        public Builder externalTrackerFormat(String externalTrackerFormat) {
            return externalTrackerFormat(Output.of(externalTrackerFormat));
        }

        /**
         * @param externalTrackerRegexPattern External issue tracker regular expression pattern.
         * 
         * @return builder
         * 
         */
        public Builder externalTrackerRegexPattern(@Nullable Output<String> externalTrackerRegexPattern) {
            $.externalTrackerRegexPattern = externalTrackerRegexPattern;
            return this;
        }

        /**
         * @param externalTrackerRegexPattern External issue tracker regular expression pattern.
         * 
         * @return builder
         * 
         */
        public Builder externalTrackerRegexPattern(String externalTrackerRegexPattern) {
            return externalTrackerRegexPattern(Output.of(externalTrackerRegexPattern));
        }

        /**
         * @param externalTrackerStyle External issue tracker number style, for example numeric or alphanumeric.
         * 
         * @return builder
         * 
         */
        public Builder externalTrackerStyle(@Nullable Output<String> externalTrackerStyle) {
            $.externalTrackerStyle = externalTrackerStyle;
            return this;
        }

        /**
         * @param externalTrackerStyle External issue tracker number style, for example numeric or alphanumeric.
         * 
         * @return builder
         * 
         */
        public Builder externalTrackerStyle(String externalTrackerStyle) {
            return externalTrackerStyle(Output.of(externalTrackerStyle));
        }

        /**
         * @param externalTrackerUrl External issue tracker URL. Setting this also enables issues unless issues is explicitly set.
         * 
         * @return builder
         * 
         */
        public Builder externalTrackerUrl(@Nullable Output<String> externalTrackerUrl) {
            $.externalTrackerUrl = externalTrackerUrl;
            return this;
        }

        /**
         * @param externalTrackerUrl External issue tracker URL. Setting this also enables issues unless issues is explicitly set.
         * 
         * @return builder
         * 
         */
        public Builder externalTrackerUrl(String externalTrackerUrl) {
            return externalTrackerUrl(Output.of(externalTrackerUrl));
        }

        /**
         * @param externalWikiUrl External wiki URL. Setting this also enables the wiki unless wiki is explicitly set.
         * 
         * @return builder
         * 
         */
        public Builder externalWikiUrl(@Nullable Output<String> externalWikiUrl) {
            $.externalWikiUrl = externalWikiUrl;
            return this;
        }

        /**
         * @param externalWikiUrl External wiki URL. Setting this also enables the wiki unless wiki is explicitly set.
         * 
         * @return builder
         * 
         */
        public Builder externalWikiUrl(String externalWikiUrl) {
            return externalWikiUrl(Output.of(externalWikiUrl));
        }

        /**
         * @param globallyEditableWiki Whether the wiki is globally editable.
         * 
         * @return builder
         * 
         */
        public Builder globallyEditableWiki(@Nullable Output<Boolean> globallyEditableWiki) {
            $.globallyEditableWiki = globallyEditableWiki;
            return this;
        }

        /**
         * @param globallyEditableWiki Whether the wiki is globally editable.
         * 
         * @return builder
         * 
         */
        public Builder globallyEditableWiki(Boolean globallyEditableWiki) {
            return globallyEditableWiki(Output.of(globallyEditableWiki));
        }

        /**
         * @param internalTrackerAllowOnlyContributorsToTrackTime Whether only contributors may track time in the internal issue tracker.
         * 
         * @return builder
         * 
         */
        public Builder internalTrackerAllowOnlyContributorsToTrackTime(@Nullable Output<Boolean> internalTrackerAllowOnlyContributorsToTrackTime) {
            $.internalTrackerAllowOnlyContributorsToTrackTime = internalTrackerAllowOnlyContributorsToTrackTime;
            return this;
        }

        /**
         * @param internalTrackerAllowOnlyContributorsToTrackTime Whether only contributors may track time in the internal issue tracker.
         * 
         * @return builder
         * 
         */
        public Builder internalTrackerAllowOnlyContributorsToTrackTime(Boolean internalTrackerAllowOnlyContributorsToTrackTime) {
            return internalTrackerAllowOnlyContributorsToTrackTime(Output.of(internalTrackerAllowOnlyContributorsToTrackTime));
        }

        /**
         * @param internalTrackerEnableIssueDependencies Whether issue dependencies are enabled in the internal issue tracker.
         * 
         * @return builder
         * 
         */
        public Builder internalTrackerEnableIssueDependencies(@Nullable Output<Boolean> internalTrackerEnableIssueDependencies) {
            $.internalTrackerEnableIssueDependencies = internalTrackerEnableIssueDependencies;
            return this;
        }

        /**
         * @param internalTrackerEnableIssueDependencies Whether issue dependencies are enabled in the internal issue tracker.
         * 
         * @return builder
         * 
         */
        public Builder internalTrackerEnableIssueDependencies(Boolean internalTrackerEnableIssueDependencies) {
            return internalTrackerEnableIssueDependencies(Output.of(internalTrackerEnableIssueDependencies));
        }

        /**
         * @param internalTrackerEnableTimeTracker Whether the internal issue tracker has time tracking enabled.
         * 
         * @return builder
         * 
         */
        public Builder internalTrackerEnableTimeTracker(@Nullable Output<Boolean> internalTrackerEnableTimeTracker) {
            $.internalTrackerEnableTimeTracker = internalTrackerEnableTimeTracker;
            return this;
        }

        /**
         * @param internalTrackerEnableTimeTracker Whether the internal issue tracker has time tracking enabled.
         * 
         * @return builder
         * 
         */
        public Builder internalTrackerEnableTimeTracker(Boolean internalTrackerEnableTimeTracker) {
            return internalTrackerEnableTimeTracker(Output.of(internalTrackerEnableTimeTracker));
        }

        /**
         * @param issues Whether the issue tracker unit is enabled. Leave unset to avoid managing it.
         * 
         * @return builder
         * 
         */
        public Builder issues(@Nullable Output<Boolean> issues) {
            $.issues = issues;
            return this;
        }

        /**
         * @param issues Whether the issue tracker unit is enabled. Leave unset to avoid managing it.
         * 
         * @return builder
         * 
         */
        public Builder issues(Boolean issues) {
            return issues(Output.of(issues));
        }

        /**
         * @param packages Whether the packages unit is enabled. Leave unset to avoid managing it.
         * 
         * @return builder
         * 
         */
        public Builder packages(@Nullable Output<Boolean> packages) {
            $.packages = packages;
            return this;
        }

        /**
         * @param packages Whether the packages unit is enabled. Leave unset to avoid managing it.
         * 
         * @return builder
         * 
         */
        public Builder packages(Boolean packages) {
            return packages(Output.of(packages));
        }

        /**
         * @param projects Whether the projects unit is enabled. Leave unset to avoid managing it.
         * 
         * @return builder
         * 
         */
        public Builder projects(@Nullable Output<Boolean> projects) {
            $.projects = projects;
            return this;
        }

        /**
         * @param projects Whether the projects unit is enabled. Leave unset to avoid managing it.
         * 
         * @return builder
         * 
         */
        public Builder projects(Boolean projects) {
            return projects(Output.of(projects));
        }

        /**
         * @param pullRequests Whether the pull request unit is enabled. Leave unset to avoid managing it.
         * 
         * @return builder
         * 
         */
        public Builder pullRequests(@Nullable Output<Boolean> pullRequests) {
            $.pullRequests = pullRequests;
            return this;
        }

        /**
         * @param pullRequests Whether the pull request unit is enabled. Leave unset to avoid managing it.
         * 
         * @return builder
         * 
         */
        public Builder pullRequests(Boolean pullRequests) {
            return pullRequests(Output.of(pullRequests));
        }

        /**
         * @param releases Whether the releases unit is enabled. Leave unset to avoid managing it.
         * 
         * @return builder
         * 
         */
        public Builder releases(@Nullable Output<Boolean> releases) {
            $.releases = releases;
            return this;
        }

        /**
         * @param releases Whether the releases unit is enabled. Leave unset to avoid managing it.
         * 
         * @return builder
         * 
         */
        public Builder releases(Boolean releases) {
            return releases(Output.of(releases));
        }

        /**
         * @param wiki Whether the wiki unit is enabled. Leave unset to avoid managing it.
         * 
         * @return builder
         * 
         */
        public Builder wiki(@Nullable Output<Boolean> wiki) {
            $.wiki = wiki;
            return this;
        }

        /**
         * @param wiki Whether the wiki unit is enabled. Leave unset to avoid managing it.
         * 
         * @return builder
         * 
         */
        public Builder wiki(Boolean wiki) {
            return wiki(Output.of(wiki));
        }

        /**
         * @param wikiBranch Branch used for the repository wiki.
         * 
         * @return builder
         * 
         */
        public Builder wikiBranch(@Nullable Output<String> wikiBranch) {
            $.wikiBranch = wikiBranch;
            return this;
        }

        /**
         * @param wikiBranch Branch used for the repository wiki.
         * 
         * @return builder
         * 
         */
        public Builder wikiBranch(String wikiBranch) {
            return wikiBranch(Output.of(wikiBranch));
        }

        public RepositorySettingsConfigArgs build() {
            return $;
        }
    }

}
