version: 2

project_name: pulumi-resource-forgejo

env_files:
  gitea_token: .goreleaser-forgejo-token

gitea_urls:
  api: http://forgejo-http:3000/api/v1
  download: https://forgejo.siron.casa

before:
  hooks:
    - sh -c 'mkdir -p bin && version=${FORGEJO_PROVIDER_VERSION#v} && go build -trimpath -ldflags "-s -w -X main.version=$version" -o bin/pulumi-resource-forgejo ./cmd/pulumi-resource-forgejo'
    - sh -c 'pulumi package get-schema ./bin/pulumi-resource-forgejo > schema.json'
    - scripts/gen-sdk.sh

builds:
  - id: pulumi-resource-forgejo
    main: ./cmd/pulumi-resource-forgejo
    binary: pulumi-resource-forgejo
    env:
      - GOMAXPROCS=1
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - id: pulumi-resource-forgejo
    ids:
      - pulumi-resource-forgejo
    name_template: "pulumi-resource-forgejo-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    formats:
      - tar.gz
    files:
      - README.md
      - LICENSE

checksum:
  name_template: checksums.txt

changelog:
  use: git
  sort: asc
  abbrev: -1
  groups:
    - title: Features
      regexp: '^.*feat(\(.+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*fix(\(.+\))??!?:.+$'
      order: 1
    - title: Documentation
      regexp: '^.*docs(\(.+\))??!?:.+$'
      order: 2
    - title: Maintenance
      regexp: '^.*(chore|ci|build|refactor|test)(\(.+\))??!?:.+$'
      order: 3
    - title: Other Changes
      order: 999
  filters:
    exclude:
      - '^chore\(release\):'

release:
  gitea:
    owner: sironheart
    name: forgejo-pulumi-provider
  mode: keep-existing
  prerelease: auto
  extra_files:
    - glob: schema.json
