// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Forgejo
{
    public static class GetCurrentUser
    {
        /// <summary>
        /// Returns the authenticated Forgejo user.
        /// </summary>
        public static Task<GetCurrentUserResult> InvokeAsync(GetCurrentUserArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetCurrentUserResult>("forgejo:index:getCurrentUser", args ?? new GetCurrentUserArgs(), options.WithDefaults());

        /// <summary>
        /// Returns the authenticated Forgejo user.
        /// </summary>
        public static Output<GetCurrentUserResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetCurrentUserResult>("forgejo:index:getCurrentUser", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Returns the authenticated Forgejo user.
        /// </summary>
        public static Output<GetCurrentUserResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetCurrentUserResult>("forgejo:index:getCurrentUser", InvokeArgs.Empty, options.WithDefaults());
    }


    public sealed class GetCurrentUserArgs : global::Pulumi.InvokeArgs
    {
        public GetCurrentUserArgs()
        {
        }
        public static new GetCurrentUserArgs Empty => new GetCurrentUserArgs();
    }


    [OutputType]
    public sealed class GetCurrentUserResult
    {
        public readonly string Email;
        public readonly string FullName;
        public readonly bool IsAdmin;
        public readonly string Login;
        public readonly int UserId;

        [OutputConstructor]
        private GetCurrentUserResult(
            string email,

            string fullName,

            bool isAdmin,

            string login,

            int userId)
        {
            Email = email;
            FullName = fullName;
            IsAdmin = isAdmin;
            Login = login;
            UserId = userId;
        }
    }
}
