// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Forgejo
{
    /// <summary>
    /// A Forgejo organization team.
    /// </summary>
    [ForgejoResourceType("forgejo:index:OrganizationTeam")]
    public partial class OrganizationTeam : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Whether team members can create organization repositories.
        /// </summary>
        [Output("canCreateOrgRepo")]
        public Output<bool?> CanCreateOrgRepo { get; private set; } = null!;

        /// <summary>
        /// Team description.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// Whether the team includes all organization repositories.
        /// </summary>
        [Output("includesAllRepositories")]
        public Output<bool?> IncludesAllRepositories { get; private set; } = null!;

        /// <summary>
        /// Team name.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Organization username/slug.
        /// </summary>
        [Output("organization")]
        public Output<string> Organization { get; private set; } = null!;

        /// <summary>
        /// Team repository permission: read, write, or admin.
        /// </summary>
        [Output("permission")]
        public Output<string?> Permission { get; private set; } = null!;

        [Output("teamId")]
        public Output<int> TeamId { get; private set; } = null!;

        /// <summary>
        /// Per-repository-unit permissions, for example repo.code=read or repo.issues=write.
        /// </summary>
        [Output("unitsMap")]
        public Output<ImmutableDictionary<string, string>?> UnitsMap { get; private set; } = null!;


        /// <summary>
        /// Create a OrganizationTeam resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public OrganizationTeam(string name, OrganizationTeamArgs args, CustomResourceOptions? options = null)
            : base("forgejo:index:OrganizationTeam", name, args ?? new OrganizationTeamArgs(), MakeResourceOptions(options, ""))
        {
        }

        private OrganizationTeam(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("forgejo:index:OrganizationTeam", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://forgejo.siron.casa/sironheart/forgejo-pulumi-provider/releases/download/v${VERSION}",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing OrganizationTeam resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static OrganizationTeam Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new OrganizationTeam(name, id, options);
        }
    }

    public sealed class OrganizationTeamArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether team members can create organization repositories.
        /// </summary>
        [Input("canCreateOrgRepo")]
        public Input<bool>? CanCreateOrgRepo { get; set; }

        /// <summary>
        /// Team description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Whether the team includes all organization repositories.
        /// </summary>
        [Input("includesAllRepositories")]
        public Input<bool>? IncludesAllRepositories { get; set; }

        /// <summary>
        /// Team name.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Organization username/slug.
        /// </summary>
        [Input("organization", required: true)]
        public Input<string> Organization { get; set; } = null!;

        /// <summary>
        /// Team repository permission: read, write, or admin.
        /// </summary>
        [Input("permission")]
        public Input<string>? Permission { get; set; }

        [Input("unitsMap")]
        private InputMap<string>? _unitsMap;

        /// <summary>
        /// Per-repository-unit permissions, for example repo.code=read or repo.issues=write.
        /// </summary>
        public InputMap<string> UnitsMap
        {
            get => _unitsMap ?? (_unitsMap = new InputMap<string>());
            set => _unitsMap = value;
        }

        public OrganizationTeamArgs()
        {
            Permission = "read";
        }
        public static new OrganizationTeamArgs Empty => new OrganizationTeamArgs();
    }
}
