// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Forgejo
{
    /// <summary>
    /// A Forgejo Actions variable for a repository.
    /// </summary>
    [ForgejoResourceType("forgejo:index:RepositoryActionVariable")]
    public partial class RepositoryActionVariable : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Actions variable name.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Repository owner.
        /// </summary>
        [Output("owner")]
        public Output<string> Owner { get; private set; } = null!;

        [Output("ownerId")]
        public Output<int> OwnerId { get; private set; } = null!;

        [Output("repoId")]
        public Output<int> RepoId { get; private set; } = null!;

        /// <summary>
        /// Repository name.
        /// </summary>
        [Output("repository")]
        public Output<string> Repository { get; private set; } = null!;

        /// <summary>
        /// Actions variable value.
        /// </summary>
        [Output("value")]
        public Output<string> Value { get; private set; } = null!;


        /// <summary>
        /// Create a RepositoryActionVariable resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public RepositoryActionVariable(string name, RepositoryActionVariableArgs args, CustomResourceOptions? options = null)
            : base("forgejo:index:RepositoryActionVariable", name, args ?? new RepositoryActionVariableArgs(), MakeResourceOptions(options, ""))
        {
        }

        private RepositoryActionVariable(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("forgejo:index:RepositoryActionVariable", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://forgejo.siron.casa/sironheart/forgejo-pulumi-provider/releases/download/v${VERSION}/",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing RepositoryActionVariable resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static RepositoryActionVariable Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new RepositoryActionVariable(name, id, options);
        }
    }

    public sealed class RepositoryActionVariableArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Actions variable name.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Repository owner.
        /// </summary>
        [Input("owner", required: true)]
        public Input<string> Owner { get; set; } = null!;

        /// <summary>
        /// Repository name.
        /// </summary>
        [Input("repository", required: true)]
        public Input<string> Repository { get; set; } = null!;

        /// <summary>
        /// Actions variable value.
        /// </summary>
        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public RepositoryActionVariableArgs()
        {
        }
        public static new RepositoryActionVariableArgs Empty => new RepositoryActionVariableArgs();
    }
}
