// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Forgejo
{
    /// <summary>
    /// A Forgejo Actions secret for a repository.
    /// </summary>
    [ForgejoResourceType("forgejo:index:RepositoryActionSecret")]
    public partial class RepositoryActionSecret : global::Pulumi.CustomResource
    {
        [Output("created")]
        public Output<string> Created { get; private set; } = null!;

        /// <summary>
        /// Actions secret name.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Repository owner.
        /// </summary>
        [Output("owner")]
        public Output<string> Owner { get; private set; } = null!;

        /// <summary>
        /// Repository name.
        /// </summary>
        [Output("repository")]
        public Output<string> Repository { get; private set; } = null!;

        /// <summary>
        /// Actions secret value.
        /// </summary>
        [Output("value")]
        public Output<string> Value { get; private set; } = null!;


        /// <summary>
        /// Create a RepositoryActionSecret resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public RepositoryActionSecret(string name, RepositoryActionSecretArgs args, CustomResourceOptions? options = null)
            : base("forgejo:index:RepositoryActionSecret", name, args ?? new RepositoryActionSecretArgs(), MakeResourceOptions(options, ""))
        {
        }

        private RepositoryActionSecret(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("forgejo:index:RepositoryActionSecret", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://forgejo.siron.casa/sironheart/forgejo-pulumi-provider/releases/download/v${VERSION}/",
                AdditionalSecretOutputs =
                {
                    "value",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing RepositoryActionSecret resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static RepositoryActionSecret Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new RepositoryActionSecret(name, id, options);
        }
    }

    public sealed class RepositoryActionSecretArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Actions secret name.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Repository owner.
        /// </summary>
        [Input("owner", required: true)]
        public Input<string> Owner { get; set; } = null!;

        /// <summary>
        /// Repository name.
        /// </summary>
        [Input("repository", required: true)]
        public Input<string> Repository { get; set; } = null!;

        [Input("value", required: true)]
        private Input<string>? _value;

        /// <summary>
        /// Actions secret value.
        /// </summary>
        public Input<string>? Value
        {
            get => _value;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _value = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public RepositoryActionSecretArgs()
        {
        }
        public static new RepositoryActionSecretArgs Empty => new RepositoryActionSecretArgs();
    }
}
