// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Forgejo
{
    /// <summary>
    /// A Forgejo tag protection rule for a repository.
    /// </summary>
    [ForgejoResourceType("forgejo:index:RepositoryTagProtection")]
    public partial class RepositoryTagProtection : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Protected tag name pattern, for example v*.
        /// </summary>
        [Output("namePattern")]
        public Output<string> NamePattern { get; private set; } = null!;

        /// <summary>
        /// Repository owner.
        /// </summary>
        [Output("owner")]
        public Output<string> Owner { get; private set; } = null!;

        [Output("protectionId")]
        public Output<int> ProtectionId { get; private set; } = null!;

        /// <summary>
        /// Repository name.
        /// </summary>
        [Output("repository")]
        public Output<string> Repository { get; private set; } = null!;

        /// <summary>
        /// Teams allowed to create matching tags.
        /// </summary>
        [Output("whitelistTeams")]
        public Output<ImmutableArray<string>> WhitelistTeams { get; private set; } = null!;

        /// <summary>
        /// Users allowed to create matching tags.
        /// </summary>
        [Output("whitelistUsernames")]
        public Output<ImmutableArray<string>> WhitelistUsernames { get; private set; } = null!;


        /// <summary>
        /// Create a RepositoryTagProtection resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public RepositoryTagProtection(string name, RepositoryTagProtectionArgs args, CustomResourceOptions? options = null)
            : base("forgejo:index:RepositoryTagProtection", name, args ?? new RepositoryTagProtectionArgs(), MakeResourceOptions(options, ""))
        {
        }

        private RepositoryTagProtection(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("forgejo:index:RepositoryTagProtection", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://forgejo.siron.casa/sironheart/forgejo-pulumi-provider/releases/download/v${VERSION}",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing RepositoryTagProtection resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static RepositoryTagProtection Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new RepositoryTagProtection(name, id, options);
        }
    }

    public sealed class RepositoryTagProtectionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Protected tag name pattern, for example v*.
        /// </summary>
        [Input("namePattern", required: true)]
        public Input<string> NamePattern { get; set; } = null!;

        /// <summary>
        /// Repository owner.
        /// </summary>
        [Input("owner", required: true)]
        public Input<string> Owner { get; set; } = null!;

        /// <summary>
        /// Repository name.
        /// </summary>
        [Input("repository", required: true)]
        public Input<string> Repository { get; set; } = null!;

        [Input("whitelistTeams")]
        private InputList<string>? _whitelistTeams;

        /// <summary>
        /// Teams allowed to create matching tags.
        /// </summary>
        public InputList<string> WhitelistTeams
        {
            get => _whitelistTeams ?? (_whitelistTeams = new InputList<string>());
            set => _whitelistTeams = value;
        }

        [Input("whitelistUsernames")]
        private InputList<string>? _whitelistUsernames;

        /// <summary>
        /// Users allowed to create matching tags.
        /// </summary>
        public InputList<string> WhitelistUsernames
        {
            get => _whitelistUsernames ?? (_whitelistUsernames = new InputList<string>());
            set => _whitelistUsernames = value;
        }

        public RepositoryTagProtectionArgs()
        {
        }
        public static new RepositoryTagProtectionArgs Empty => new RepositoryTagProtectionArgs();
    }
}
