// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Forgejo
{
    /// <summary>
    /// A Forgejo repository push mirror, optionally limited to matching branches.
    /// </summary>
    [ForgejoResourceType("forgejo:index:RepositoryPushMirror")]
    public partial class RepositoryPushMirror : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Optional branch filter for the push mirror. Leave empty to mirror all branches.
        /// </summary>
        [Output("branchFilter")]
        public Output<string?> BranchFilter { get; private set; } = null!;

        [Output("created")]
        public Output<string> Created { get; private set; } = null!;

        /// <summary>
        /// Mirror sync interval, for example 8h30m0s. Leave empty to use Forgejo's default.
        /// </summary>
        [Output("interval")]
        public Output<string?> Interval { get; private set; } = null!;

        [Output("lastError")]
        public Output<string> LastError { get; private set; } = null!;

        [Output("lastUpdate")]
        public Output<string> LastUpdate { get; private set; } = null!;

        /// <summary>
        /// Repository owner.
        /// </summary>
        [Output("owner")]
        public Output<string> Owner { get; private set; } = null!;

        [Output("publicKey")]
        public Output<string> PublicKey { get; private set; } = null!;

        /// <summary>
        /// Target remote URL for the push mirror.
        /// </summary>
        [Output("remoteAddress")]
        public Output<string> RemoteAddress { get; private set; } = null!;

        [Output("remoteName")]
        public Output<string> RemoteName { get; private set; } = null!;

        /// <summary>
        /// Password or token for authenticating to the remote.
        /// </summary>
        [Output("remotePassword")]
        public Output<string?> RemotePassword { get; private set; } = null!;

        /// <summary>
        /// Username for authenticating to the remote.
        /// </summary>
        [Output("remoteUsername")]
        public Output<string?> RemoteUsername { get; private set; } = null!;

        /// <summary>
        /// Repository name.
        /// </summary>
        [Output("repository")]
        public Output<string> Repository { get; private set; } = null!;

        /// <summary>
        /// Whether pushes to this repository trigger the mirror.
        /// </summary>
        [Output("syncOnCommit")]
        public Output<bool?> SyncOnCommit { get; private set; } = null!;

        /// <summary>
        /// Whether Forgejo should use an SSH key for the push mirror remote.
        /// </summary>
        [Output("useSsh")]
        public Output<bool?> UseSsh { get; private set; } = null!;


        /// <summary>
        /// Create a RepositoryPushMirror resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public RepositoryPushMirror(string name, RepositoryPushMirrorArgs args, CustomResourceOptions? options = null)
            : base("forgejo:index:RepositoryPushMirror", name, args ?? new RepositoryPushMirrorArgs(), MakeResourceOptions(options, ""))
        {
        }

        private RepositoryPushMirror(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("forgejo:index:RepositoryPushMirror", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://forgejo.siron.casa/sironheart/forgejo-pulumi-provider/releases/download/v${VERSION}/",
                AdditionalSecretOutputs =
                {
                    "remotePassword",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing RepositoryPushMirror resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static RepositoryPushMirror Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new RepositoryPushMirror(name, id, options);
        }
    }

    public sealed class RepositoryPushMirrorArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Optional branch filter for the push mirror. Leave empty to mirror all branches.
        /// </summary>
        [Input("branchFilter")]
        public Input<string>? BranchFilter { get; set; }

        /// <summary>
        /// Mirror sync interval, for example 8h30m0s. Leave empty to use Forgejo's default.
        /// </summary>
        [Input("interval")]
        public Input<string>? Interval { get; set; }

        /// <summary>
        /// Repository owner.
        /// </summary>
        [Input("owner", required: true)]
        public Input<string> Owner { get; set; } = null!;

        /// <summary>
        /// Target remote URL for the push mirror.
        /// </summary>
        [Input("remoteAddress", required: true)]
        public Input<string> RemoteAddress { get; set; } = null!;

        [Input("remotePassword")]
        private Input<string>? _remotePassword;

        /// <summary>
        /// Password or token for authenticating to the remote.
        /// </summary>
        public Input<string>? RemotePassword
        {
            get => _remotePassword;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _remotePassword = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Username for authenticating to the remote.
        /// </summary>
        [Input("remoteUsername")]
        public Input<string>? RemoteUsername { get; set; }

        /// <summary>
        /// Repository name.
        /// </summary>
        [Input("repository", required: true)]
        public Input<string> Repository { get; set; } = null!;

        /// <summary>
        /// Whether pushes to this repository trigger the mirror.
        /// </summary>
        [Input("syncOnCommit")]
        public Input<bool>? SyncOnCommit { get; set; }

        /// <summary>
        /// Whether Forgejo should use an SSH key for the push mirror remote.
        /// </summary>
        [Input("useSsh")]
        public Input<bool>? UseSsh { get; set; }

        public RepositoryPushMirrorArgs()
        {
        }
        public static new RepositoryPushMirrorArgs Empty => new RepositoryPushMirrorArgs();
    }
}
