// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Forgejo
{
    /// <summary>
    /// Settings for enabled Forgejo repository units and their wiki or issue tracker configuration.
    /// </summary>
    [ForgejoResourceType("forgejo:index:RepositorySettings")]
    public partial class RepositorySettings : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Whether the actions unit is enabled. Leave unset to avoid managing it.
        /// </summary>
        [Output("actions")]
        public Output<bool?> Actions { get; private set; } = null!;

        /// <summary>
        /// Whether fast-forward-only merges are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
        /// </summary>
        [Output("allowFastForwardOnlyMerge")]
        public Output<bool?> AllowFastForwardOnlyMerge { get; private set; } = null!;

        /// <summary>
        /// Whether merge commits are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
        /// </summary>
        [Output("allowMergeCommits")]
        public Output<bool?> AllowMergeCommits { get; private set; } = null!;

        /// <summary>
        /// Whether rebase merges are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
        /// </summary>
        [Output("allowRebase")]
        public Output<bool?> AllowRebase { get; private set; } = null!;

        /// <summary>
        /// Whether rebase-merge (rebase with merge commit) is allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
        /// </summary>
        [Output("allowRebaseMerge")]
        public Output<bool?> AllowRebaseMerge { get; private set; } = null!;

        /// <summary>
        /// Whether squash merges are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
        /// </summary>
        [Output("allowSquashMerge")]
        public Output<bool?> AllowSquashMerge { get; private set; } = null!;

        /// <summary>
        /// Whether the repository is archived. Leave unset to avoid managing it.
        /// </summary>
        [Output("archived")]
        public Output<bool?> Archived { get; private set; } = null!;

        /// <summary>
        /// Whether Forgejo deletes pull request branches by default after merge. Setting this also enables pull requests unless pullRequests is explicitly set.
        /// </summary>
        [Output("defaultDeleteBranchAfterMerge")]
        public Output<bool?> DefaultDeleteBranchAfterMerge { get; private set; } = null!;

        /// <summary>
        /// Default merge style: merge, rebase, rebase-merge, squash, or fast-forward-only. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
        /// </summary>
        [Output("defaultMergeStyle")]
        public Output<string?> DefaultMergeStyle { get; private set; } = null!;

        /// <summary>
        /// External issue tracker URL format. Forgejo supports placeholders such as {user}, {repo}, and {index}.
        /// </summary>
        [Output("externalTrackerFormat")]
        public Output<string?> ExternalTrackerFormat { get; private set; } = null!;

        /// <summary>
        /// External issue tracker regular expression pattern.
        /// </summary>
        [Output("externalTrackerRegexPattern")]
        public Output<string?> ExternalTrackerRegexPattern { get; private set; } = null!;

        /// <summary>
        /// External issue tracker number style, for example numeric or alphanumeric.
        /// </summary>
        [Output("externalTrackerStyle")]
        public Output<string?> ExternalTrackerStyle { get; private set; } = null!;

        /// <summary>
        /// External issue tracker URL. Setting this also enables issues unless issues is explicitly set.
        /// </summary>
        [Output("externalTrackerUrl")]
        public Output<string?> ExternalTrackerUrl { get; private set; } = null!;

        /// <summary>
        /// External wiki URL. Setting this also enables the wiki unless wiki is explicitly set.
        /// </summary>
        [Output("externalWikiUrl")]
        public Output<string?> ExternalWikiUrl { get; private set; } = null!;

        /// <summary>
        /// Whether the wiki is globally editable.
        /// </summary>
        [Output("globallyEditableWiki")]
        public Output<bool?> GloballyEditableWiki { get; private set; } = null!;

        /// <summary>
        /// Whether only contributors may track time in the internal issue tracker.
        /// </summary>
        [Output("internalTrackerAllowOnlyContributorsToTrackTime")]
        public Output<bool?> InternalTrackerAllowOnlyContributorsToTrackTime { get; private set; } = null!;

        /// <summary>
        /// Whether issue dependencies are enabled in the internal issue tracker.
        /// </summary>
        [Output("internalTrackerEnableIssueDependencies")]
        public Output<bool?> InternalTrackerEnableIssueDependencies { get; private set; } = null!;

        /// <summary>
        /// Whether the internal issue tracker has time tracking enabled.
        /// </summary>
        [Output("internalTrackerEnableTimeTracker")]
        public Output<bool?> InternalTrackerEnableTimeTracker { get; private set; } = null!;

        /// <summary>
        /// Whether the issue tracker unit is enabled. Leave unset to avoid managing it.
        /// </summary>
        [Output("issues")]
        public Output<bool?> Issues { get; private set; } = null!;

        /// <summary>
        /// Repository owner.
        /// </summary>
        [Output("owner")]
        public Output<string> Owner { get; private set; } = null!;

        /// <summary>
        /// Whether the packages unit is enabled. Leave unset to avoid managing it.
        /// </summary>
        [Output("packages")]
        public Output<bool?> Packages { get; private set; } = null!;

        /// <summary>
        /// Whether the projects unit is enabled. Leave unset to avoid managing it.
        /// </summary>
        [Output("projects")]
        public Output<bool?> Projects { get; private set; } = null!;

        /// <summary>
        /// Whether the pull request unit is enabled. Leave unset to avoid managing it.
        /// </summary>
        [Output("pullRequests")]
        public Output<bool?> PullRequests { get; private set; } = null!;

        /// <summary>
        /// Whether the releases unit is enabled. Leave unset to avoid managing it.
        /// </summary>
        [Output("releases")]
        public Output<bool?> Releases { get; private set; } = null!;

        /// <summary>
        /// Repository name.
        /// </summary>
        [Output("repository")]
        public Output<string> Repository { get; private set; } = null!;

        /// <summary>
        /// Whether the wiki unit is enabled. Leave unset to avoid managing it.
        /// </summary>
        [Output("wiki")]
        public Output<bool?> Wiki { get; private set; } = null!;

        /// <summary>
        /// Branch used for the repository wiki.
        /// </summary>
        [Output("wikiBranch")]
        public Output<string?> WikiBranch { get; private set; } = null!;


        /// <summary>
        /// Create a RepositorySettings resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public RepositorySettings(string name, RepositorySettingsArgs args, CustomResourceOptions? options = null)
            : base("forgejo:index:RepositorySettings", name, args ?? new RepositorySettingsArgs(), MakeResourceOptions(options, ""))
        {
        }

        private RepositorySettings(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("forgejo:index:RepositorySettings", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://forgejo.siron.casa/sironheart/forgejo-pulumi-provider/releases/download/v${VERSION}/",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing RepositorySettings resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static RepositorySettings Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new RepositorySettings(name, id, options);
        }
    }

    public sealed class RepositorySettingsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether the actions unit is enabled. Leave unset to avoid managing it.
        /// </summary>
        [Input("actions")]
        public Input<bool>? Actions { get; set; }

        /// <summary>
        /// Whether fast-forward-only merges are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
        /// </summary>
        [Input("allowFastForwardOnlyMerge")]
        public Input<bool>? AllowFastForwardOnlyMerge { get; set; }

        /// <summary>
        /// Whether merge commits are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
        /// </summary>
        [Input("allowMergeCommits")]
        public Input<bool>? AllowMergeCommits { get; set; }

        /// <summary>
        /// Whether rebase merges are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
        /// </summary>
        [Input("allowRebase")]
        public Input<bool>? AllowRebase { get; set; }

        /// <summary>
        /// Whether rebase-merge (rebase with merge commit) is allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
        /// </summary>
        [Input("allowRebaseMerge")]
        public Input<bool>? AllowRebaseMerge { get; set; }

        /// <summary>
        /// Whether squash merges are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
        /// </summary>
        [Input("allowSquashMerge")]
        public Input<bool>? AllowSquashMerge { get; set; }

        /// <summary>
        /// Whether the repository is archived. Leave unset to avoid managing it.
        /// </summary>
        [Input("archived")]
        public Input<bool>? Archived { get; set; }

        /// <summary>
        /// Whether Forgejo deletes pull request branches by default after merge. Setting this also enables pull requests unless pullRequests is explicitly set.
        /// </summary>
        [Input("defaultDeleteBranchAfterMerge")]
        public Input<bool>? DefaultDeleteBranchAfterMerge { get; set; }

        /// <summary>
        /// Default merge style: merge, rebase, rebase-merge, squash, or fast-forward-only. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
        /// </summary>
        [Input("defaultMergeStyle")]
        public Input<string>? DefaultMergeStyle { get; set; }

        /// <summary>
        /// External issue tracker URL format. Forgejo supports placeholders such as {user}, {repo}, and {index}.
        /// </summary>
        [Input("externalTrackerFormat")]
        public Input<string>? ExternalTrackerFormat { get; set; }

        /// <summary>
        /// External issue tracker regular expression pattern.
        /// </summary>
        [Input("externalTrackerRegexPattern")]
        public Input<string>? ExternalTrackerRegexPattern { get; set; }

        /// <summary>
        /// External issue tracker number style, for example numeric or alphanumeric.
        /// </summary>
        [Input("externalTrackerStyle")]
        public Input<string>? ExternalTrackerStyle { get; set; }

        /// <summary>
        /// External issue tracker URL. Setting this also enables issues unless issues is explicitly set.
        /// </summary>
        [Input("externalTrackerUrl")]
        public Input<string>? ExternalTrackerUrl { get; set; }

        /// <summary>
        /// External wiki URL. Setting this also enables the wiki unless wiki is explicitly set.
        /// </summary>
        [Input("externalWikiUrl")]
        public Input<string>? ExternalWikiUrl { get; set; }

        /// <summary>
        /// Whether the wiki is globally editable.
        /// </summary>
        [Input("globallyEditableWiki")]
        public Input<bool>? GloballyEditableWiki { get; set; }

        /// <summary>
        /// Whether only contributors may track time in the internal issue tracker.
        /// </summary>
        [Input("internalTrackerAllowOnlyContributorsToTrackTime")]
        public Input<bool>? InternalTrackerAllowOnlyContributorsToTrackTime { get; set; }

        /// <summary>
        /// Whether issue dependencies are enabled in the internal issue tracker.
        /// </summary>
        [Input("internalTrackerEnableIssueDependencies")]
        public Input<bool>? InternalTrackerEnableIssueDependencies { get; set; }

        /// <summary>
        /// Whether the internal issue tracker has time tracking enabled.
        /// </summary>
        [Input("internalTrackerEnableTimeTracker")]
        public Input<bool>? InternalTrackerEnableTimeTracker { get; set; }

        /// <summary>
        /// Whether the issue tracker unit is enabled. Leave unset to avoid managing it.
        /// </summary>
        [Input("issues")]
        public Input<bool>? Issues { get; set; }

        /// <summary>
        /// Repository owner.
        /// </summary>
        [Input("owner", required: true)]
        public Input<string> Owner { get; set; } = null!;

        /// <summary>
        /// Whether the packages unit is enabled. Leave unset to avoid managing it.
        /// </summary>
        [Input("packages")]
        public Input<bool>? Packages { get; set; }

        /// <summary>
        /// Whether the projects unit is enabled. Leave unset to avoid managing it.
        /// </summary>
        [Input("projects")]
        public Input<bool>? Projects { get; set; }

        /// <summary>
        /// Whether the pull request unit is enabled. Leave unset to avoid managing it.
        /// </summary>
        [Input("pullRequests")]
        public Input<bool>? PullRequests { get; set; }

        /// <summary>
        /// Whether the releases unit is enabled. Leave unset to avoid managing it.
        /// </summary>
        [Input("releases")]
        public Input<bool>? Releases { get; set; }

        /// <summary>
        /// Repository name.
        /// </summary>
        [Input("repository", required: true)]
        public Input<string> Repository { get; set; } = null!;

        /// <summary>
        /// Whether the wiki unit is enabled. Leave unset to avoid managing it.
        /// </summary>
        [Input("wiki")]
        public Input<bool>? Wiki { get; set; }

        /// <summary>
        /// Branch used for the repository wiki.
        /// </summary>
        [Input("wikiBranch")]
        public Input<string>? WikiBranch { get; set; }

        public RepositorySettingsArgs()
        {
        }
        public static new RepositorySettingsArgs Empty => new RepositorySettingsArgs();
    }
}
