// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package forgejo

import (
	"context"
	"reflect"

	"errors"
	"forgejo.siron.casa/sironheart/forgejo-pulumi-provider/sdk/go/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A Forgejo deploy key for a repository.
type DeployKey struct {
	pulumi.CustomResourceState

	Fingerprint pulumi.StringOutput `pulumi:"fingerprint"`
	// OpenSSH public key material.
	Key   pulumi.StringOutput `pulumi:"key"`
	KeyId pulumi.IntOutput    `pulumi:"keyId"`
	// Repository owner.
	Owner pulumi.StringOutput `pulumi:"owner"`
	// Whether the deploy key is read-only.
	ReadOnly pulumi.BoolPtrOutput `pulumi:"readOnly"`
	// Repository name.
	Repository pulumi.StringOutput `pulumi:"repository"`
	// Deploy key title.
	Title pulumi.StringOutput `pulumi:"title"`
	Url   pulumi.StringOutput `pulumi:"url"`
}

// NewDeployKey registers a new resource with the given unique name, arguments, and options.
func NewDeployKey(ctx *pulumi.Context,
	name string, args *DeployKeyArgs, opts ...pulumi.ResourceOption) (*DeployKey, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Key == nil {
		return nil, errors.New("invalid value for required argument 'Key'")
	}
	if args.Owner == nil {
		return nil, errors.New("invalid value for required argument 'Owner'")
	}
	if args.Repository == nil {
		return nil, errors.New("invalid value for required argument 'Repository'")
	}
	if args.Title == nil {
		return nil, errors.New("invalid value for required argument 'Title'")
	}
	if args.ReadOnly == nil {
		args.ReadOnly = pulumi.BoolPtr(true)
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DeployKey
	err := ctx.RegisterResource("forgejo:index:DeployKey", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDeployKey gets an existing DeployKey resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDeployKey(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DeployKeyState, opts ...pulumi.ResourceOption) (*DeployKey, error) {
	var resource DeployKey
	err := ctx.ReadResource("forgejo:index:DeployKey", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DeployKey resources.
type deployKeyState struct {
}

type DeployKeyState struct {
}

func (DeployKeyState) ElementType() reflect.Type {
	return reflect.TypeOf((*deployKeyState)(nil)).Elem()
}

type deployKeyArgs struct {
	// OpenSSH public key material.
	Key string `pulumi:"key"`
	// Repository owner.
	Owner string `pulumi:"owner"`
	// Whether the deploy key is read-only.
	ReadOnly *bool `pulumi:"readOnly"`
	// Repository name.
	Repository string `pulumi:"repository"`
	// Deploy key title.
	Title string `pulumi:"title"`
}

// The set of arguments for constructing a DeployKey resource.
type DeployKeyArgs struct {
	// OpenSSH public key material.
	Key pulumi.StringInput
	// Repository owner.
	Owner pulumi.StringInput
	// Whether the deploy key is read-only.
	ReadOnly pulumi.BoolPtrInput
	// Repository name.
	Repository pulumi.StringInput
	// Deploy key title.
	Title pulumi.StringInput
}

func (DeployKeyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*deployKeyArgs)(nil)).Elem()
}

type DeployKeyInput interface {
	pulumi.Input

	ToDeployKeyOutput() DeployKeyOutput
	ToDeployKeyOutputWithContext(ctx context.Context) DeployKeyOutput
}

func (*DeployKey) ElementType() reflect.Type {
	return reflect.TypeOf((**DeployKey)(nil)).Elem()
}

func (i *DeployKey) ToDeployKeyOutput() DeployKeyOutput {
	return i.ToDeployKeyOutputWithContext(context.Background())
}

func (i *DeployKey) ToDeployKeyOutputWithContext(ctx context.Context) DeployKeyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DeployKeyOutput)
}

type DeployKeyOutput struct{ *pulumi.OutputState }

func (DeployKeyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DeployKey)(nil)).Elem()
}

func (o DeployKeyOutput) ToDeployKeyOutput() DeployKeyOutput {
	return o
}

func (o DeployKeyOutput) ToDeployKeyOutputWithContext(ctx context.Context) DeployKeyOutput {
	return o
}

func (o DeployKeyOutput) Fingerprint() pulumi.StringOutput {
	return o.ApplyT(func(v *DeployKey) pulumi.StringOutput { return v.Fingerprint }).(pulumi.StringOutput)
}

// OpenSSH public key material.
func (o DeployKeyOutput) Key() pulumi.StringOutput {
	return o.ApplyT(func(v *DeployKey) pulumi.StringOutput { return v.Key }).(pulumi.StringOutput)
}

func (o DeployKeyOutput) KeyId() pulumi.IntOutput {
	return o.ApplyT(func(v *DeployKey) pulumi.IntOutput { return v.KeyId }).(pulumi.IntOutput)
}

// Repository owner.
func (o DeployKeyOutput) Owner() pulumi.StringOutput {
	return o.ApplyT(func(v *DeployKey) pulumi.StringOutput { return v.Owner }).(pulumi.StringOutput)
}

// Whether the deploy key is read-only.
func (o DeployKeyOutput) ReadOnly() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *DeployKey) pulumi.BoolPtrOutput { return v.ReadOnly }).(pulumi.BoolPtrOutput)
}

// Repository name.
func (o DeployKeyOutput) Repository() pulumi.StringOutput {
	return o.ApplyT(func(v *DeployKey) pulumi.StringOutput { return v.Repository }).(pulumi.StringOutput)
}

// Deploy key title.
func (o DeployKeyOutput) Title() pulumi.StringOutput {
	return o.ApplyT(func(v *DeployKey) pulumi.StringOutput { return v.Title }).(pulumi.StringOutput)
}

func (o DeployKeyOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v *DeployKey) pulumi.StringOutput { return v.Url }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DeployKeyInput)(nil)).Elem(), &DeployKey{})
	pulumi.RegisterOutputType(DeployKeyOutput{})
}
