// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package forgejopulumiprovider

import (
	"fmt"

	"forgejo.siron.casa/sironheart/forgejo-pulumi-provider/sdk/go/internal"
	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "forgejo:index:DeployKey":
		r = &DeployKey{}
	case "forgejo:index:Organization":
		r = &Organization{}
	case "forgejo:index:OrganizationActionSecret":
		r = &OrganizationActionSecret{}
	case "forgejo:index:OrganizationActionVariable":
		r = &OrganizationActionVariable{}
	case "forgejo:index:OrganizationTeam":
		r = &OrganizationTeam{}
	case "forgejo:index:OrganizationTeamMember":
		r = &OrganizationTeamMember{}
	case "forgejo:index:PublicKey":
		r = &PublicKey{}
	case "forgejo:index:Repository":
		r = &Repository{}
	case "forgejo:index:RepositoryActionSecret":
		r = &RepositoryActionSecret{}
	case "forgejo:index:RepositoryActionVariable":
		r = &RepositoryActionVariable{}
	case "forgejo:index:RepositoryBranchProtection":
		r = &RepositoryBranchProtection{}
	case "forgejo:index:RepositoryPushMirror":
		r = &RepositoryPushMirror{}
	case "forgejo:index:RepositorySettings":
		r = &RepositorySettings{}
	case "forgejo:index:RepositoryTagProtection":
		r = &RepositoryTagProtection{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:forgejo" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"forgejo",
		"index",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"forgejo",
		&pkg{version},
	)
}
