// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package forgejo

import (
	"context"
	"reflect"

	"errors"
	"forgejo.siron.casa/sironheart/forgejo-pulumi-provider/sdk/go/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A Forgejo organization.
type Organization struct {
	pulumi.CustomResourceState

	AvatarUrl pulumi.StringOutput `pulumi:"avatarUrl"`
	// Organization description.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Organization display name.
	FullName pulumi.StringPtrOutput `pulumi:"fullName"`
	// Organization location.
	Location pulumi.StringPtrOutput `pulumi:"location"`
	// Organization username/slug.
	Name pulumi.StringOutput `pulumi:"name"`
	// Organization visibility, for example public, limited, or private. Leave empty to use Forgejo's default.
	Visibility pulumi.StringPtrOutput `pulumi:"visibility"`
	// Organization website URL.
	Website pulumi.StringPtrOutput `pulumi:"website"`
}

// NewOrganization registers a new resource with the given unique name, arguments, and options.
func NewOrganization(ctx *pulumi.Context,
	name string, args *OrganizationArgs, opts ...pulumi.ResourceOption) (*Organization, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Organization
	err := ctx.RegisterResource("forgejo:index:Organization", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetOrganization gets an existing Organization resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetOrganization(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *OrganizationState, opts ...pulumi.ResourceOption) (*Organization, error) {
	var resource Organization
	err := ctx.ReadResource("forgejo:index:Organization", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Organization resources.
type organizationState struct {
}

type OrganizationState struct {
}

func (OrganizationState) ElementType() reflect.Type {
	return reflect.TypeOf((*organizationState)(nil)).Elem()
}

type organizationArgs struct {
	// Organization description.
	Description *string `pulumi:"description"`
	// Organization display name.
	FullName *string `pulumi:"fullName"`
	// Organization location.
	Location *string `pulumi:"location"`
	// Organization username/slug.
	Name string `pulumi:"name"`
	// Organization visibility, for example public, limited, or private. Leave empty to use Forgejo's default.
	Visibility *string `pulumi:"visibility"`
	// Organization website URL.
	Website *string `pulumi:"website"`
}

// The set of arguments for constructing a Organization resource.
type OrganizationArgs struct {
	// Organization description.
	Description pulumi.StringPtrInput
	// Organization display name.
	FullName pulumi.StringPtrInput
	// Organization location.
	Location pulumi.StringPtrInput
	// Organization username/slug.
	Name pulumi.StringInput
	// Organization visibility, for example public, limited, or private. Leave empty to use Forgejo's default.
	Visibility pulumi.StringPtrInput
	// Organization website URL.
	Website pulumi.StringPtrInput
}

func (OrganizationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*organizationArgs)(nil)).Elem()
}

type OrganizationInput interface {
	pulumi.Input

	ToOrganizationOutput() OrganizationOutput
	ToOrganizationOutputWithContext(ctx context.Context) OrganizationOutput
}

func (*Organization) ElementType() reflect.Type {
	return reflect.TypeOf((**Organization)(nil)).Elem()
}

func (i *Organization) ToOrganizationOutput() OrganizationOutput {
	return i.ToOrganizationOutputWithContext(context.Background())
}

func (i *Organization) ToOrganizationOutputWithContext(ctx context.Context) OrganizationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OrganizationOutput)
}

type OrganizationOutput struct{ *pulumi.OutputState }

func (OrganizationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Organization)(nil)).Elem()
}

func (o OrganizationOutput) ToOrganizationOutput() OrganizationOutput {
	return o
}

func (o OrganizationOutput) ToOrganizationOutputWithContext(ctx context.Context) OrganizationOutput {
	return o
}

func (o OrganizationOutput) AvatarUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *Organization) pulumi.StringOutput { return v.AvatarUrl }).(pulumi.StringOutput)
}

// Organization description.
func (o OrganizationOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Organization) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Organization display name.
func (o OrganizationOutput) FullName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Organization) pulumi.StringPtrOutput { return v.FullName }).(pulumi.StringPtrOutput)
}

// Organization location.
func (o OrganizationOutput) Location() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Organization) pulumi.StringPtrOutput { return v.Location }).(pulumi.StringPtrOutput)
}

// Organization username/slug.
func (o OrganizationOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Organization) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Organization visibility, for example public, limited, or private. Leave empty to use Forgejo's default.
func (o OrganizationOutput) Visibility() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Organization) pulumi.StringPtrOutput { return v.Visibility }).(pulumi.StringPtrOutput)
}

// Organization website URL.
func (o OrganizationOutput) Website() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Organization) pulumi.StringPtrOutput { return v.Website }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*OrganizationInput)(nil)).Elem(), &Organization{})
	pulumi.RegisterOutputType(OrganizationOutput{})
}
