// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package forgejopulumiprovider

import (
	"context"
	"reflect"

	"errors"
	"forgejo.siron.casa/sironheart/forgejo-pulumi-provider/sdk/go/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A Forgejo SSH public key for the authenticated user.
type PublicKey struct {
	pulumi.CustomResourceState

	Fingerprint pulumi.StringOutput `pulumi:"fingerprint"`
	// OpenSSH public key material.
	Key     pulumi.StringOutput `pulumi:"key"`
	KeyId   pulumi.IntOutput    `pulumi:"keyId"`
	KeyType pulumi.StringOutput `pulumi:"keyType"`
	Owner   pulumi.StringOutput `pulumi:"owner"`
	// Whether the key has read-only access.
	ReadOnly pulumi.BoolPtrOutput `pulumi:"readOnly"`
	// Public key title.
	Title pulumi.StringOutput `pulumi:"title"`
	Url   pulumi.StringOutput `pulumi:"url"`
}

// NewPublicKey registers a new resource with the given unique name, arguments, and options.
func NewPublicKey(ctx *pulumi.Context,
	name string, args *PublicKeyArgs, opts ...pulumi.ResourceOption) (*PublicKey, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Key == nil {
		return nil, errors.New("invalid value for required argument 'Key'")
	}
	if args.Title == nil {
		return nil, errors.New("invalid value for required argument 'Title'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource PublicKey
	err := ctx.RegisterResource("forgejo:index:PublicKey", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPublicKey gets an existing PublicKey resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPublicKey(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PublicKeyState, opts ...pulumi.ResourceOption) (*PublicKey, error) {
	var resource PublicKey
	err := ctx.ReadResource("forgejo:index:PublicKey", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PublicKey resources.
type publicKeyState struct {
}

type PublicKeyState struct {
}

func (PublicKeyState) ElementType() reflect.Type {
	return reflect.TypeOf((*publicKeyState)(nil)).Elem()
}

type publicKeyArgs struct {
	// OpenSSH public key material.
	Key string `pulumi:"key"`
	// Whether the key has read-only access.
	ReadOnly *bool `pulumi:"readOnly"`
	// Public key title.
	Title string `pulumi:"title"`
}

// The set of arguments for constructing a PublicKey resource.
type PublicKeyArgs struct {
	// OpenSSH public key material.
	Key pulumi.StringInput
	// Whether the key has read-only access.
	ReadOnly pulumi.BoolPtrInput
	// Public key title.
	Title pulumi.StringInput
}

func (PublicKeyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*publicKeyArgs)(nil)).Elem()
}

type PublicKeyInput interface {
	pulumi.Input

	ToPublicKeyOutput() PublicKeyOutput
	ToPublicKeyOutputWithContext(ctx context.Context) PublicKeyOutput
}

func (*PublicKey) ElementType() reflect.Type {
	return reflect.TypeOf((**PublicKey)(nil)).Elem()
}

func (i *PublicKey) ToPublicKeyOutput() PublicKeyOutput {
	return i.ToPublicKeyOutputWithContext(context.Background())
}

func (i *PublicKey) ToPublicKeyOutputWithContext(ctx context.Context) PublicKeyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PublicKeyOutput)
}

type PublicKeyOutput struct{ *pulumi.OutputState }

func (PublicKeyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PublicKey)(nil)).Elem()
}

func (o PublicKeyOutput) ToPublicKeyOutput() PublicKeyOutput {
	return o
}

func (o PublicKeyOutput) ToPublicKeyOutputWithContext(ctx context.Context) PublicKeyOutput {
	return o
}

func (o PublicKeyOutput) Fingerprint() pulumi.StringOutput {
	return o.ApplyT(func(v *PublicKey) pulumi.StringOutput { return v.Fingerprint }).(pulumi.StringOutput)
}

// OpenSSH public key material.
func (o PublicKeyOutput) Key() pulumi.StringOutput {
	return o.ApplyT(func(v *PublicKey) pulumi.StringOutput { return v.Key }).(pulumi.StringOutput)
}

func (o PublicKeyOutput) KeyId() pulumi.IntOutput {
	return o.ApplyT(func(v *PublicKey) pulumi.IntOutput { return v.KeyId }).(pulumi.IntOutput)
}

func (o PublicKeyOutput) KeyType() pulumi.StringOutput {
	return o.ApplyT(func(v *PublicKey) pulumi.StringOutput { return v.KeyType }).(pulumi.StringOutput)
}

func (o PublicKeyOutput) Owner() pulumi.StringOutput {
	return o.ApplyT(func(v *PublicKey) pulumi.StringOutput { return v.Owner }).(pulumi.StringOutput)
}

// Whether the key has read-only access.
func (o PublicKeyOutput) ReadOnly() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *PublicKey) pulumi.BoolPtrOutput { return v.ReadOnly }).(pulumi.BoolPtrOutput)
}

// Public key title.
func (o PublicKeyOutput) Title() pulumi.StringOutput {
	return o.ApplyT(func(v *PublicKey) pulumi.StringOutput { return v.Title }).(pulumi.StringOutput)
}

func (o PublicKeyOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v *PublicKey) pulumi.StringOutput { return v.Url }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PublicKeyInput)(nil)).Elem(), &PublicKey{})
	pulumi.RegisterOutputType(PublicKeyOutput{})
}
