// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package forgejopulumiprovider

import (
	"context"
	"reflect"

	"errors"
	"forgejo.siron.casa/sironheart/forgejo-pulumi-provider/sdk/go/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A Forgejo tag protection rule for a repository.
type RepositoryTagProtection struct {
	pulumi.CustomResourceState

	// Protected tag name pattern, for example v*.
	NamePattern pulumi.StringOutput `pulumi:"namePattern"`
	// Repository owner.
	Owner        pulumi.StringOutput `pulumi:"owner"`
	ProtectionId pulumi.IntOutput    `pulumi:"protectionId"`
	// Repository name.
	Repository pulumi.StringOutput `pulumi:"repository"`
	// Teams allowed to create matching tags.
	WhitelistTeams pulumi.StringArrayOutput `pulumi:"whitelistTeams"`
	// Users allowed to create matching tags.
	WhitelistUsernames pulumi.StringArrayOutput `pulumi:"whitelistUsernames"`
}

// NewRepositoryTagProtection registers a new resource with the given unique name, arguments, and options.
func NewRepositoryTagProtection(ctx *pulumi.Context,
	name string, args *RepositoryTagProtectionArgs, opts ...pulumi.ResourceOption) (*RepositoryTagProtection, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.NamePattern == nil {
		return nil, errors.New("invalid value for required argument 'NamePattern'")
	}
	if args.Owner == nil {
		return nil, errors.New("invalid value for required argument 'Owner'")
	}
	if args.Repository == nil {
		return nil, errors.New("invalid value for required argument 'Repository'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource RepositoryTagProtection
	err := ctx.RegisterResource("forgejo:index:RepositoryTagProtection", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRepositoryTagProtection gets an existing RepositoryTagProtection resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRepositoryTagProtection(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RepositoryTagProtectionState, opts ...pulumi.ResourceOption) (*RepositoryTagProtection, error) {
	var resource RepositoryTagProtection
	err := ctx.ReadResource("forgejo:index:RepositoryTagProtection", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering RepositoryTagProtection resources.
type repositoryTagProtectionState struct {
}

type RepositoryTagProtectionState struct {
}

func (RepositoryTagProtectionState) ElementType() reflect.Type {
	return reflect.TypeOf((*repositoryTagProtectionState)(nil)).Elem()
}

type repositoryTagProtectionArgs struct {
	// Protected tag name pattern, for example v*.
	NamePattern string `pulumi:"namePattern"`
	// Repository owner.
	Owner string `pulumi:"owner"`
	// Repository name.
	Repository string `pulumi:"repository"`
	// Teams allowed to create matching tags.
	WhitelistTeams []string `pulumi:"whitelistTeams"`
	// Users allowed to create matching tags.
	WhitelistUsernames []string `pulumi:"whitelistUsernames"`
}

// The set of arguments for constructing a RepositoryTagProtection resource.
type RepositoryTagProtectionArgs struct {
	// Protected tag name pattern, for example v*.
	NamePattern pulumi.StringInput
	// Repository owner.
	Owner pulumi.StringInput
	// Repository name.
	Repository pulumi.StringInput
	// Teams allowed to create matching tags.
	WhitelistTeams pulumi.StringArrayInput
	// Users allowed to create matching tags.
	WhitelistUsernames pulumi.StringArrayInput
}

func (RepositoryTagProtectionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*repositoryTagProtectionArgs)(nil)).Elem()
}

type RepositoryTagProtectionInput interface {
	pulumi.Input

	ToRepositoryTagProtectionOutput() RepositoryTagProtectionOutput
	ToRepositoryTagProtectionOutputWithContext(ctx context.Context) RepositoryTagProtectionOutput
}

func (*RepositoryTagProtection) ElementType() reflect.Type {
	return reflect.TypeOf((**RepositoryTagProtection)(nil)).Elem()
}

func (i *RepositoryTagProtection) ToRepositoryTagProtectionOutput() RepositoryTagProtectionOutput {
	return i.ToRepositoryTagProtectionOutputWithContext(context.Background())
}

func (i *RepositoryTagProtection) ToRepositoryTagProtectionOutputWithContext(ctx context.Context) RepositoryTagProtectionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RepositoryTagProtectionOutput)
}

type RepositoryTagProtectionOutput struct{ *pulumi.OutputState }

func (RepositoryTagProtectionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RepositoryTagProtection)(nil)).Elem()
}

func (o RepositoryTagProtectionOutput) ToRepositoryTagProtectionOutput() RepositoryTagProtectionOutput {
	return o
}

func (o RepositoryTagProtectionOutput) ToRepositoryTagProtectionOutputWithContext(ctx context.Context) RepositoryTagProtectionOutput {
	return o
}

// Protected tag name pattern, for example v*.
func (o RepositoryTagProtectionOutput) NamePattern() pulumi.StringOutput {
	return o.ApplyT(func(v *RepositoryTagProtection) pulumi.StringOutput { return v.NamePattern }).(pulumi.StringOutput)
}

// Repository owner.
func (o RepositoryTagProtectionOutput) Owner() pulumi.StringOutput {
	return o.ApplyT(func(v *RepositoryTagProtection) pulumi.StringOutput { return v.Owner }).(pulumi.StringOutput)
}

func (o RepositoryTagProtectionOutput) ProtectionId() pulumi.IntOutput {
	return o.ApplyT(func(v *RepositoryTagProtection) pulumi.IntOutput { return v.ProtectionId }).(pulumi.IntOutput)
}

// Repository name.
func (o RepositoryTagProtectionOutput) Repository() pulumi.StringOutput {
	return o.ApplyT(func(v *RepositoryTagProtection) pulumi.StringOutput { return v.Repository }).(pulumi.StringOutput)
}

// Teams allowed to create matching tags.
func (o RepositoryTagProtectionOutput) WhitelistTeams() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *RepositoryTagProtection) pulumi.StringArrayOutput { return v.WhitelistTeams }).(pulumi.StringArrayOutput)
}

// Users allowed to create matching tags.
func (o RepositoryTagProtectionOutput) WhitelistUsernames() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *RepositoryTagProtection) pulumi.StringArrayOutput { return v.WhitelistUsernames }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RepositoryTagProtectionInput)(nil)).Elem(), &RepositoryTagProtection{})
	pulumi.RegisterOutputType(RepositoryTagProtectionOutput{})
}
