// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package forgejo

import (
	"context"
	"reflect"

	"errors"
	"forgejo.siron.casa/sironheart/forgejo-pulumi-provider/sdk/go/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A Forgejo Actions variable for a repository.
type RepositoryActionVariable struct {
	pulumi.CustomResourceState

	// Actions variable name.
	Name pulumi.StringOutput `pulumi:"name"`
	// Repository owner.
	Owner   pulumi.StringOutput `pulumi:"owner"`
	OwnerId pulumi.IntOutput    `pulumi:"ownerId"`
	RepoId  pulumi.IntOutput    `pulumi:"repoId"`
	// Repository name.
	Repository pulumi.StringOutput `pulumi:"repository"`
	// Actions variable value.
	Value pulumi.StringOutput `pulumi:"value"`
}

// NewRepositoryActionVariable registers a new resource with the given unique name, arguments, and options.
func NewRepositoryActionVariable(ctx *pulumi.Context,
	name string, args *RepositoryActionVariableArgs, opts ...pulumi.ResourceOption) (*RepositoryActionVariable, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.Owner == nil {
		return nil, errors.New("invalid value for required argument 'Owner'")
	}
	if args.Repository == nil {
		return nil, errors.New("invalid value for required argument 'Repository'")
	}
	if args.Value == nil {
		return nil, errors.New("invalid value for required argument 'Value'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource RepositoryActionVariable
	err := ctx.RegisterResource("forgejo:index:RepositoryActionVariable", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRepositoryActionVariable gets an existing RepositoryActionVariable resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRepositoryActionVariable(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RepositoryActionVariableState, opts ...pulumi.ResourceOption) (*RepositoryActionVariable, error) {
	var resource RepositoryActionVariable
	err := ctx.ReadResource("forgejo:index:RepositoryActionVariable", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering RepositoryActionVariable resources.
type repositoryActionVariableState struct {
}

type RepositoryActionVariableState struct {
}

func (RepositoryActionVariableState) ElementType() reflect.Type {
	return reflect.TypeOf((*repositoryActionVariableState)(nil)).Elem()
}

type repositoryActionVariableArgs struct {
	// Actions variable name.
	Name string `pulumi:"name"`
	// Repository owner.
	Owner string `pulumi:"owner"`
	// Repository name.
	Repository string `pulumi:"repository"`
	// Actions variable value.
	Value string `pulumi:"value"`
}

// The set of arguments for constructing a RepositoryActionVariable resource.
type RepositoryActionVariableArgs struct {
	// Actions variable name.
	Name pulumi.StringInput
	// Repository owner.
	Owner pulumi.StringInput
	// Repository name.
	Repository pulumi.StringInput
	// Actions variable value.
	Value pulumi.StringInput
}

func (RepositoryActionVariableArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*repositoryActionVariableArgs)(nil)).Elem()
}

type RepositoryActionVariableInput interface {
	pulumi.Input

	ToRepositoryActionVariableOutput() RepositoryActionVariableOutput
	ToRepositoryActionVariableOutputWithContext(ctx context.Context) RepositoryActionVariableOutput
}

func (*RepositoryActionVariable) ElementType() reflect.Type {
	return reflect.TypeOf((**RepositoryActionVariable)(nil)).Elem()
}

func (i *RepositoryActionVariable) ToRepositoryActionVariableOutput() RepositoryActionVariableOutput {
	return i.ToRepositoryActionVariableOutputWithContext(context.Background())
}

func (i *RepositoryActionVariable) ToRepositoryActionVariableOutputWithContext(ctx context.Context) RepositoryActionVariableOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RepositoryActionVariableOutput)
}

type RepositoryActionVariableOutput struct{ *pulumi.OutputState }

func (RepositoryActionVariableOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RepositoryActionVariable)(nil)).Elem()
}

func (o RepositoryActionVariableOutput) ToRepositoryActionVariableOutput() RepositoryActionVariableOutput {
	return o
}

func (o RepositoryActionVariableOutput) ToRepositoryActionVariableOutputWithContext(ctx context.Context) RepositoryActionVariableOutput {
	return o
}

// Actions variable name.
func (o RepositoryActionVariableOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *RepositoryActionVariable) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Repository owner.
func (o RepositoryActionVariableOutput) Owner() pulumi.StringOutput {
	return o.ApplyT(func(v *RepositoryActionVariable) pulumi.StringOutput { return v.Owner }).(pulumi.StringOutput)
}

func (o RepositoryActionVariableOutput) OwnerId() pulumi.IntOutput {
	return o.ApplyT(func(v *RepositoryActionVariable) pulumi.IntOutput { return v.OwnerId }).(pulumi.IntOutput)
}

func (o RepositoryActionVariableOutput) RepoId() pulumi.IntOutput {
	return o.ApplyT(func(v *RepositoryActionVariable) pulumi.IntOutput { return v.RepoId }).(pulumi.IntOutput)
}

// Repository name.
func (o RepositoryActionVariableOutput) Repository() pulumi.StringOutput {
	return o.ApplyT(func(v *RepositoryActionVariable) pulumi.StringOutput { return v.Repository }).(pulumi.StringOutput)
}

// Actions variable value.
func (o RepositoryActionVariableOutput) Value() pulumi.StringOutput {
	return o.ApplyT(func(v *RepositoryActionVariable) pulumi.StringOutput { return v.Value }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RepositoryActionVariableInput)(nil)).Elem(), &RepositoryActionVariable{})
	pulumi.RegisterOutputType(RepositoryActionVariableOutput{})
}
