// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package forgejopulumiprovider

import (
	"context"
	"reflect"

	"errors"
	"forgejo.siron.casa/sironheart/forgejo-pulumi-provider/sdk/go/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A Forgejo Actions secret for a repository.
type RepositoryActionSecret struct {
	pulumi.CustomResourceState

	Created pulumi.StringOutput `pulumi:"created"`
	// Actions secret name.
	Name pulumi.StringOutput `pulumi:"name"`
	// Repository owner.
	Owner pulumi.StringOutput `pulumi:"owner"`
	// Repository name.
	Repository pulumi.StringOutput `pulumi:"repository"`
	// Actions secret value.
	Value pulumi.StringOutput `pulumi:"value"`
}

// NewRepositoryActionSecret registers a new resource with the given unique name, arguments, and options.
func NewRepositoryActionSecret(ctx *pulumi.Context,
	name string, args *RepositoryActionSecretArgs, opts ...pulumi.ResourceOption) (*RepositoryActionSecret, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.Owner == nil {
		return nil, errors.New("invalid value for required argument 'Owner'")
	}
	if args.Repository == nil {
		return nil, errors.New("invalid value for required argument 'Repository'")
	}
	if args.Value == nil {
		return nil, errors.New("invalid value for required argument 'Value'")
	}
	if args.Value != nil {
		args.Value = pulumi.ToSecret(args.Value).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"value",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource RepositoryActionSecret
	err := ctx.RegisterResource("forgejo:index:RepositoryActionSecret", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRepositoryActionSecret gets an existing RepositoryActionSecret resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRepositoryActionSecret(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RepositoryActionSecretState, opts ...pulumi.ResourceOption) (*RepositoryActionSecret, error) {
	var resource RepositoryActionSecret
	err := ctx.ReadResource("forgejo:index:RepositoryActionSecret", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering RepositoryActionSecret resources.
type repositoryActionSecretState struct {
}

type RepositoryActionSecretState struct {
}

func (RepositoryActionSecretState) ElementType() reflect.Type {
	return reflect.TypeOf((*repositoryActionSecretState)(nil)).Elem()
}

type repositoryActionSecretArgs struct {
	// Actions secret name.
	Name string `pulumi:"name"`
	// Repository owner.
	Owner string `pulumi:"owner"`
	// Repository name.
	Repository string `pulumi:"repository"`
	// Actions secret value.
	Value string `pulumi:"value"`
}

// The set of arguments for constructing a RepositoryActionSecret resource.
type RepositoryActionSecretArgs struct {
	// Actions secret name.
	Name pulumi.StringInput
	// Repository owner.
	Owner pulumi.StringInput
	// Repository name.
	Repository pulumi.StringInput
	// Actions secret value.
	Value pulumi.StringInput
}

func (RepositoryActionSecretArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*repositoryActionSecretArgs)(nil)).Elem()
}

type RepositoryActionSecretInput interface {
	pulumi.Input

	ToRepositoryActionSecretOutput() RepositoryActionSecretOutput
	ToRepositoryActionSecretOutputWithContext(ctx context.Context) RepositoryActionSecretOutput
}

func (*RepositoryActionSecret) ElementType() reflect.Type {
	return reflect.TypeOf((**RepositoryActionSecret)(nil)).Elem()
}

func (i *RepositoryActionSecret) ToRepositoryActionSecretOutput() RepositoryActionSecretOutput {
	return i.ToRepositoryActionSecretOutputWithContext(context.Background())
}

func (i *RepositoryActionSecret) ToRepositoryActionSecretOutputWithContext(ctx context.Context) RepositoryActionSecretOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RepositoryActionSecretOutput)
}

type RepositoryActionSecretOutput struct{ *pulumi.OutputState }

func (RepositoryActionSecretOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RepositoryActionSecret)(nil)).Elem()
}

func (o RepositoryActionSecretOutput) ToRepositoryActionSecretOutput() RepositoryActionSecretOutput {
	return o
}

func (o RepositoryActionSecretOutput) ToRepositoryActionSecretOutputWithContext(ctx context.Context) RepositoryActionSecretOutput {
	return o
}

func (o RepositoryActionSecretOutput) Created() pulumi.StringOutput {
	return o.ApplyT(func(v *RepositoryActionSecret) pulumi.StringOutput { return v.Created }).(pulumi.StringOutput)
}

// Actions secret name.
func (o RepositoryActionSecretOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *RepositoryActionSecret) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Repository owner.
func (o RepositoryActionSecretOutput) Owner() pulumi.StringOutput {
	return o.ApplyT(func(v *RepositoryActionSecret) pulumi.StringOutput { return v.Owner }).(pulumi.StringOutput)
}

// Repository name.
func (o RepositoryActionSecretOutput) Repository() pulumi.StringOutput {
	return o.ApplyT(func(v *RepositoryActionSecret) pulumi.StringOutput { return v.Repository }).(pulumi.StringOutput)
}

// Actions secret value.
func (o RepositoryActionSecretOutput) Value() pulumi.StringOutput {
	return o.ApplyT(func(v *RepositoryActionSecret) pulumi.StringOutput { return v.Value }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RepositoryActionSecretInput)(nil)).Elem(), &RepositoryActionSecret{})
	pulumi.RegisterOutputType(RepositoryActionSecretOutput{})
}
