// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package forgejopulumiprovider

import (
	"context"
	"reflect"

	"errors"
	"forgejo.siron.casa/sironheart/forgejo-pulumi-provider/sdk/go/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A Forgejo repository push mirror, optionally limited to matching branches.
type RepositoryPushMirror struct {
	pulumi.CustomResourceState

	// Optional branch filter for the push mirror. Leave empty to mirror all branches.
	BranchFilter pulumi.StringPtrOutput `pulumi:"branchFilter"`
	Created      pulumi.StringOutput    `pulumi:"created"`
	// Mirror sync interval, for example 8h30m0s. Leave empty to use Forgejo's default.
	Interval   pulumi.StringPtrOutput `pulumi:"interval"`
	LastError  pulumi.StringOutput    `pulumi:"lastError"`
	LastUpdate pulumi.StringOutput    `pulumi:"lastUpdate"`
	// Repository owner.
	Owner     pulumi.StringOutput `pulumi:"owner"`
	PublicKey pulumi.StringOutput `pulumi:"publicKey"`
	// Target remote URL for the push mirror.
	RemoteAddress pulumi.StringOutput `pulumi:"remoteAddress"`
	RemoteName    pulumi.StringOutput `pulumi:"remoteName"`
	// Password or token for authenticating to the remote.
	RemotePassword pulumi.StringPtrOutput `pulumi:"remotePassword"`
	// Username for authenticating to the remote.
	RemoteUsername pulumi.StringPtrOutput `pulumi:"remoteUsername"`
	// Repository name.
	Repository pulumi.StringOutput `pulumi:"repository"`
	// Whether pushes to this repository trigger the mirror.
	SyncOnCommit pulumi.BoolPtrOutput `pulumi:"syncOnCommit"`
	// Whether Forgejo should use an SSH key for the push mirror remote.
	UseSsh pulumi.BoolPtrOutput `pulumi:"useSsh"`
}

// NewRepositoryPushMirror registers a new resource with the given unique name, arguments, and options.
func NewRepositoryPushMirror(ctx *pulumi.Context,
	name string, args *RepositoryPushMirrorArgs, opts ...pulumi.ResourceOption) (*RepositoryPushMirror, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Owner == nil {
		return nil, errors.New("invalid value for required argument 'Owner'")
	}
	if args.RemoteAddress == nil {
		return nil, errors.New("invalid value for required argument 'RemoteAddress'")
	}
	if args.Repository == nil {
		return nil, errors.New("invalid value for required argument 'Repository'")
	}
	if args.RemotePassword != nil {
		args.RemotePassword = pulumi.ToSecret(args.RemotePassword).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"remotePassword",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource RepositoryPushMirror
	err := ctx.RegisterResource("forgejo:index:RepositoryPushMirror", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRepositoryPushMirror gets an existing RepositoryPushMirror resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRepositoryPushMirror(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RepositoryPushMirrorState, opts ...pulumi.ResourceOption) (*RepositoryPushMirror, error) {
	var resource RepositoryPushMirror
	err := ctx.ReadResource("forgejo:index:RepositoryPushMirror", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering RepositoryPushMirror resources.
type repositoryPushMirrorState struct {
}

type RepositoryPushMirrorState struct {
}

func (RepositoryPushMirrorState) ElementType() reflect.Type {
	return reflect.TypeOf((*repositoryPushMirrorState)(nil)).Elem()
}

type repositoryPushMirrorArgs struct {
	// Optional branch filter for the push mirror. Leave empty to mirror all branches.
	BranchFilter *string `pulumi:"branchFilter"`
	// Mirror sync interval, for example 8h30m0s. Leave empty to use Forgejo's default.
	Interval *string `pulumi:"interval"`
	// Repository owner.
	Owner string `pulumi:"owner"`
	// Target remote URL for the push mirror.
	RemoteAddress string `pulumi:"remoteAddress"`
	// Password or token for authenticating to the remote.
	RemotePassword *string `pulumi:"remotePassword"`
	// Username for authenticating to the remote.
	RemoteUsername *string `pulumi:"remoteUsername"`
	// Repository name.
	Repository string `pulumi:"repository"`
	// Whether pushes to this repository trigger the mirror.
	SyncOnCommit *bool `pulumi:"syncOnCommit"`
	// Whether Forgejo should use an SSH key for the push mirror remote.
	UseSsh *bool `pulumi:"useSsh"`
}

// The set of arguments for constructing a RepositoryPushMirror resource.
type RepositoryPushMirrorArgs struct {
	// Optional branch filter for the push mirror. Leave empty to mirror all branches.
	BranchFilter pulumi.StringPtrInput
	// Mirror sync interval, for example 8h30m0s. Leave empty to use Forgejo's default.
	Interval pulumi.StringPtrInput
	// Repository owner.
	Owner pulumi.StringInput
	// Target remote URL for the push mirror.
	RemoteAddress pulumi.StringInput
	// Password or token for authenticating to the remote.
	RemotePassword pulumi.StringPtrInput
	// Username for authenticating to the remote.
	RemoteUsername pulumi.StringPtrInput
	// Repository name.
	Repository pulumi.StringInput
	// Whether pushes to this repository trigger the mirror.
	SyncOnCommit pulumi.BoolPtrInput
	// Whether Forgejo should use an SSH key for the push mirror remote.
	UseSsh pulumi.BoolPtrInput
}

func (RepositoryPushMirrorArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*repositoryPushMirrorArgs)(nil)).Elem()
}

type RepositoryPushMirrorInput interface {
	pulumi.Input

	ToRepositoryPushMirrorOutput() RepositoryPushMirrorOutput
	ToRepositoryPushMirrorOutputWithContext(ctx context.Context) RepositoryPushMirrorOutput
}

func (*RepositoryPushMirror) ElementType() reflect.Type {
	return reflect.TypeOf((**RepositoryPushMirror)(nil)).Elem()
}

func (i *RepositoryPushMirror) ToRepositoryPushMirrorOutput() RepositoryPushMirrorOutput {
	return i.ToRepositoryPushMirrorOutputWithContext(context.Background())
}

func (i *RepositoryPushMirror) ToRepositoryPushMirrorOutputWithContext(ctx context.Context) RepositoryPushMirrorOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RepositoryPushMirrorOutput)
}

type RepositoryPushMirrorOutput struct{ *pulumi.OutputState }

func (RepositoryPushMirrorOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RepositoryPushMirror)(nil)).Elem()
}

func (o RepositoryPushMirrorOutput) ToRepositoryPushMirrorOutput() RepositoryPushMirrorOutput {
	return o
}

func (o RepositoryPushMirrorOutput) ToRepositoryPushMirrorOutputWithContext(ctx context.Context) RepositoryPushMirrorOutput {
	return o
}

// Optional branch filter for the push mirror. Leave empty to mirror all branches.
func (o RepositoryPushMirrorOutput) BranchFilter() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *RepositoryPushMirror) pulumi.StringPtrOutput { return v.BranchFilter }).(pulumi.StringPtrOutput)
}

func (o RepositoryPushMirrorOutput) Created() pulumi.StringOutput {
	return o.ApplyT(func(v *RepositoryPushMirror) pulumi.StringOutput { return v.Created }).(pulumi.StringOutput)
}

// Mirror sync interval, for example 8h30m0s. Leave empty to use Forgejo's default.
func (o RepositoryPushMirrorOutput) Interval() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *RepositoryPushMirror) pulumi.StringPtrOutput { return v.Interval }).(pulumi.StringPtrOutput)
}

func (o RepositoryPushMirrorOutput) LastError() pulumi.StringOutput {
	return o.ApplyT(func(v *RepositoryPushMirror) pulumi.StringOutput { return v.LastError }).(pulumi.StringOutput)
}

func (o RepositoryPushMirrorOutput) LastUpdate() pulumi.StringOutput {
	return o.ApplyT(func(v *RepositoryPushMirror) pulumi.StringOutput { return v.LastUpdate }).(pulumi.StringOutput)
}

// Repository owner.
func (o RepositoryPushMirrorOutput) Owner() pulumi.StringOutput {
	return o.ApplyT(func(v *RepositoryPushMirror) pulumi.StringOutput { return v.Owner }).(pulumi.StringOutput)
}

func (o RepositoryPushMirrorOutput) PublicKey() pulumi.StringOutput {
	return o.ApplyT(func(v *RepositoryPushMirror) pulumi.StringOutput { return v.PublicKey }).(pulumi.StringOutput)
}

// Target remote URL for the push mirror.
func (o RepositoryPushMirrorOutput) RemoteAddress() pulumi.StringOutput {
	return o.ApplyT(func(v *RepositoryPushMirror) pulumi.StringOutput { return v.RemoteAddress }).(pulumi.StringOutput)
}

func (o RepositoryPushMirrorOutput) RemoteName() pulumi.StringOutput {
	return o.ApplyT(func(v *RepositoryPushMirror) pulumi.StringOutput { return v.RemoteName }).(pulumi.StringOutput)
}

// Password or token for authenticating to the remote.
func (o RepositoryPushMirrorOutput) RemotePassword() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *RepositoryPushMirror) pulumi.StringPtrOutput { return v.RemotePassword }).(pulumi.StringPtrOutput)
}

// Username for authenticating to the remote.
func (o RepositoryPushMirrorOutput) RemoteUsername() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *RepositoryPushMirror) pulumi.StringPtrOutput { return v.RemoteUsername }).(pulumi.StringPtrOutput)
}

// Repository name.
func (o RepositoryPushMirrorOutput) Repository() pulumi.StringOutput {
	return o.ApplyT(func(v *RepositoryPushMirror) pulumi.StringOutput { return v.Repository }).(pulumi.StringOutput)
}

// Whether pushes to this repository trigger the mirror.
func (o RepositoryPushMirrorOutput) SyncOnCommit() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *RepositoryPushMirror) pulumi.BoolPtrOutput { return v.SyncOnCommit }).(pulumi.BoolPtrOutput)
}

// Whether Forgejo should use an SSH key for the push mirror remote.
func (o RepositoryPushMirrorOutput) UseSsh() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *RepositoryPushMirror) pulumi.BoolPtrOutput { return v.UseSsh }).(pulumi.BoolPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RepositoryPushMirrorInput)(nil)).Elem(), &RepositoryPushMirror{})
	pulumi.RegisterOutputType(RepositoryPushMirrorOutput{})
}
