// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package forgejopulumiprovider

import (
	"context"
	"reflect"

	"errors"
	"forgejo.siron.casa/sironheart/forgejo-pulumi-provider/sdk/go/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A Forgejo repository.
type Repository struct {
	pulumi.CustomResourceState

	CloneUrl pulumi.StringOutput `pulumi:"cloneUrl"`
	// Default branch name. Leave empty to use Forgejo's default.
	DefaultBranch pulumi.StringPtrOutput `pulumi:"defaultBranch"`
	// Repository description.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	FullName    pulumi.StringOutput    `pulumi:"fullName"`
	HtmlUrl     pulumi.StringOutput    `pulumi:"htmlUrl"`
	// Repository name.
	Name pulumi.StringOutput `pulumi:"name"`
	// Repository owner. Leave empty to create a repository for the authenticated user; set an organization name to create an organization repository.
	Owner pulumi.StringPtrOutput `pulumi:"owner"`
	// Whether the repository is private.
	Private pulumi.BoolPtrOutput `pulumi:"private"`
	// Optional repository unit, wiki, and issue tracker settings to manage with this repository.
	Settings RepositorySettingsConfigPtrOutput `pulumi:"settings"`
	SshUrl   pulumi.StringOutput               `pulumi:"sshUrl"`
	// Whether the repository can be used as a template.
	Template pulumi.BoolPtrOutput `pulumi:"template"`
	// Repository website URL.
	Website pulumi.StringPtrOutput `pulumi:"website"`
}

// NewRepository registers a new resource with the given unique name, arguments, and options.
func NewRepository(ctx *pulumi.Context,
	name string, args *RepositoryArgs, opts ...pulumi.ResourceOption) (*Repository, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Repository
	err := ctx.RegisterResource("forgejo:index:Repository", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRepository gets an existing Repository resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRepository(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RepositoryState, opts ...pulumi.ResourceOption) (*Repository, error) {
	var resource Repository
	err := ctx.ReadResource("forgejo:index:Repository", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Repository resources.
type repositoryState struct {
}

type RepositoryState struct {
}

func (RepositoryState) ElementType() reflect.Type {
	return reflect.TypeOf((*repositoryState)(nil)).Elem()
}

type repositoryArgs struct {
	// Default branch name. Leave empty to use Forgejo's default.
	DefaultBranch *string `pulumi:"defaultBranch"`
	// Repository description.
	Description *string `pulumi:"description"`
	// Repository name.
	Name string `pulumi:"name"`
	// Repository owner. Leave empty to create a repository for the authenticated user; set an organization name to create an organization repository.
	Owner *string `pulumi:"owner"`
	// Whether the repository is private.
	Private *bool `pulumi:"private"`
	// Optional repository unit, wiki, and issue tracker settings to manage with this repository.
	Settings *RepositorySettingsConfig `pulumi:"settings"`
	// Whether the repository can be used as a template.
	Template *bool `pulumi:"template"`
	// Repository website URL.
	Website *string `pulumi:"website"`
}

// The set of arguments for constructing a Repository resource.
type RepositoryArgs struct {
	// Default branch name. Leave empty to use Forgejo's default.
	DefaultBranch pulumi.StringPtrInput
	// Repository description.
	Description pulumi.StringPtrInput
	// Repository name.
	Name pulumi.StringInput
	// Repository owner. Leave empty to create a repository for the authenticated user; set an organization name to create an organization repository.
	Owner pulumi.StringPtrInput
	// Whether the repository is private.
	Private pulumi.BoolPtrInput
	// Optional repository unit, wiki, and issue tracker settings to manage with this repository.
	Settings RepositorySettingsConfigPtrInput
	// Whether the repository can be used as a template.
	Template pulumi.BoolPtrInput
	// Repository website URL.
	Website pulumi.StringPtrInput
}

func (RepositoryArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*repositoryArgs)(nil)).Elem()
}

type RepositoryInput interface {
	pulumi.Input

	ToRepositoryOutput() RepositoryOutput
	ToRepositoryOutputWithContext(ctx context.Context) RepositoryOutput
}

func (*Repository) ElementType() reflect.Type {
	return reflect.TypeOf((**Repository)(nil)).Elem()
}

func (i *Repository) ToRepositoryOutput() RepositoryOutput {
	return i.ToRepositoryOutputWithContext(context.Background())
}

func (i *Repository) ToRepositoryOutputWithContext(ctx context.Context) RepositoryOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RepositoryOutput)
}

type RepositoryOutput struct{ *pulumi.OutputState }

func (RepositoryOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Repository)(nil)).Elem()
}

func (o RepositoryOutput) ToRepositoryOutput() RepositoryOutput {
	return o
}

func (o RepositoryOutput) ToRepositoryOutputWithContext(ctx context.Context) RepositoryOutput {
	return o
}

func (o RepositoryOutput) CloneUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *Repository) pulumi.StringOutput { return v.CloneUrl }).(pulumi.StringOutput)
}

// Default branch name. Leave empty to use Forgejo's default.
func (o RepositoryOutput) DefaultBranch() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Repository) pulumi.StringPtrOutput { return v.DefaultBranch }).(pulumi.StringPtrOutput)
}

// Repository description.
func (o RepositoryOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Repository) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

func (o RepositoryOutput) FullName() pulumi.StringOutput {
	return o.ApplyT(func(v *Repository) pulumi.StringOutput { return v.FullName }).(pulumi.StringOutput)
}

func (o RepositoryOutput) HtmlUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *Repository) pulumi.StringOutput { return v.HtmlUrl }).(pulumi.StringOutput)
}

// Repository name.
func (o RepositoryOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Repository) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Repository owner. Leave empty to create a repository for the authenticated user; set an organization name to create an organization repository.
func (o RepositoryOutput) Owner() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Repository) pulumi.StringPtrOutput { return v.Owner }).(pulumi.StringPtrOutput)
}

// Whether the repository is private.
func (o RepositoryOutput) Private() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Repository) pulumi.BoolPtrOutput { return v.Private }).(pulumi.BoolPtrOutput)
}

// Optional repository unit, wiki, and issue tracker settings to manage with this repository.
func (o RepositoryOutput) Settings() RepositorySettingsConfigPtrOutput {
	return o.ApplyT(func(v *Repository) RepositorySettingsConfigPtrOutput { return v.Settings }).(RepositorySettingsConfigPtrOutput)
}

func (o RepositoryOutput) SshUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *Repository) pulumi.StringOutput { return v.SshUrl }).(pulumi.StringOutput)
}

// Whether the repository can be used as a template.
func (o RepositoryOutput) Template() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Repository) pulumi.BoolPtrOutput { return v.Template }).(pulumi.BoolPtrOutput)
}

// Repository website URL.
func (o RepositoryOutput) Website() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Repository) pulumi.StringPtrOutput { return v.Website }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RepositoryInput)(nil)).Elem(), &Repository{})
	pulumi.RegisterOutputType(RepositoryOutput{})
}
