// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package casa.siron.forgejo.forgejo.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetCurrentUserResult {
    private String email;
    private String fullName;
    private Boolean isAdmin;
    private String login;
    private Integer userId;

    private GetCurrentUserResult() {}
    public String email() {
        return this.email;
    }
    public String fullName() {
        return this.fullName;
    }
    public Boolean isAdmin() {
        return this.isAdmin;
    }
    public String login() {
        return this.login;
    }
    public Integer userId() {
        return this.userId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetCurrentUserResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String email;
        private String fullName;
        private Boolean isAdmin;
        private String login;
        private Integer userId;
        public Builder() {}
        public Builder(GetCurrentUserResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.email = defaults.email;
    	      this.fullName = defaults.fullName;
    	      this.isAdmin = defaults.isAdmin;
    	      this.login = defaults.login;
    	      this.userId = defaults.userId;
        }

        @CustomType.Setter
        public Builder email(String email) {
            if (email == null) {
              throw new MissingRequiredPropertyException("GetCurrentUserResult", "email");
            }
            this.email = email;
            return this;
        }
        @CustomType.Setter
        public Builder fullName(String fullName) {
            if (fullName == null) {
              throw new MissingRequiredPropertyException("GetCurrentUserResult", "fullName");
            }
            this.fullName = fullName;
            return this;
        }
        @CustomType.Setter
        public Builder isAdmin(Boolean isAdmin) {
            if (isAdmin == null) {
              throw new MissingRequiredPropertyException("GetCurrentUserResult", "isAdmin");
            }
            this.isAdmin = isAdmin;
            return this;
        }
        @CustomType.Setter
        public Builder login(String login) {
            if (login == null) {
              throw new MissingRequiredPropertyException("GetCurrentUserResult", "login");
            }
            this.login = login;
            return this;
        }
        @CustomType.Setter
        public Builder userId(Integer userId) {
            if (userId == null) {
              throw new MissingRequiredPropertyException("GetCurrentUserResult", "userId");
            }
            this.userId = userId;
            return this;
        }
        public GetCurrentUserResult build() {
            final var _resultValue = new GetCurrentUserResult();
            _resultValue.email = email;
            _resultValue.fullName = fullName;
            _resultValue.isAdmin = isAdmin;
            _resultValue.login = login;
            _resultValue.userId = userId;
            return _resultValue;
        }
    }
}
