// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package casa.siron.forgejo.forgejo.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class RepositorySettingsConfig {
    /**
     * @return Whether the actions unit is enabled. Leave unset to avoid managing it.
     * 
     */
    private @Nullable Boolean actions;
    /**
     * @return External issue tracker URL format. Forgejo supports placeholders such as {user}, {repo}, and {index}.
     * 
     */
    private @Nullable String externalTrackerFormat;
    /**
     * @return External issue tracker regular expression pattern.
     * 
     */
    private @Nullable String externalTrackerRegexPattern;
    /**
     * @return External issue tracker number style, for example numeric or alphanumeric.
     * 
     */
    private @Nullable String externalTrackerStyle;
    /**
     * @return External issue tracker URL. Setting this also enables issues unless issues is explicitly set.
     * 
     */
    private @Nullable String externalTrackerUrl;
    /**
     * @return External wiki URL. Setting this also enables the wiki unless wiki is explicitly set.
     * 
     */
    private @Nullable String externalWikiUrl;
    /**
     * @return Whether the wiki is globally editable.
     * 
     */
    private @Nullable Boolean globallyEditableWiki;
    /**
     * @return Whether only contributors may track time in the internal issue tracker.
     * 
     */
    private @Nullable Boolean internalTrackerAllowOnlyContributorsToTrackTime;
    /**
     * @return Whether issue dependencies are enabled in the internal issue tracker.
     * 
     */
    private @Nullable Boolean internalTrackerEnableIssueDependencies;
    /**
     * @return Whether the internal issue tracker has time tracking enabled.
     * 
     */
    private @Nullable Boolean internalTrackerEnableTimeTracker;
    /**
     * @return Whether the issue tracker unit is enabled. Leave unset to avoid managing it.
     * 
     */
    private @Nullable Boolean issues;
    /**
     * @return Whether the packages unit is enabled. Leave unset to avoid managing it.
     * 
     */
    private @Nullable Boolean packages;
    /**
     * @return Whether the projects unit is enabled. Leave unset to avoid managing it.
     * 
     */
    private @Nullable Boolean projects;
    /**
     * @return Whether the pull request unit is enabled. Leave unset to avoid managing it.
     * 
     */
    private @Nullable Boolean pullRequests;
    /**
     * @return Whether the releases unit is enabled. Leave unset to avoid managing it.
     * 
     */
    private @Nullable Boolean releases;
    /**
     * @return Whether the wiki unit is enabled. Leave unset to avoid managing it.
     * 
     */
    private @Nullable Boolean wiki;
    /**
     * @return Branch used for the repository wiki.
     * 
     */
    private @Nullable String wikiBranch;

    private RepositorySettingsConfig() {}
    /**
     * @return Whether the actions unit is enabled. Leave unset to avoid managing it.
     * 
     */
    public Optional<Boolean> actions() {
        return Optional.ofNullable(this.actions);
    }
    /**
     * @return External issue tracker URL format. Forgejo supports placeholders such as {user}, {repo}, and {index}.
     * 
     */
    public Optional<String> externalTrackerFormat() {
        return Optional.ofNullable(this.externalTrackerFormat);
    }
    /**
     * @return External issue tracker regular expression pattern.
     * 
     */
    public Optional<String> externalTrackerRegexPattern() {
        return Optional.ofNullable(this.externalTrackerRegexPattern);
    }
    /**
     * @return External issue tracker number style, for example numeric or alphanumeric.
     * 
     */
    public Optional<String> externalTrackerStyle() {
        return Optional.ofNullable(this.externalTrackerStyle);
    }
    /**
     * @return External issue tracker URL. Setting this also enables issues unless issues is explicitly set.
     * 
     */
    public Optional<String> externalTrackerUrl() {
        return Optional.ofNullable(this.externalTrackerUrl);
    }
    /**
     * @return External wiki URL. Setting this also enables the wiki unless wiki is explicitly set.
     * 
     */
    public Optional<String> externalWikiUrl() {
        return Optional.ofNullable(this.externalWikiUrl);
    }
    /**
     * @return Whether the wiki is globally editable.
     * 
     */
    public Optional<Boolean> globallyEditableWiki() {
        return Optional.ofNullable(this.globallyEditableWiki);
    }
    /**
     * @return Whether only contributors may track time in the internal issue tracker.
     * 
     */
    public Optional<Boolean> internalTrackerAllowOnlyContributorsToTrackTime() {
        return Optional.ofNullable(this.internalTrackerAllowOnlyContributorsToTrackTime);
    }
    /**
     * @return Whether issue dependencies are enabled in the internal issue tracker.
     * 
     */
    public Optional<Boolean> internalTrackerEnableIssueDependencies() {
        return Optional.ofNullable(this.internalTrackerEnableIssueDependencies);
    }
    /**
     * @return Whether the internal issue tracker has time tracking enabled.
     * 
     */
    public Optional<Boolean> internalTrackerEnableTimeTracker() {
        return Optional.ofNullable(this.internalTrackerEnableTimeTracker);
    }
    /**
     * @return Whether the issue tracker unit is enabled. Leave unset to avoid managing it.
     * 
     */
    public Optional<Boolean> issues() {
        return Optional.ofNullable(this.issues);
    }
    /**
     * @return Whether the packages unit is enabled. Leave unset to avoid managing it.
     * 
     */
    public Optional<Boolean> packages() {
        return Optional.ofNullable(this.packages);
    }
    /**
     * @return Whether the projects unit is enabled. Leave unset to avoid managing it.
     * 
     */
    public Optional<Boolean> projects() {
        return Optional.ofNullable(this.projects);
    }
    /**
     * @return Whether the pull request unit is enabled. Leave unset to avoid managing it.
     * 
     */
    public Optional<Boolean> pullRequests() {
        return Optional.ofNullable(this.pullRequests);
    }
    /**
     * @return Whether the releases unit is enabled. Leave unset to avoid managing it.
     * 
     */
    public Optional<Boolean> releases() {
        return Optional.ofNullable(this.releases);
    }
    /**
     * @return Whether the wiki unit is enabled. Leave unset to avoid managing it.
     * 
     */
    public Optional<Boolean> wiki() {
        return Optional.ofNullable(this.wiki);
    }
    /**
     * @return Branch used for the repository wiki.
     * 
     */
    public Optional<String> wikiBranch() {
        return Optional.ofNullable(this.wikiBranch);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(RepositorySettingsConfig defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean actions;
        private @Nullable String externalTrackerFormat;
        private @Nullable String externalTrackerRegexPattern;
        private @Nullable String externalTrackerStyle;
        private @Nullable String externalTrackerUrl;
        private @Nullable String externalWikiUrl;
        private @Nullable Boolean globallyEditableWiki;
        private @Nullable Boolean internalTrackerAllowOnlyContributorsToTrackTime;
        private @Nullable Boolean internalTrackerEnableIssueDependencies;
        private @Nullable Boolean internalTrackerEnableTimeTracker;
        private @Nullable Boolean issues;
        private @Nullable Boolean packages;
        private @Nullable Boolean projects;
        private @Nullable Boolean pullRequests;
        private @Nullable Boolean releases;
        private @Nullable Boolean wiki;
        private @Nullable String wikiBranch;
        public Builder() {}
        public Builder(RepositorySettingsConfig defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.actions = defaults.actions;
    	      this.externalTrackerFormat = defaults.externalTrackerFormat;
    	      this.externalTrackerRegexPattern = defaults.externalTrackerRegexPattern;
    	      this.externalTrackerStyle = defaults.externalTrackerStyle;
    	      this.externalTrackerUrl = defaults.externalTrackerUrl;
    	      this.externalWikiUrl = defaults.externalWikiUrl;
    	      this.globallyEditableWiki = defaults.globallyEditableWiki;
    	      this.internalTrackerAllowOnlyContributorsToTrackTime = defaults.internalTrackerAllowOnlyContributorsToTrackTime;
    	      this.internalTrackerEnableIssueDependencies = defaults.internalTrackerEnableIssueDependencies;
    	      this.internalTrackerEnableTimeTracker = defaults.internalTrackerEnableTimeTracker;
    	      this.issues = defaults.issues;
    	      this.packages = defaults.packages;
    	      this.projects = defaults.projects;
    	      this.pullRequests = defaults.pullRequests;
    	      this.releases = defaults.releases;
    	      this.wiki = defaults.wiki;
    	      this.wikiBranch = defaults.wikiBranch;
        }

        @CustomType.Setter
        public Builder actions(@Nullable Boolean actions) {

            this.actions = actions;
            return this;
        }
        @CustomType.Setter
        public Builder externalTrackerFormat(@Nullable String externalTrackerFormat) {

            this.externalTrackerFormat = externalTrackerFormat;
            return this;
        }
        @CustomType.Setter
        public Builder externalTrackerRegexPattern(@Nullable String externalTrackerRegexPattern) {

            this.externalTrackerRegexPattern = externalTrackerRegexPattern;
            return this;
        }
        @CustomType.Setter
        public Builder externalTrackerStyle(@Nullable String externalTrackerStyle) {

            this.externalTrackerStyle = externalTrackerStyle;
            return this;
        }
        @CustomType.Setter
        public Builder externalTrackerUrl(@Nullable String externalTrackerUrl) {

            this.externalTrackerUrl = externalTrackerUrl;
            return this;
        }
        @CustomType.Setter
        public Builder externalWikiUrl(@Nullable String externalWikiUrl) {

            this.externalWikiUrl = externalWikiUrl;
            return this;
        }
        @CustomType.Setter
        public Builder globallyEditableWiki(@Nullable Boolean globallyEditableWiki) {

            this.globallyEditableWiki = globallyEditableWiki;
            return this;
        }
        @CustomType.Setter
        public Builder internalTrackerAllowOnlyContributorsToTrackTime(@Nullable Boolean internalTrackerAllowOnlyContributorsToTrackTime) {

            this.internalTrackerAllowOnlyContributorsToTrackTime = internalTrackerAllowOnlyContributorsToTrackTime;
            return this;
        }
        @CustomType.Setter
        public Builder internalTrackerEnableIssueDependencies(@Nullable Boolean internalTrackerEnableIssueDependencies) {

            this.internalTrackerEnableIssueDependencies = internalTrackerEnableIssueDependencies;
            return this;
        }
        @CustomType.Setter
        public Builder internalTrackerEnableTimeTracker(@Nullable Boolean internalTrackerEnableTimeTracker) {

            this.internalTrackerEnableTimeTracker = internalTrackerEnableTimeTracker;
            return this;
        }
        @CustomType.Setter
        public Builder issues(@Nullable Boolean issues) {

            this.issues = issues;
            return this;
        }
        @CustomType.Setter
        public Builder packages(@Nullable Boolean packages) {

            this.packages = packages;
            return this;
        }
        @CustomType.Setter
        public Builder projects(@Nullable Boolean projects) {

            this.projects = projects;
            return this;
        }
        @CustomType.Setter
        public Builder pullRequests(@Nullable Boolean pullRequests) {

            this.pullRequests = pullRequests;
            return this;
        }
        @CustomType.Setter
        public Builder releases(@Nullable Boolean releases) {

            this.releases = releases;
            return this;
        }
        @CustomType.Setter
        public Builder wiki(@Nullable Boolean wiki) {

            this.wiki = wiki;
            return this;
        }
        @CustomType.Setter
        public Builder wikiBranch(@Nullable String wikiBranch) {

            this.wikiBranch = wikiBranch;
            return this;
        }
        public RepositorySettingsConfig build() {
            final var _resultValue = new RepositorySettingsConfig();
            _resultValue.actions = actions;
            _resultValue.externalTrackerFormat = externalTrackerFormat;
            _resultValue.externalTrackerRegexPattern = externalTrackerRegexPattern;
            _resultValue.externalTrackerStyle = externalTrackerStyle;
            _resultValue.externalTrackerUrl = externalTrackerUrl;
            _resultValue.externalWikiUrl = externalWikiUrl;
            _resultValue.globallyEditableWiki = globallyEditableWiki;
            _resultValue.internalTrackerAllowOnlyContributorsToTrackTime = internalTrackerAllowOnlyContributorsToTrackTime;
            _resultValue.internalTrackerEnableIssueDependencies = internalTrackerEnableIssueDependencies;
            _resultValue.internalTrackerEnableTimeTracker = internalTrackerEnableTimeTracker;
            _resultValue.issues = issues;
            _resultValue.packages = packages;
            _resultValue.projects = projects;
            _resultValue.pullRequests = pullRequests;
            _resultValue.releases = releases;
            _resultValue.wiki = wiki;
            _resultValue.wikiBranch = wikiBranch;
            return _resultValue;
        }
    }
}
