// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"forgejo.siron.casa/sironheart/forgejo-pulumi-provider/sdk/go/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Forgejo API token. Can also be set with FORGEJO_TOKEN.
func GetToken(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "forgejo:token")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "FORGEJO_TOKEN"); d != nil {
		value = d.(string)
	}
	return value
}

// Base URL of the Forgejo instance. Can also be set with FORGEJO_URL.
func GetUrl(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "forgejo:url")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "FORGEJO_URL"); d != nil {
		value = d.(string)
	}
	return value
}
