// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package casa.siron.pulumi.forgejo;

import casa.siron.pulumi.forgejo.OrganizationArgs;
import casa.siron.pulumi.forgejo.Utilities;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * A Forgejo organization.
 * 
 */
@ResourceType(type="forgejo:index:Organization")
public class Organization extends com.pulumi.resources.CustomResource {
    @Export(name="avatarUrl", refs={String.class}, tree="[0]")
    private Output<String> avatarUrl;

    public Output<String> avatarUrl() {
        return this.avatarUrl;
    }
    /**
     * Organization description.
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    /**
     * @return Organization description.
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * Organization display name.
     * 
     */
    @Export(name="fullName", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> fullName;

    /**
     * @return Organization display name.
     * 
     */
    public Output<Optional<String>> fullName() {
        return Codegen.optional(this.fullName);
    }
    /**
     * Organization location.
     * 
     */
    @Export(name="location", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> location;

    /**
     * @return Organization location.
     * 
     */
    public Output<Optional<String>> location() {
        return Codegen.optional(this.location);
    }
    /**
     * Organization username/slug.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return Organization username/slug.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Organization visibility, for example public, limited, or private. Leave empty to use Forgejo&#39;s default.
     * 
     */
    @Export(name="visibility", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> visibility;

    /**
     * @return Organization visibility, for example public, limited, or private. Leave empty to use Forgejo&#39;s default.
     * 
     */
    public Output<Optional<String>> visibility() {
        return Codegen.optional(this.visibility);
    }
    /**
     * Organization website URL.
     * 
     */
    @Export(name="website", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> website;

    /**
     * @return Organization website URL.
     * 
     */
    public Output<Optional<String>> website() {
        return Codegen.optional(this.website);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Organization(java.lang.String name) {
        this(name, OrganizationArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Organization(java.lang.String name, OrganizationArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Organization(java.lang.String name, OrganizationArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("forgejo:index:Organization", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Organization(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("forgejo:index:Organization", name, null, makeResourceOptions(options, id), false);
    }

    private static OrganizationArgs makeArgs(OrganizationArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? OrganizationArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("https://forgejo.siron.casa/sironheart/forgejo-pulumi-provider/releases/download/v${VERSION}")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Organization get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Organization(name, id, options);
    }
}
