// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface RepositorySettingsConfigArgs {
    /**
     * Whether the actions unit is enabled. Leave unset to avoid managing it.
     */
    actions?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the repository is archived. Leave unset to avoid managing it.
     */
    archived?: pulumi.Input<boolean | undefined>;
    /**
     * Whether Forgejo deletes pull request branches by default after merge. Setting this also enables pull requests unless pullRequests is explicitly set.
     */
    defaultDeleteBranchAfterMerge?: pulumi.Input<boolean | undefined>;
    /**
     * External issue tracker URL format. Forgejo supports placeholders such as {user}, {repo}, and {index}.
     */
    externalTrackerFormat?: pulumi.Input<string | undefined>;
    /**
     * External issue tracker regular expression pattern.
     */
    externalTrackerRegexPattern?: pulumi.Input<string | undefined>;
    /**
     * External issue tracker number style, for example numeric or alphanumeric.
     */
    externalTrackerStyle?: pulumi.Input<string | undefined>;
    /**
     * External issue tracker URL. Setting this also enables issues unless issues is explicitly set.
     */
    externalTrackerUrl?: pulumi.Input<string | undefined>;
    /**
     * External wiki URL. Setting this also enables the wiki unless wiki is explicitly set.
     */
    externalWikiUrl?: pulumi.Input<string | undefined>;
    /**
     * Whether the wiki is globally editable.
     */
    globallyEditableWiki?: pulumi.Input<boolean | undefined>;
    /**
     * Whether only contributors may track time in the internal issue tracker.
     */
    internalTrackerAllowOnlyContributorsToTrackTime?: pulumi.Input<boolean | undefined>;
    /**
     * Whether issue dependencies are enabled in the internal issue tracker.
     */
    internalTrackerEnableIssueDependencies?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the internal issue tracker has time tracking enabled.
     */
    internalTrackerEnableTimeTracker?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the issue tracker unit is enabled. Leave unset to avoid managing it.
     */
    issues?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the packages unit is enabled. Leave unset to avoid managing it.
     */
    packages?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the projects unit is enabled. Leave unset to avoid managing it.
     */
    projects?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the pull request unit is enabled. Leave unset to avoid managing it.
     */
    pullRequests?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the releases unit is enabled. Leave unset to avoid managing it.
     */
    releases?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the wiki unit is enabled. Leave unset to avoid managing it.
     */
    wiki?: pulumi.Input<boolean | undefined>;
    /**
     * Branch used for the repository wiki.
     */
    wikiBranch?: pulumi.Input<string | undefined>;
}
