# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .deploy_key import *
from .get_current_user import *
from .organization import *
from .organization_team import *
from .provider import *
from .public_key import *
from .repository import *
from .repository_action_variable import *
from .repository_tag_protection import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_forgejo.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_forgejo.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "forgejo",
  "mod": "index",
  "fqn": "pulumi_forgejo",
  "classes": {
   "forgejo:index:DeployKey": "DeployKey",
   "forgejo:index:Organization": "Organization",
   "forgejo:index:OrganizationTeam": "OrganizationTeam",
   "forgejo:index:PublicKey": "PublicKey",
   "forgejo:index:Repository": "Repository",
   "forgejo:index:RepositoryActionVariable": "RepositoryActionVariable",
   "forgejo:index:RepositoryTagProtection": "RepositoryTagProtection"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "forgejo",
  "token": "pulumi:providers:forgejo",
  "fqn": "pulumi_forgejo",
  "class": "Provider"
 }
]
"""
)
