// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package casa.siron.forgejo.forgejo;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class OrganizationActionVariableArgs extends com.pulumi.resources.ResourceArgs {

    public static final OrganizationActionVariableArgs Empty = new OrganizationActionVariableArgs();

    /**
     * Actions variable name.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return Actions variable name.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * Organization name.
     * 
     */
    @Import(name="organization", required=true)
    private Output<String> organization;

    /**
     * @return Organization name.
     * 
     */
    public Output<String> organization() {
        return this.organization;
    }

    /**
     * Actions variable value.
     * 
     */
    @Import(name="value", required=true)
    private Output<String> value;

    /**
     * @return Actions variable value.
     * 
     */
    public Output<String> value() {
        return this.value;
    }

    private OrganizationActionVariableArgs() {}

    private OrganizationActionVariableArgs(OrganizationActionVariableArgs $) {
        this.name = $.name;
        this.organization = $.organization;
        this.value = $.value;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(OrganizationActionVariableArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private OrganizationActionVariableArgs $;

        public Builder() {
            $ = new OrganizationActionVariableArgs();
        }

        public Builder(OrganizationActionVariableArgs defaults) {
            $ = new OrganizationActionVariableArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name Actions variable name.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Actions variable name.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param organization Organization name.
         * 
         * @return builder
         * 
         */
        public Builder organization(Output<String> organization) {
            $.organization = organization;
            return this;
        }

        /**
         * @param organization Organization name.
         * 
         * @return builder
         * 
         */
        public Builder organization(String organization) {
            return organization(Output.of(organization));
        }

        /**
         * @param value Actions variable value.
         * 
         * @return builder
         * 
         */
        public Builder value(Output<String> value) {
            $.value = value;
            return this;
        }

        /**
         * @param value Actions variable value.
         * 
         * @return builder
         * 
         */
        public Builder value(String value) {
            return value(Output.of(value));
        }

        public OrganizationActionVariableArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("OrganizationActionVariableArgs", "name");
            }
            if ($.organization == null) {
                throw new MissingRequiredPropertyException("OrganizationActionVariableArgs", "organization");
            }
            if ($.value == null) {
                throw new MissingRequiredPropertyException("OrganizationActionVariableArgs", "value");
            }
            return $;
        }
    }

}
