// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package casa.siron.forgejo.forgejo;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class OrganizationTeamMemberArgs extends com.pulumi.resources.ResourceArgs {

    public static final OrganizationTeamMemberArgs Empty = new OrganizationTeamMemberArgs();

    /**
     * Organization username/slug. Required when teamId is not set.
     * 
     */
    @Import(name="organization")
    private @Nullable Output<String> organization;

    /**
     * @return Organization username/slug. Required when teamId is not set.
     * 
     */
    public Optional<Output<String>> organization() {
        return Optional.ofNullable(this.organization);
    }

    /**
     * Team name. Required when teamId is not set.
     * 
     */
    @Import(name="team")
    private @Nullable Output<String> team;

    /**
     * @return Team name. Required when teamId is not set.
     * 
     */
    public Optional<Output<String>> team() {
        return Optional.ofNullable(this.team);
    }

    /**
     * Numeric Forgejo team ID. If omitted, organization and team are used to look up the team.
     * 
     */
    @Import(name="teamId")
    private @Nullable Output<Integer> teamId;

    /**
     * @return Numeric Forgejo team ID. If omitted, organization and team are used to look up the team.
     * 
     */
    public Optional<Output<Integer>> teamId() {
        return Optional.ofNullable(this.teamId);
    }

    /**
     * Username to add to the team.
     * 
     */
    @Import(name="username", required=true)
    private Output<String> username;

    /**
     * @return Username to add to the team.
     * 
     */
    public Output<String> username() {
        return this.username;
    }

    private OrganizationTeamMemberArgs() {}

    private OrganizationTeamMemberArgs(OrganizationTeamMemberArgs $) {
        this.organization = $.organization;
        this.team = $.team;
        this.teamId = $.teamId;
        this.username = $.username;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(OrganizationTeamMemberArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private OrganizationTeamMemberArgs $;

        public Builder() {
            $ = new OrganizationTeamMemberArgs();
        }

        public Builder(OrganizationTeamMemberArgs defaults) {
            $ = new OrganizationTeamMemberArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param organization Organization username/slug. Required when teamId is not set.
         * 
         * @return builder
         * 
         */
        public Builder organization(@Nullable Output<String> organization) {
            $.organization = organization;
            return this;
        }

        /**
         * @param organization Organization username/slug. Required when teamId is not set.
         * 
         * @return builder
         * 
         */
        public Builder organization(String organization) {
            return organization(Output.of(organization));
        }

        /**
         * @param team Team name. Required when teamId is not set.
         * 
         * @return builder
         * 
         */
        public Builder team(@Nullable Output<String> team) {
            $.team = team;
            return this;
        }

        /**
         * @param team Team name. Required when teamId is not set.
         * 
         * @return builder
         * 
         */
        public Builder team(String team) {
            return team(Output.of(team));
        }

        /**
         * @param teamId Numeric Forgejo team ID. If omitted, organization and team are used to look up the team.
         * 
         * @return builder
         * 
         */
        public Builder teamId(@Nullable Output<Integer> teamId) {
            $.teamId = teamId;
            return this;
        }

        /**
         * @param teamId Numeric Forgejo team ID. If omitted, organization and team are used to look up the team.
         * 
         * @return builder
         * 
         */
        public Builder teamId(Integer teamId) {
            return teamId(Output.of(teamId));
        }

        /**
         * @param username Username to add to the team.
         * 
         * @return builder
         * 
         */
        public Builder username(Output<String> username) {
            $.username = username;
            return this;
        }

        /**
         * @param username Username to add to the team.
         * 
         * @return builder
         * 
         */
        public Builder username(String username) {
            return username(Output.of(username));
        }

        public OrganizationTeamMemberArgs build() {
            if ($.username == null) {
                throw new MissingRequiredPropertyException("OrganizationTeamMemberArgs", "username");
            }
            return $;
        }
    }

}
