// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package casa.siron.forgejo.forgejo;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class ProviderArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProviderArgs Empty = new ProviderArgs();

    /**
     * Forgejo API token. Can also be set with FORGEJO_TOKEN.
     * 
     */
    @Import(name="token", required=true)
    private Output<String> token;

    /**
     * @return Forgejo API token. Can also be set with FORGEJO_TOKEN.
     * 
     */
    public Output<String> token() {
        return this.token;
    }

    /**
     * Base URL of the Forgejo instance. Can also be set with FORGEJO_URL.
     * 
     */
    @Import(name="url", required=true)
    private Output<String> url;

    /**
     * @return Base URL of the Forgejo instance. Can also be set with FORGEJO_URL.
     * 
     */
    public Output<String> url() {
        return this.url;
    }

    private ProviderArgs() {}

    private ProviderArgs(ProviderArgs $) {
        this.token = $.token;
        this.url = $.url;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProviderArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProviderArgs $;

        public Builder() {
            $ = new ProviderArgs();
        }

        public Builder(ProviderArgs defaults) {
            $ = new ProviderArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param token Forgejo API token. Can also be set with FORGEJO_TOKEN.
         * 
         * @return builder
         * 
         */
        public Builder token(Output<String> token) {
            $.token = token;
            return this;
        }

        /**
         * @param token Forgejo API token. Can also be set with FORGEJO_TOKEN.
         * 
         * @return builder
         * 
         */
        public Builder token(String token) {
            return token(Output.of(token));
        }

        /**
         * @param url Base URL of the Forgejo instance. Can also be set with FORGEJO_URL.
         * 
         * @return builder
         * 
         */
        public Builder url(Output<String> url) {
            $.url = url;
            return this;
        }

        /**
         * @param url Base URL of the Forgejo instance. Can also be set with FORGEJO_URL.
         * 
         * @return builder
         * 
         */
        public Builder url(String url) {
            return url(Output.of(url));
        }

        public ProviderArgs build() {
            $.token = Codegen.stringProp("token").secret().arg($.token).env("FORGEJO_TOKEN").require();
            $.url = Codegen.stringProp("url").output().arg($.url).env("FORGEJO_URL").require();
            return $;
        }
    }

}
