// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package casa.siron.forgejo.forgejo;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class RepositoryPushMirrorArgs extends com.pulumi.resources.ResourceArgs {

    public static final RepositoryPushMirrorArgs Empty = new RepositoryPushMirrorArgs();

    /**
     * Optional branch filter for the push mirror. Leave empty to mirror all branches.
     * 
     */
    @Import(name="branchFilter")
    private @Nullable Output<String> branchFilter;

    /**
     * @return Optional branch filter for the push mirror. Leave empty to mirror all branches.
     * 
     */
    public Optional<Output<String>> branchFilter() {
        return Optional.ofNullable(this.branchFilter);
    }

    /**
     * Mirror sync interval, for example 8h30m0s. Leave empty to use Forgejo&#39;s default.
     * 
     */
    @Import(name="interval")
    private @Nullable Output<String> interval;

    /**
     * @return Mirror sync interval, for example 8h30m0s. Leave empty to use Forgejo&#39;s default.
     * 
     */
    public Optional<Output<String>> interval() {
        return Optional.ofNullable(this.interval);
    }

    /**
     * Repository owner.
     * 
     */
    @Import(name="owner", required=true)
    private Output<String> owner;

    /**
     * @return Repository owner.
     * 
     */
    public Output<String> owner() {
        return this.owner;
    }

    /**
     * Target remote URL for the push mirror.
     * 
     */
    @Import(name="remoteAddress", required=true)
    private Output<String> remoteAddress;

    /**
     * @return Target remote URL for the push mirror.
     * 
     */
    public Output<String> remoteAddress() {
        return this.remoteAddress;
    }

    /**
     * Password or token for authenticating to the remote.
     * 
     */
    @Import(name="remotePassword")
    private @Nullable Output<String> remotePassword;

    /**
     * @return Password or token for authenticating to the remote.
     * 
     */
    public Optional<Output<String>> remotePassword() {
        return Optional.ofNullable(this.remotePassword);
    }

    /**
     * Username for authenticating to the remote.
     * 
     */
    @Import(name="remoteUsername")
    private @Nullable Output<String> remoteUsername;

    /**
     * @return Username for authenticating to the remote.
     * 
     */
    public Optional<Output<String>> remoteUsername() {
        return Optional.ofNullable(this.remoteUsername);
    }

    /**
     * Repository name.
     * 
     */
    @Import(name="repository", required=true)
    private Output<String> repository;

    /**
     * @return Repository name.
     * 
     */
    public Output<String> repository() {
        return this.repository;
    }

    /**
     * Whether pushes to this repository trigger the mirror.
     * 
     */
    @Import(name="syncOnCommit")
    private @Nullable Output<Boolean> syncOnCommit;

    /**
     * @return Whether pushes to this repository trigger the mirror.
     * 
     */
    public Optional<Output<Boolean>> syncOnCommit() {
        return Optional.ofNullable(this.syncOnCommit);
    }

    /**
     * Whether Forgejo should use an SSH key for the push mirror remote.
     * 
     */
    @Import(name="useSsh")
    private @Nullable Output<Boolean> useSsh;

    /**
     * @return Whether Forgejo should use an SSH key for the push mirror remote.
     * 
     */
    public Optional<Output<Boolean>> useSsh() {
        return Optional.ofNullable(this.useSsh);
    }

    private RepositoryPushMirrorArgs() {}

    private RepositoryPushMirrorArgs(RepositoryPushMirrorArgs $) {
        this.branchFilter = $.branchFilter;
        this.interval = $.interval;
        this.owner = $.owner;
        this.remoteAddress = $.remoteAddress;
        this.remotePassword = $.remotePassword;
        this.remoteUsername = $.remoteUsername;
        this.repository = $.repository;
        this.syncOnCommit = $.syncOnCommit;
        this.useSsh = $.useSsh;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RepositoryPushMirrorArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RepositoryPushMirrorArgs $;

        public Builder() {
            $ = new RepositoryPushMirrorArgs();
        }

        public Builder(RepositoryPushMirrorArgs defaults) {
            $ = new RepositoryPushMirrorArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param branchFilter Optional branch filter for the push mirror. Leave empty to mirror all branches.
         * 
         * @return builder
         * 
         */
        public Builder branchFilter(@Nullable Output<String> branchFilter) {
            $.branchFilter = branchFilter;
            return this;
        }

        /**
         * @param branchFilter Optional branch filter for the push mirror. Leave empty to mirror all branches.
         * 
         * @return builder
         * 
         */
        public Builder branchFilter(String branchFilter) {
            return branchFilter(Output.of(branchFilter));
        }

        /**
         * @param interval Mirror sync interval, for example 8h30m0s. Leave empty to use Forgejo&#39;s default.
         * 
         * @return builder
         * 
         */
        public Builder interval(@Nullable Output<String> interval) {
            $.interval = interval;
            return this;
        }

        /**
         * @param interval Mirror sync interval, for example 8h30m0s. Leave empty to use Forgejo&#39;s default.
         * 
         * @return builder
         * 
         */
        public Builder interval(String interval) {
            return interval(Output.of(interval));
        }

        /**
         * @param owner Repository owner.
         * 
         * @return builder
         * 
         */
        public Builder owner(Output<String> owner) {
            $.owner = owner;
            return this;
        }

        /**
         * @param owner Repository owner.
         * 
         * @return builder
         * 
         */
        public Builder owner(String owner) {
            return owner(Output.of(owner));
        }

        /**
         * @param remoteAddress Target remote URL for the push mirror.
         * 
         * @return builder
         * 
         */
        public Builder remoteAddress(Output<String> remoteAddress) {
            $.remoteAddress = remoteAddress;
            return this;
        }

        /**
         * @param remoteAddress Target remote URL for the push mirror.
         * 
         * @return builder
         * 
         */
        public Builder remoteAddress(String remoteAddress) {
            return remoteAddress(Output.of(remoteAddress));
        }

        /**
         * @param remotePassword Password or token for authenticating to the remote.
         * 
         * @return builder
         * 
         */
        public Builder remotePassword(@Nullable Output<String> remotePassword) {
            $.remotePassword = remotePassword;
            return this;
        }

        /**
         * @param remotePassword Password or token for authenticating to the remote.
         * 
         * @return builder
         * 
         */
        public Builder remotePassword(String remotePassword) {
            return remotePassword(Output.of(remotePassword));
        }

        /**
         * @param remoteUsername Username for authenticating to the remote.
         * 
         * @return builder
         * 
         */
        public Builder remoteUsername(@Nullable Output<String> remoteUsername) {
            $.remoteUsername = remoteUsername;
            return this;
        }

        /**
         * @param remoteUsername Username for authenticating to the remote.
         * 
         * @return builder
         * 
         */
        public Builder remoteUsername(String remoteUsername) {
            return remoteUsername(Output.of(remoteUsername));
        }

        /**
         * @param repository Repository name.
         * 
         * @return builder
         * 
         */
        public Builder repository(Output<String> repository) {
            $.repository = repository;
            return this;
        }

        /**
         * @param repository Repository name.
         * 
         * @return builder
         * 
         */
        public Builder repository(String repository) {
            return repository(Output.of(repository));
        }

        /**
         * @param syncOnCommit Whether pushes to this repository trigger the mirror.
         * 
         * @return builder
         * 
         */
        public Builder syncOnCommit(@Nullable Output<Boolean> syncOnCommit) {
            $.syncOnCommit = syncOnCommit;
            return this;
        }

        /**
         * @param syncOnCommit Whether pushes to this repository trigger the mirror.
         * 
         * @return builder
         * 
         */
        public Builder syncOnCommit(Boolean syncOnCommit) {
            return syncOnCommit(Output.of(syncOnCommit));
        }

        /**
         * @param useSsh Whether Forgejo should use an SSH key for the push mirror remote.
         * 
         * @return builder
         * 
         */
        public Builder useSsh(@Nullable Output<Boolean> useSsh) {
            $.useSsh = useSsh;
            return this;
        }

        /**
         * @param useSsh Whether Forgejo should use an SSH key for the push mirror remote.
         * 
         * @return builder
         * 
         */
        public Builder useSsh(Boolean useSsh) {
            return useSsh(Output.of(useSsh));
        }

        public RepositoryPushMirrorArgs build() {
            if ($.owner == null) {
                throw new MissingRequiredPropertyException("RepositoryPushMirrorArgs", "owner");
            }
            if ($.remoteAddress == null) {
                throw new MissingRequiredPropertyException("RepositoryPushMirrorArgs", "remoteAddress");
            }
            if ($.repository == null) {
                throw new MissingRequiredPropertyException("RepositoryPushMirrorArgs", "repository");
            }
            return $;
        }
    }

}
