// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package casa.siron.forgejo.forgejo;

import casa.siron.forgejo.forgejo.RepositorySettingsArgs;
import casa.siron.forgejo.forgejo.Utilities;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Settings for enabled Forgejo repository units and their wiki or issue tracker configuration.
 * 
 */
@ResourceType(type="forgejo:index:RepositorySettings")
public class RepositorySettings extends com.pulumi.resources.CustomResource {
    /**
     * Whether the actions unit is enabled. Leave unset to avoid managing it.
     * 
     */
    @Export(name="actions", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> actions;

    /**
     * @return Whether the actions unit is enabled. Leave unset to avoid managing it.
     * 
     */
    public Output<Optional<Boolean>> actions() {
        return Codegen.optional(this.actions);
    }
    /**
     * External issue tracker URL format. Forgejo supports placeholders such as {user}, {repo}, and {index}.
     * 
     */
    @Export(name="externalTrackerFormat", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> externalTrackerFormat;

    /**
     * @return External issue tracker URL format. Forgejo supports placeholders such as {user}, {repo}, and {index}.
     * 
     */
    public Output<Optional<String>> externalTrackerFormat() {
        return Codegen.optional(this.externalTrackerFormat);
    }
    /**
     * External issue tracker regular expression pattern.
     * 
     */
    @Export(name="externalTrackerRegexPattern", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> externalTrackerRegexPattern;

    /**
     * @return External issue tracker regular expression pattern.
     * 
     */
    public Output<Optional<String>> externalTrackerRegexPattern() {
        return Codegen.optional(this.externalTrackerRegexPattern);
    }
    /**
     * External issue tracker number style, for example numeric or alphanumeric.
     * 
     */
    @Export(name="externalTrackerStyle", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> externalTrackerStyle;

    /**
     * @return External issue tracker number style, for example numeric or alphanumeric.
     * 
     */
    public Output<Optional<String>> externalTrackerStyle() {
        return Codegen.optional(this.externalTrackerStyle);
    }
    /**
     * External issue tracker URL. Setting this also enables issues unless issues is explicitly set.
     * 
     */
    @Export(name="externalTrackerUrl", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> externalTrackerUrl;

    /**
     * @return External issue tracker URL. Setting this also enables issues unless issues is explicitly set.
     * 
     */
    public Output<Optional<String>> externalTrackerUrl() {
        return Codegen.optional(this.externalTrackerUrl);
    }
    /**
     * External wiki URL. Setting this also enables the wiki unless wiki is explicitly set.
     * 
     */
    @Export(name="externalWikiUrl", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> externalWikiUrl;

    /**
     * @return External wiki URL. Setting this also enables the wiki unless wiki is explicitly set.
     * 
     */
    public Output<Optional<String>> externalWikiUrl() {
        return Codegen.optional(this.externalWikiUrl);
    }
    /**
     * Whether the wiki is globally editable.
     * 
     */
    @Export(name="globallyEditableWiki", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> globallyEditableWiki;

    /**
     * @return Whether the wiki is globally editable.
     * 
     */
    public Output<Optional<Boolean>> globallyEditableWiki() {
        return Codegen.optional(this.globallyEditableWiki);
    }
    /**
     * Whether only contributors may track time in the internal issue tracker.
     * 
     */
    @Export(name="internalTrackerAllowOnlyContributorsToTrackTime", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> internalTrackerAllowOnlyContributorsToTrackTime;

    /**
     * @return Whether only contributors may track time in the internal issue tracker.
     * 
     */
    public Output<Optional<Boolean>> internalTrackerAllowOnlyContributorsToTrackTime() {
        return Codegen.optional(this.internalTrackerAllowOnlyContributorsToTrackTime);
    }
    /**
     * Whether issue dependencies are enabled in the internal issue tracker.
     * 
     */
    @Export(name="internalTrackerEnableIssueDependencies", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> internalTrackerEnableIssueDependencies;

    /**
     * @return Whether issue dependencies are enabled in the internal issue tracker.
     * 
     */
    public Output<Optional<Boolean>> internalTrackerEnableIssueDependencies() {
        return Codegen.optional(this.internalTrackerEnableIssueDependencies);
    }
    /**
     * Whether the internal issue tracker has time tracking enabled.
     * 
     */
    @Export(name="internalTrackerEnableTimeTracker", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> internalTrackerEnableTimeTracker;

    /**
     * @return Whether the internal issue tracker has time tracking enabled.
     * 
     */
    public Output<Optional<Boolean>> internalTrackerEnableTimeTracker() {
        return Codegen.optional(this.internalTrackerEnableTimeTracker);
    }
    /**
     * Whether the issue tracker unit is enabled. Leave unset to avoid managing it.
     * 
     */
    @Export(name="issues", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> issues;

    /**
     * @return Whether the issue tracker unit is enabled. Leave unset to avoid managing it.
     * 
     */
    public Output<Optional<Boolean>> issues() {
        return Codegen.optional(this.issues);
    }
    /**
     * Repository owner.
     * 
     */
    @Export(name="owner", refs={String.class}, tree="[0]")
    private Output<String> owner;

    /**
     * @return Repository owner.
     * 
     */
    public Output<String> owner() {
        return this.owner;
    }
    /**
     * Whether the packages unit is enabled. Leave unset to avoid managing it.
     * 
     */
    @Export(name="packages", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> packages;

    /**
     * @return Whether the packages unit is enabled. Leave unset to avoid managing it.
     * 
     */
    public Output<Optional<Boolean>> packages() {
        return Codegen.optional(this.packages);
    }
    /**
     * Whether the projects unit is enabled. Leave unset to avoid managing it.
     * 
     */
    @Export(name="projects", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> projects;

    /**
     * @return Whether the projects unit is enabled. Leave unset to avoid managing it.
     * 
     */
    public Output<Optional<Boolean>> projects() {
        return Codegen.optional(this.projects);
    }
    /**
     * Whether the pull request unit is enabled. Leave unset to avoid managing it.
     * 
     */
    @Export(name="pullRequests", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> pullRequests;

    /**
     * @return Whether the pull request unit is enabled. Leave unset to avoid managing it.
     * 
     */
    public Output<Optional<Boolean>> pullRequests() {
        return Codegen.optional(this.pullRequests);
    }
    /**
     * Whether the releases unit is enabled. Leave unset to avoid managing it.
     * 
     */
    @Export(name="releases", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> releases;

    /**
     * @return Whether the releases unit is enabled. Leave unset to avoid managing it.
     * 
     */
    public Output<Optional<Boolean>> releases() {
        return Codegen.optional(this.releases);
    }
    /**
     * Repository name.
     * 
     */
    @Export(name="repository", refs={String.class}, tree="[0]")
    private Output<String> repository;

    /**
     * @return Repository name.
     * 
     */
    public Output<String> repository() {
        return this.repository;
    }
    /**
     * Whether the wiki unit is enabled. Leave unset to avoid managing it.
     * 
     */
    @Export(name="wiki", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> wiki;

    /**
     * @return Whether the wiki unit is enabled. Leave unset to avoid managing it.
     * 
     */
    public Output<Optional<Boolean>> wiki() {
        return Codegen.optional(this.wiki);
    }
    /**
     * Branch used for the repository wiki.
     * 
     */
    @Export(name="wikiBranch", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> wikiBranch;

    /**
     * @return Branch used for the repository wiki.
     * 
     */
    public Output<Optional<String>> wikiBranch() {
        return Codegen.optional(this.wikiBranch);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public RepositorySettings(java.lang.String name) {
        this(name, RepositorySettingsArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public RepositorySettings(java.lang.String name, RepositorySettingsArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public RepositorySettings(java.lang.String name, RepositorySettingsArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("forgejo:index:RepositorySettings", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private RepositorySettings(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("forgejo:index:RepositorySettings", name, null, makeResourceOptions(options, id), false);
    }

    private static RepositorySettingsArgs makeArgs(RepositorySettingsArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? RepositorySettingsArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("https://forgejo.siron.casa/sironheart/forgejo-pulumi-provider/releases/download/v${VERSION}/")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static RepositorySettings get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new RepositorySettings(name, id, options);
    }
}
