// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package casa.siron.forgejo.forgejo;

import casa.siron.forgejo.forgejo.RepositoryPushMirrorArgs;
import casa.siron.forgejo.forgejo.Utilities;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * A Forgejo repository push mirror, optionally limited to matching branches.
 * 
 */
@ResourceType(type="forgejo:index:RepositoryPushMirror")
public class RepositoryPushMirror extends com.pulumi.resources.CustomResource {
    /**
     * Optional branch filter for the push mirror. Leave empty to mirror all branches.
     * 
     */
    @Export(name="branchFilter", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> branchFilter;

    /**
     * @return Optional branch filter for the push mirror. Leave empty to mirror all branches.
     * 
     */
    public Output<Optional<String>> branchFilter() {
        return Codegen.optional(this.branchFilter);
    }
    @Export(name="created", refs={String.class}, tree="[0]")
    private Output<String> created;

    public Output<String> created() {
        return this.created;
    }
    /**
     * Mirror sync interval, for example 8h30m0s. Leave empty to use Forgejo&#39;s default.
     * 
     */
    @Export(name="interval", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> interval;

    /**
     * @return Mirror sync interval, for example 8h30m0s. Leave empty to use Forgejo&#39;s default.
     * 
     */
    public Output<Optional<String>> interval() {
        return Codegen.optional(this.interval);
    }
    @Export(name="lastError", refs={String.class}, tree="[0]")
    private Output<String> lastError;

    public Output<String> lastError() {
        return this.lastError;
    }
    @Export(name="lastUpdate", refs={String.class}, tree="[0]")
    private Output<String> lastUpdate;

    public Output<String> lastUpdate() {
        return this.lastUpdate;
    }
    /**
     * Repository owner.
     * 
     */
    @Export(name="owner", refs={String.class}, tree="[0]")
    private Output<String> owner;

    /**
     * @return Repository owner.
     * 
     */
    public Output<String> owner() {
        return this.owner;
    }
    @Export(name="publicKey", refs={String.class}, tree="[0]")
    private Output<String> publicKey;

    public Output<String> publicKey() {
        return this.publicKey;
    }
    /**
     * Target remote URL for the push mirror.
     * 
     */
    @Export(name="remoteAddress", refs={String.class}, tree="[0]")
    private Output<String> remoteAddress;

    /**
     * @return Target remote URL for the push mirror.
     * 
     */
    public Output<String> remoteAddress() {
        return this.remoteAddress;
    }
    @Export(name="remoteName", refs={String.class}, tree="[0]")
    private Output<String> remoteName;

    public Output<String> remoteName() {
        return this.remoteName;
    }
    /**
     * Password or token for authenticating to the remote.
     * 
     */
    @Export(name="remotePassword", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> remotePassword;

    /**
     * @return Password or token for authenticating to the remote.
     * 
     */
    public Output<Optional<String>> remotePassword() {
        return Codegen.optional(this.remotePassword);
    }
    /**
     * Username for authenticating to the remote.
     * 
     */
    @Export(name="remoteUsername", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> remoteUsername;

    /**
     * @return Username for authenticating to the remote.
     * 
     */
    public Output<Optional<String>> remoteUsername() {
        return Codegen.optional(this.remoteUsername);
    }
    /**
     * Repository name.
     * 
     */
    @Export(name="repository", refs={String.class}, tree="[0]")
    private Output<String> repository;

    /**
     * @return Repository name.
     * 
     */
    public Output<String> repository() {
        return this.repository;
    }
    /**
     * Whether pushes to this repository trigger the mirror.
     * 
     */
    @Export(name="syncOnCommit", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> syncOnCommit;

    /**
     * @return Whether pushes to this repository trigger the mirror.
     * 
     */
    public Output<Optional<Boolean>> syncOnCommit() {
        return Codegen.optional(this.syncOnCommit);
    }
    /**
     * Whether Forgejo should use an SSH key for the push mirror remote.
     * 
     */
    @Export(name="useSsh", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> useSsh;

    /**
     * @return Whether Forgejo should use an SSH key for the push mirror remote.
     * 
     */
    public Output<Optional<Boolean>> useSsh() {
        return Codegen.optional(this.useSsh);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public RepositoryPushMirror(java.lang.String name) {
        this(name, RepositoryPushMirrorArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public RepositoryPushMirror(java.lang.String name, RepositoryPushMirrorArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public RepositoryPushMirror(java.lang.String name, RepositoryPushMirrorArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("forgejo:index:RepositoryPushMirror", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private RepositoryPushMirror(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("forgejo:index:RepositoryPushMirror", name, null, makeResourceOptions(options, id), false);
    }

    private static RepositoryPushMirrorArgs makeArgs(RepositoryPushMirrorArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? RepositoryPushMirrorArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("https://forgejo.siron.casa/sironheart/forgejo-pulumi-provider/releases/download/v${VERSION}/")
            .additionalSecretOutputs(List.of(
                "remotePassword"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static RepositoryPushMirror get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new RepositoryPushMirror(name, id, options);
    }
}
