// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package casa.siron.forgejo.forgejo;

import casa.siron.forgejo.forgejo.RepositoryArgs;
import casa.siron.forgejo.forgejo.Utilities;
import casa.siron.forgejo.forgejo.outputs.RepositorySettingsConfig;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * A Forgejo repository.
 * 
 */
@ResourceType(type="forgejo:index:Repository")
public class Repository extends com.pulumi.resources.CustomResource {
    @Export(name="cloneUrl", refs={String.class}, tree="[0]")
    private Output<String> cloneUrl;

    public Output<String> cloneUrl() {
        return this.cloneUrl;
    }
    /**
     * Default branch name. Leave empty to use Forgejo&#39;s default.
     * 
     */
    @Export(name="defaultBranch", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> defaultBranch;

    /**
     * @return Default branch name. Leave empty to use Forgejo&#39;s default.
     * 
     */
    public Output<Optional<String>> defaultBranch() {
        return Codegen.optional(this.defaultBranch);
    }
    /**
     * Repository description.
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    /**
     * @return Repository description.
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    @Export(name="fullName", refs={String.class}, tree="[0]")
    private Output<String> fullName;

    public Output<String> fullName() {
        return this.fullName;
    }
    @Export(name="htmlUrl", refs={String.class}, tree="[0]")
    private Output<String> htmlUrl;

    public Output<String> htmlUrl() {
        return this.htmlUrl;
    }
    /**
     * Repository name.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return Repository name.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Repository owner. Leave empty to create a repository for the authenticated user; set an organization name to create an organization repository.
     * 
     */
    @Export(name="owner", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> owner;

    /**
     * @return Repository owner. Leave empty to create a repository for the authenticated user; set an organization name to create an organization repository.
     * 
     */
    public Output<Optional<String>> owner() {
        return Codegen.optional(this.owner);
    }
    /**
     * Whether the repository is private.
     * 
     */
    @Export(name="private", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> private_;

    /**
     * @return Whether the repository is private.
     * 
     */
    public Output<Optional<Boolean>> private_() {
        return Codegen.optional(this.private_);
    }
    /**
     * Optional repository unit, wiki, and issue tracker settings to manage with this repository.
     * 
     */
    @Export(name="settings", refs={RepositorySettingsConfig.class}, tree="[0]")
    private Output</* @Nullable */ RepositorySettingsConfig> settings;

    /**
     * @return Optional repository unit, wiki, and issue tracker settings to manage with this repository.
     * 
     */
    public Output<Optional<RepositorySettingsConfig>> settings() {
        return Codegen.optional(this.settings);
    }
    @Export(name="sshUrl", refs={String.class}, tree="[0]")
    private Output<String> sshUrl;

    public Output<String> sshUrl() {
        return this.sshUrl;
    }
    /**
     * Whether the repository can be used as a template.
     * 
     */
    @Export(name="template", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> template;

    /**
     * @return Whether the repository can be used as a template.
     * 
     */
    public Output<Optional<Boolean>> template() {
        return Codegen.optional(this.template);
    }
    /**
     * Repository website URL.
     * 
     */
    @Export(name="website", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> website;

    /**
     * @return Repository website URL.
     * 
     */
    public Output<Optional<String>> website() {
        return Codegen.optional(this.website);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Repository(java.lang.String name) {
        this(name, RepositoryArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Repository(java.lang.String name, RepositoryArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Repository(java.lang.String name, RepositoryArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("forgejo:index:Repository", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Repository(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("forgejo:index:Repository", name, null, makeResourceOptions(options, id), false);
    }

    private static RepositoryArgs makeArgs(RepositoryArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? RepositoryArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("https://forgejo.siron.casa/sironheart/forgejo-pulumi-provider/releases/download/v${VERSION}/")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Repository get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Repository(name, id, options);
    }
}
