// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package casa.siron.forgejo.forgejo;

import casa.siron.forgejo.forgejo.RepositoryBranchProtectionArgs;
import casa.siron.forgejo.forgejo.Utilities;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * A Forgejo branch protection rule for a repository.
 * 
 */
@ResourceType(type="forgejo:index:RepositoryBranchProtection")
public class RepositoryBranchProtection extends com.pulumi.resources.CustomResource {
    /**
     * Teams whose approvals count.
     * 
     */
    @Export(name="approvalsWhitelistTeams", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> approvalsWhitelistTeams;

    /**
     * @return Teams whose approvals count.
     * 
     */
    public Output<Optional<List<String>>> approvalsWhitelistTeams() {
        return Codegen.optional(this.approvalsWhitelistTeams);
    }
    /**
     * Users whose approvals count.
     * 
     */
    @Export(name="approvalsWhitelistUsernames", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> approvalsWhitelistUsernames;

    /**
     * @return Users whose approvals count.
     * 
     */
    public Output<Optional<List<String>>> approvalsWhitelistUsernames() {
        return Codegen.optional(this.approvalsWhitelistUsernames);
    }
    /**
     * Whether official review requests block merging.
     * 
     */
    @Export(name="blockOnOfficialReviewRequests", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> blockOnOfficialReviewRequests;

    /**
     * @return Whether official review requests block merging.
     * 
     */
    public Output<Optional<Boolean>> blockOnOfficialReviewRequests() {
        return Codegen.optional(this.blockOnOfficialReviewRequests);
    }
    /**
     * Whether outdated branches block merging.
     * 
     */
    @Export(name="blockOnOutdatedBranch", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> blockOnOutdatedBranch;

    /**
     * @return Whether outdated branches block merging.
     * 
     */
    public Output<Optional<Boolean>> blockOnOutdatedBranch() {
        return Codegen.optional(this.blockOnOutdatedBranch);
    }
    /**
     * Whether rejected reviews block merging.
     * 
     */
    @Export(name="blockOnRejectedReviews", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> blockOnRejectedReviews;

    /**
     * @return Whether rejected reviews block merging.
     * 
     */
    public Output<Optional<Boolean>> blockOnRejectedReviews() {
        return Codegen.optional(this.blockOnRejectedReviews);
    }
    @Export(name="created", refs={String.class}, tree="[0]")
    private Output<String> created;

    public Output<String> created() {
        return this.created;
    }
    /**
     * Whether stale approvals are dismissed after new commits.
     * 
     */
    @Export(name="dismissStaleApprovals", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> dismissStaleApprovals;

    /**
     * @return Whether stale approvals are dismissed after new commits.
     * 
     */
    public Output<Optional<Boolean>> dismissStaleApprovals() {
        return Codegen.optional(this.dismissStaleApprovals);
    }
    /**
     * Whether review approvals are limited to the approval whitelist.
     * 
     */
    @Export(name="enableApprovalsWhitelist", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> enableApprovalsWhitelist;

    /**
     * @return Whether review approvals are limited to the approval whitelist.
     * 
     */
    public Output<Optional<Boolean>> enableApprovalsWhitelist() {
        return Codegen.optional(this.enableApprovalsWhitelist);
    }
    /**
     * Whether merging is limited to the merge whitelist.
     * 
     */
    @Export(name="enableMergeWhitelist", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> enableMergeWhitelist;

    /**
     * @return Whether merging is limited to the merge whitelist.
     * 
     */
    public Output<Optional<Boolean>> enableMergeWhitelist() {
        return Codegen.optional(this.enableMergeWhitelist);
    }
    /**
     * Whether protected branches can be pushed to directly.
     * 
     */
    @Export(name="enablePush", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> enablePush;

    /**
     * @return Whether protected branches can be pushed to directly.
     * 
     */
    public Output<Optional<Boolean>> enablePush() {
        return Codegen.optional(this.enablePush);
    }
    /**
     * Whether direct pushes are limited to the push whitelist.
     * 
     */
    @Export(name="enablePushWhitelist", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> enablePushWhitelist;

    /**
     * @return Whether direct pushes are limited to the push whitelist.
     * 
     */
    public Output<Optional<Boolean>> enablePushWhitelist() {
        return Codegen.optional(this.enablePushWhitelist);
    }
    /**
     * Whether status checks are required before merge.
     * 
     */
    @Export(name="enableStatusCheck", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> enableStatusCheck;

    /**
     * @return Whether status checks are required before merge.
     * 
     */
    public Output<Optional<Boolean>> enableStatusCheck() {
        return Codegen.optional(this.enableStatusCheck);
    }
    /**
     * Teams allowed to merge.
     * 
     */
    @Export(name="mergeWhitelistTeams", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> mergeWhitelistTeams;

    /**
     * @return Teams allowed to merge.
     * 
     */
    public Output<Optional<List<String>>> mergeWhitelistTeams() {
        return Codegen.optional(this.mergeWhitelistTeams);
    }
    /**
     * Users allowed to merge.
     * 
     */
    @Export(name="mergeWhitelistUsernames", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> mergeWhitelistUsernames;

    /**
     * @return Users allowed to merge.
     * 
     */
    public Output<Optional<List<String>>> mergeWhitelistUsernames() {
        return Codegen.optional(this.mergeWhitelistUsernames);
    }
    /**
     * Protected branch name or rule pattern.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return Protected branch name or rule pattern.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Repository owner.
     * 
     */
    @Export(name="owner", refs={String.class}, tree="[0]")
    private Output<String> owner;

    /**
     * @return Repository owner.
     * 
     */
    public Output<String> owner() {
        return this.owner;
    }
    /**
     * Protected file patterns.
     * 
     */
    @Export(name="protectedFilePatterns", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> protectedFilePatterns;

    /**
     * @return Protected file patterns.
     * 
     */
    public Output<Optional<String>> protectedFilePatterns() {
        return Codegen.optional(this.protectedFilePatterns);
    }
    /**
     * Whether deploy keys may push directly.
     * 
     */
    @Export(name="pushWhitelistDeployKeys", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> pushWhitelistDeployKeys;

    /**
     * @return Whether deploy keys may push directly.
     * 
     */
    public Output<Optional<Boolean>> pushWhitelistDeployKeys() {
        return Codegen.optional(this.pushWhitelistDeployKeys);
    }
    /**
     * Teams allowed to push directly.
     * 
     */
    @Export(name="pushWhitelistTeams", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> pushWhitelistTeams;

    /**
     * @return Teams allowed to push directly.
     * 
     */
    public Output<Optional<List<String>>> pushWhitelistTeams() {
        return Codegen.optional(this.pushWhitelistTeams);
    }
    /**
     * Users allowed to push directly.
     * 
     */
    @Export(name="pushWhitelistUsernames", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> pushWhitelistUsernames;

    /**
     * @return Users allowed to push directly.
     * 
     */
    public Output<Optional<List<String>>> pushWhitelistUsernames() {
        return Codegen.optional(this.pushWhitelistUsernames);
    }
    /**
     * Repository name.
     * 
     */
    @Export(name="repository", refs={String.class}, tree="[0]")
    private Output<String> repository;

    /**
     * @return Repository name.
     * 
     */
    public Output<String> repository() {
        return this.repository;
    }
    /**
     * Whether commits must be signed.
     * 
     */
    @Export(name="requireSignedCommits", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> requireSignedCommits;

    /**
     * @return Whether commits must be signed.
     * 
     */
    public Output<Optional<Boolean>> requireSignedCommits() {
        return Codegen.optional(this.requireSignedCommits);
    }
    /**
     * Number of required approving reviews.
     * 
     */
    @Export(name="requiredApprovals", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> requiredApprovals;

    /**
     * @return Number of required approving reviews.
     * 
     */
    public Output<Optional<Integer>> requiredApprovals() {
        return Codegen.optional(this.requiredApprovals);
    }
    /**
     * Required status check contexts.
     * 
     */
    @Export(name="statusCheckContexts", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> statusCheckContexts;

    /**
     * @return Required status check contexts.
     * 
     */
    public Output<Optional<List<String>>> statusCheckContexts() {
        return Codegen.optional(this.statusCheckContexts);
    }
    /**
     * Unprotected file patterns.
     * 
     */
    @Export(name="unprotectedFilePatterns", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> unprotectedFilePatterns;

    /**
     * @return Unprotected file patterns.
     * 
     */
    public Output<Optional<String>> unprotectedFilePatterns() {
        return Codegen.optional(this.unprotectedFilePatterns);
    }
    @Export(name="updated", refs={String.class}, tree="[0]")
    private Output<String> updated;

    public Output<String> updated() {
        return this.updated;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public RepositoryBranchProtection(java.lang.String name) {
        this(name, RepositoryBranchProtectionArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public RepositoryBranchProtection(java.lang.String name, RepositoryBranchProtectionArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public RepositoryBranchProtection(java.lang.String name, RepositoryBranchProtectionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("forgejo:index:RepositoryBranchProtection", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private RepositoryBranchProtection(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("forgejo:index:RepositoryBranchProtection", name, null, makeResourceOptions(options, id), false);
    }

    private static RepositoryBranchProtectionArgs makeArgs(RepositoryBranchProtectionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? RepositoryBranchProtectionArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("https://forgejo.siron.casa/sironheart/forgejo-pulumi-provider/releases/download/v${VERSION}/")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static RepositoryBranchProtection get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new RepositoryBranchProtection(name, id, options);
    }
}
