// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package casa.siron.forgejo.forgejo;

import casa.siron.forgejo.forgejo.inputs.RepositorySettingsConfigArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class RepositoryArgs extends com.pulumi.resources.ResourceArgs {

    public static final RepositoryArgs Empty = new RepositoryArgs();

    /**
     * Default branch name. Leave empty to use Forgejo&#39;s default.
     * 
     */
    @Import(name="defaultBranch")
    private @Nullable Output<String> defaultBranch;

    /**
     * @return Default branch name. Leave empty to use Forgejo&#39;s default.
     * 
     */
    public Optional<Output<String>> defaultBranch() {
        return Optional.ofNullable(this.defaultBranch);
    }

    /**
     * Repository description.
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return Repository description.
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * Repository name.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return Repository name.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * Repository owner. Leave empty to create a repository for the authenticated user; set an organization name to create an organization repository.
     * 
     */
    @Import(name="owner")
    private @Nullable Output<String> owner;

    /**
     * @return Repository owner. Leave empty to create a repository for the authenticated user; set an organization name to create an organization repository.
     * 
     */
    public Optional<Output<String>> owner() {
        return Optional.ofNullable(this.owner);
    }

    /**
     * Whether the repository is private.
     * 
     */
    @Import(name="private")
    private @Nullable Output<Boolean> private_;

    /**
     * @return Whether the repository is private.
     * 
     */
    public Optional<Output<Boolean>> private_() {
        return Optional.ofNullable(this.private_);
    }

    /**
     * Optional repository unit, wiki, and issue tracker settings to manage with this repository.
     * 
     */
    @Import(name="settings")
    private @Nullable Output<RepositorySettingsConfigArgs> settings;

    /**
     * @return Optional repository unit, wiki, and issue tracker settings to manage with this repository.
     * 
     */
    public Optional<Output<RepositorySettingsConfigArgs>> settings() {
        return Optional.ofNullable(this.settings);
    }

    /**
     * Whether the repository can be used as a template.
     * 
     */
    @Import(name="template")
    private @Nullable Output<Boolean> template;

    /**
     * @return Whether the repository can be used as a template.
     * 
     */
    public Optional<Output<Boolean>> template() {
        return Optional.ofNullable(this.template);
    }

    /**
     * Repository website URL.
     * 
     */
    @Import(name="website")
    private @Nullable Output<String> website;

    /**
     * @return Repository website URL.
     * 
     */
    public Optional<Output<String>> website() {
        return Optional.ofNullable(this.website);
    }

    private RepositoryArgs() {}

    private RepositoryArgs(RepositoryArgs $) {
        this.defaultBranch = $.defaultBranch;
        this.description = $.description;
        this.name = $.name;
        this.owner = $.owner;
        this.private_ = $.private_;
        this.settings = $.settings;
        this.template = $.template;
        this.website = $.website;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RepositoryArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RepositoryArgs $;

        public Builder() {
            $ = new RepositoryArgs();
        }

        public Builder(RepositoryArgs defaults) {
            $ = new RepositoryArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param defaultBranch Default branch name. Leave empty to use Forgejo&#39;s default.
         * 
         * @return builder
         * 
         */
        public Builder defaultBranch(@Nullable Output<String> defaultBranch) {
            $.defaultBranch = defaultBranch;
            return this;
        }

        /**
         * @param defaultBranch Default branch name. Leave empty to use Forgejo&#39;s default.
         * 
         * @return builder
         * 
         */
        public Builder defaultBranch(String defaultBranch) {
            return defaultBranch(Output.of(defaultBranch));
        }

        /**
         * @param description Repository description.
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description Repository description.
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param name Repository name.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Repository name.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param owner Repository owner. Leave empty to create a repository for the authenticated user; set an organization name to create an organization repository.
         * 
         * @return builder
         * 
         */
        public Builder owner(@Nullable Output<String> owner) {
            $.owner = owner;
            return this;
        }

        /**
         * @param owner Repository owner. Leave empty to create a repository for the authenticated user; set an organization name to create an organization repository.
         * 
         * @return builder
         * 
         */
        public Builder owner(String owner) {
            return owner(Output.of(owner));
        }

        /**
         * @param private_ Whether the repository is private.
         * 
         * @return builder
         * 
         */
        public Builder private_(@Nullable Output<Boolean> private_) {
            $.private_ = private_;
            return this;
        }

        /**
         * @param private_ Whether the repository is private.
         * 
         * @return builder
         * 
         */
        public Builder private_(Boolean private_) {
            return private_(Output.of(private_));
        }

        /**
         * @param settings Optional repository unit, wiki, and issue tracker settings to manage with this repository.
         * 
         * @return builder
         * 
         */
        public Builder settings(@Nullable Output<RepositorySettingsConfigArgs> settings) {
            $.settings = settings;
            return this;
        }

        /**
         * @param settings Optional repository unit, wiki, and issue tracker settings to manage with this repository.
         * 
         * @return builder
         * 
         */
        public Builder settings(RepositorySettingsConfigArgs settings) {
            return settings(Output.of(settings));
        }

        /**
         * @param template Whether the repository can be used as a template.
         * 
         * @return builder
         * 
         */
        public Builder template(@Nullable Output<Boolean> template) {
            $.template = template;
            return this;
        }

        /**
         * @param template Whether the repository can be used as a template.
         * 
         * @return builder
         * 
         */
        public Builder template(Boolean template) {
            return template(Output.of(template));
        }

        /**
         * @param website Repository website URL.
         * 
         * @return builder
         * 
         */
        public Builder website(@Nullable Output<String> website) {
            $.website = website;
            return this;
        }

        /**
         * @param website Repository website URL.
         * 
         * @return builder
         * 
         */
        public Builder website(String website) {
            return website(Output.of(website));
        }

        public RepositoryArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("RepositoryArgs", "name");
            }
            return $;
        }
    }

}
