// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package casa.siron.forgejo.forgejo;

import casa.siron.forgejo.forgejo.RepositoryTagProtectionArgs;
import casa.siron.forgejo.forgejo.Utilities;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * A Forgejo tag protection rule for a repository.
 * 
 */
@ResourceType(type="forgejo:index:RepositoryTagProtection")
public class RepositoryTagProtection extends com.pulumi.resources.CustomResource {
    /**
     * Protected tag name pattern, for example v*.
     * 
     */
    @Export(name="namePattern", refs={String.class}, tree="[0]")
    private Output<String> namePattern;

    /**
     * @return Protected tag name pattern, for example v*.
     * 
     */
    public Output<String> namePattern() {
        return this.namePattern;
    }
    /**
     * Repository owner.
     * 
     */
    @Export(name="owner", refs={String.class}, tree="[0]")
    private Output<String> owner;

    /**
     * @return Repository owner.
     * 
     */
    public Output<String> owner() {
        return this.owner;
    }
    @Export(name="protectionId", refs={Integer.class}, tree="[0]")
    private Output<Integer> protectionId;

    public Output<Integer> protectionId() {
        return this.protectionId;
    }
    /**
     * Repository name.
     * 
     */
    @Export(name="repository", refs={String.class}, tree="[0]")
    private Output<String> repository;

    /**
     * @return Repository name.
     * 
     */
    public Output<String> repository() {
        return this.repository;
    }
    /**
     * Teams allowed to create matching tags.
     * 
     */
    @Export(name="whitelistTeams", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> whitelistTeams;

    /**
     * @return Teams allowed to create matching tags.
     * 
     */
    public Output<Optional<List<String>>> whitelistTeams() {
        return Codegen.optional(this.whitelistTeams);
    }
    /**
     * Users allowed to create matching tags.
     * 
     */
    @Export(name="whitelistUsernames", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> whitelistUsernames;

    /**
     * @return Users allowed to create matching tags.
     * 
     */
    public Output<Optional<List<String>>> whitelistUsernames() {
        return Codegen.optional(this.whitelistUsernames);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public RepositoryTagProtection(java.lang.String name) {
        this(name, RepositoryTagProtectionArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public RepositoryTagProtection(java.lang.String name, RepositoryTagProtectionArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public RepositoryTagProtection(java.lang.String name, RepositoryTagProtectionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("forgejo:index:RepositoryTagProtection", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private RepositoryTagProtection(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("forgejo:index:RepositoryTagProtection", name, null, makeResourceOptions(options, id), false);
    }

    private static RepositoryTagProtectionArgs makeArgs(RepositoryTagProtectionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? RepositoryTagProtectionArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("https://forgejo.siron.casa/sironheart/forgejo-pulumi-provider/releases/download/v${VERSION}/")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static RepositoryTagProtection get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new RepositoryTagProtection(name, id, options);
    }
}
