// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.sironheart.pulumi.forgejo;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DeployKeyArgs extends com.pulumi.resources.ResourceArgs {

    public static final DeployKeyArgs Empty = new DeployKeyArgs();

    /**
     * OpenSSH public key material.
     * 
     */
    @Import(name="key", required=true)
    private Output<String> key;

    /**
     * @return OpenSSH public key material.
     * 
     */
    public Output<String> key() {
        return this.key;
    }

    /**
     * Repository owner.
     * 
     */
    @Import(name="owner", required=true)
    private Output<String> owner;

    /**
     * @return Repository owner.
     * 
     */
    public Output<String> owner() {
        return this.owner;
    }

    /**
     * Whether the deploy key is read-only.
     * 
     */
    @Import(name="readOnly")
    private @Nullable Output<Boolean> readOnly;

    /**
     * @return Whether the deploy key is read-only.
     * 
     */
    public Optional<Output<Boolean>> readOnly() {
        return Optional.ofNullable(this.readOnly);
    }

    /**
     * Repository name.
     * 
     */
    @Import(name="repository", required=true)
    private Output<String> repository;

    /**
     * @return Repository name.
     * 
     */
    public Output<String> repository() {
        return this.repository;
    }

    /**
     * Deploy key title.
     * 
     */
    @Import(name="title", required=true)
    private Output<String> title;

    /**
     * @return Deploy key title.
     * 
     */
    public Output<String> title() {
        return this.title;
    }

    private DeployKeyArgs() {}

    private DeployKeyArgs(DeployKeyArgs $) {
        this.key = $.key;
        this.owner = $.owner;
        this.readOnly = $.readOnly;
        this.repository = $.repository;
        this.title = $.title;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DeployKeyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DeployKeyArgs $;

        public Builder() {
            $ = new DeployKeyArgs();
        }

        public Builder(DeployKeyArgs defaults) {
            $ = new DeployKeyArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param key OpenSSH public key material.
         * 
         * @return builder
         * 
         */
        public Builder key(Output<String> key) {
            $.key = key;
            return this;
        }

        /**
         * @param key OpenSSH public key material.
         * 
         * @return builder
         * 
         */
        public Builder key(String key) {
            return key(Output.of(key));
        }

        /**
         * @param owner Repository owner.
         * 
         * @return builder
         * 
         */
        public Builder owner(Output<String> owner) {
            $.owner = owner;
            return this;
        }

        /**
         * @param owner Repository owner.
         * 
         * @return builder
         * 
         */
        public Builder owner(String owner) {
            return owner(Output.of(owner));
        }

        /**
         * @param readOnly Whether the deploy key is read-only.
         * 
         * @return builder
         * 
         */
        public Builder readOnly(@Nullable Output<Boolean> readOnly) {
            $.readOnly = readOnly;
            return this;
        }

        /**
         * @param readOnly Whether the deploy key is read-only.
         * 
         * @return builder
         * 
         */
        public Builder readOnly(Boolean readOnly) {
            return readOnly(Output.of(readOnly));
        }

        /**
         * @param repository Repository name.
         * 
         * @return builder
         * 
         */
        public Builder repository(Output<String> repository) {
            $.repository = repository;
            return this;
        }

        /**
         * @param repository Repository name.
         * 
         * @return builder
         * 
         */
        public Builder repository(String repository) {
            return repository(Output.of(repository));
        }

        /**
         * @param title Deploy key title.
         * 
         * @return builder
         * 
         */
        public Builder title(Output<String> title) {
            $.title = title;
            return this;
        }

        /**
         * @param title Deploy key title.
         * 
         * @return builder
         * 
         */
        public Builder title(String title) {
            return title(Output.of(title));
        }

        public DeployKeyArgs build() {
            if ($.key == null) {
                throw new MissingRequiredPropertyException("DeployKeyArgs", "key");
            }
            if ($.owner == null) {
                throw new MissingRequiredPropertyException("DeployKeyArgs", "owner");
            }
            $.readOnly = Codegen.booleanProp("readOnly").output().arg($.readOnly).def(true).getNullable();
            if ($.repository == null) {
                throw new MissingRequiredPropertyException("DeployKeyArgs", "repository");
            }
            if ($.title == null) {
                throw new MissingRequiredPropertyException("DeployKeyArgs", "title");
            }
            return $;
        }
    }

}
