// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.sironheart.pulumi.forgejo;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class OrganizationArgs extends com.pulumi.resources.ResourceArgs {

    public static final OrganizationArgs Empty = new OrganizationArgs();

    /**
     * Organization description.
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return Organization description.
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * Organization display name.
     * 
     */
    @Import(name="fullName")
    private @Nullable Output<String> fullName;

    /**
     * @return Organization display name.
     * 
     */
    public Optional<Output<String>> fullName() {
        return Optional.ofNullable(this.fullName);
    }

    /**
     * Organization location.
     * 
     */
    @Import(name="location")
    private @Nullable Output<String> location;

    /**
     * @return Organization location.
     * 
     */
    public Optional<Output<String>> location() {
        return Optional.ofNullable(this.location);
    }

    /**
     * Organization username/slug.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return Organization username/slug.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * Organization visibility, for example public, limited, or private. Leave empty to use Forgejo&#39;s default.
     * 
     */
    @Import(name="visibility")
    private @Nullable Output<String> visibility;

    /**
     * @return Organization visibility, for example public, limited, or private. Leave empty to use Forgejo&#39;s default.
     * 
     */
    public Optional<Output<String>> visibility() {
        return Optional.ofNullable(this.visibility);
    }

    /**
     * Organization website URL.
     * 
     */
    @Import(name="website")
    private @Nullable Output<String> website;

    /**
     * @return Organization website URL.
     * 
     */
    public Optional<Output<String>> website() {
        return Optional.ofNullable(this.website);
    }

    private OrganizationArgs() {}

    private OrganizationArgs(OrganizationArgs $) {
        this.description = $.description;
        this.fullName = $.fullName;
        this.location = $.location;
        this.name = $.name;
        this.visibility = $.visibility;
        this.website = $.website;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(OrganizationArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private OrganizationArgs $;

        public Builder() {
            $ = new OrganizationArgs();
        }

        public Builder(OrganizationArgs defaults) {
            $ = new OrganizationArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param description Organization description.
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description Organization description.
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param fullName Organization display name.
         * 
         * @return builder
         * 
         */
        public Builder fullName(@Nullable Output<String> fullName) {
            $.fullName = fullName;
            return this;
        }

        /**
         * @param fullName Organization display name.
         * 
         * @return builder
         * 
         */
        public Builder fullName(String fullName) {
            return fullName(Output.of(fullName));
        }

        /**
         * @param location Organization location.
         * 
         * @return builder
         * 
         */
        public Builder location(@Nullable Output<String> location) {
            $.location = location;
            return this;
        }

        /**
         * @param location Organization location.
         * 
         * @return builder
         * 
         */
        public Builder location(String location) {
            return location(Output.of(location));
        }

        /**
         * @param name Organization username/slug.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Organization username/slug.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param visibility Organization visibility, for example public, limited, or private. Leave empty to use Forgejo&#39;s default.
         * 
         * @return builder
         * 
         */
        public Builder visibility(@Nullable Output<String> visibility) {
            $.visibility = visibility;
            return this;
        }

        /**
         * @param visibility Organization visibility, for example public, limited, or private. Leave empty to use Forgejo&#39;s default.
         * 
         * @return builder
         * 
         */
        public Builder visibility(String visibility) {
            return visibility(Output.of(visibility));
        }

        /**
         * @param website Organization website URL.
         * 
         * @return builder
         * 
         */
        public Builder website(@Nullable Output<String> website) {
            $.website = website;
            return this;
        }

        /**
         * @param website Organization website URL.
         * 
         * @return builder
         * 
         */
        public Builder website(String website) {
            return website(Output.of(website));
        }

        public OrganizationArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("OrganizationArgs", "name");
            }
            return $;
        }
    }

}
