// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Returns the authenticated Forgejo user.
 */
export function getCurrentUser(args?: GetCurrentUserArgs, opts?: pulumi.InvokeOptions): Promise<GetCurrentUserResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("forgejo:index:getCurrentUser", {
    }, opts);
}

export interface GetCurrentUserArgs {
}

export interface GetCurrentUserResult {
    readonly email: string;
    readonly fullName: string;
    readonly isAdmin: boolean;
    readonly login: string;
    readonly userId: number;
}
/**
 * Returns the authenticated Forgejo user.
 */
export function getCurrentUserOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetCurrentUserResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("forgejo:index:getCurrentUser", {
    }, opts);
}

