// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { DeployKeyArgs } from "./deployKey";
export type DeployKey = import("./deployKey").DeployKey;
export const DeployKey: typeof import("./deployKey").DeployKey = null as any;
utilities.lazyLoad(exports, ["DeployKey"], () => require("./deployKey"));

export { GetCurrentUserArgs, GetCurrentUserResult } from "./getCurrentUser";
export const getCurrentUser: typeof import("./getCurrentUser").getCurrentUser = null as any;
export const getCurrentUserOutput: typeof import("./getCurrentUser").getCurrentUserOutput = null as any;
utilities.lazyLoad(exports, ["getCurrentUser","getCurrentUserOutput"], () => require("./getCurrentUser"));

export { OrganizationArgs } from "./organization";
export type Organization = import("./organization").Organization;
export const Organization: typeof import("./organization").Organization = null as any;
utilities.lazyLoad(exports, ["Organization"], () => require("./organization"));

export { OrganizationTeamArgs } from "./organizationTeam";
export type OrganizationTeam = import("./organizationTeam").OrganizationTeam;
export const OrganizationTeam: typeof import("./organizationTeam").OrganizationTeam = null as any;
utilities.lazyLoad(exports, ["OrganizationTeam"], () => require("./organizationTeam"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { PublicKeyArgs } from "./publicKey";
export type PublicKey = import("./publicKey").PublicKey;
export const PublicKey: typeof import("./publicKey").PublicKey = null as any;
utilities.lazyLoad(exports, ["PublicKey"], () => require("./publicKey"));

export { RepositoryArgs } from "./repository";
export type Repository = import("./repository").Repository;
export const Repository: typeof import("./repository").Repository = null as any;
utilities.lazyLoad(exports, ["Repository"], () => require("./repository"));

export { RepositoryActionVariableArgs } from "./repositoryActionVariable";
export type RepositoryActionVariable = import("./repositoryActionVariable").RepositoryActionVariable;
export const RepositoryActionVariable: typeof import("./repositoryActionVariable").RepositoryActionVariable = null as any;
utilities.lazyLoad(exports, ["RepositoryActionVariable"], () => require("./repositoryActionVariable"));

export { RepositoryTagProtectionArgs } from "./repositoryTagProtection";
export type RepositoryTagProtection = import("./repositoryTagProtection").RepositoryTagProtection;
export const RepositoryTagProtection: typeof import("./repositoryTagProtection").RepositoryTagProtection = null as any;
utilities.lazyLoad(exports, ["RepositoryTagProtection"], () => require("./repositoryTagProtection"));


// Export sub-modules:
import * as config from "./config";

export {
    config,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "forgejo:index:DeployKey":
                return new DeployKey(name, <any>undefined, { urn })
            case "forgejo:index:Organization":
                return new Organization(name, <any>undefined, { urn })
            case "forgejo:index:OrganizationTeam":
                return new OrganizationTeam(name, <any>undefined, { urn })
            case "forgejo:index:PublicKey":
                return new PublicKey(name, <any>undefined, { urn })
            case "forgejo:index:Repository":
                return new Repository(name, <any>undefined, { urn })
            case "forgejo:index:RepositoryActionVariable":
                return new RepositoryActionVariable(name, <any>undefined, { urn })
            case "forgejo:index:RepositoryTagProtection":
                return new RepositoryTagProtection(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("forgejo", "index", _module)
pulumi.runtime.registerResourcePackage("forgejo", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:forgejo") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
