// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A Forgejo tag protection rule for a repository.
 */
export class RepositoryTagProtection extends pulumi.CustomResource {
    /**
     * Get an existing RepositoryTagProtection resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): RepositoryTagProtection {
        return new RepositoryTagProtection(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'forgejo:index:RepositoryTagProtection';

    /**
     * Returns true if the given object is an instance of RepositoryTagProtection.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RepositoryTagProtection {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RepositoryTagProtection.__pulumiType;
    }

    /**
     * Protected tag name pattern, for example v*.
     */
    declare public readonly namePattern: pulumi.Output<string>;
    /**
     * Repository owner.
     */
    declare public readonly owner: pulumi.Output<string>;
    declare public /*out*/ readonly protectionId: pulumi.Output<number>;
    /**
     * Repository name.
     */
    declare public readonly repository: pulumi.Output<string>;
    /**
     * Teams allowed to create matching tags.
     */
    declare public readonly whitelistTeams: pulumi.Output<string[] | undefined>;
    /**
     * Users allowed to create matching tags.
     */
    declare public readonly whitelistUsernames: pulumi.Output<string[] | undefined>;

    /**
     * Create a RepositoryTagProtection resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RepositoryTagProtectionArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.namePattern === undefined && !opts.urn) {
                throw new Error("Missing required property 'namePattern'");
            }
            if (args?.owner === undefined && !opts.urn) {
                throw new Error("Missing required property 'owner'");
            }
            if (args?.repository === undefined && !opts.urn) {
                throw new Error("Missing required property 'repository'");
            }
            resourceInputs["namePattern"] = args?.namePattern;
            resourceInputs["owner"] = args?.owner;
            resourceInputs["repository"] = args?.repository;
            resourceInputs["whitelistTeams"] = args?.whitelistTeams;
            resourceInputs["whitelistUsernames"] = args?.whitelistUsernames;
            resourceInputs["protectionId"] = undefined /*out*/;
        } else {
            resourceInputs["namePattern"] = undefined /*out*/;
            resourceInputs["owner"] = undefined /*out*/;
            resourceInputs["protectionId"] = undefined /*out*/;
            resourceInputs["repository"] = undefined /*out*/;
            resourceInputs["whitelistTeams"] = undefined /*out*/;
            resourceInputs["whitelistUsernames"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RepositoryTagProtection.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a RepositoryTagProtection resource.
 */
export interface RepositoryTagProtectionArgs {
    /**
     * Protected tag name pattern, for example v*.
     */
    namePattern: pulumi.Input<string>;
    /**
     * Repository owner.
     */
    owner: pulumi.Input<string>;
    /**
     * Repository name.
     */
    repository: pulumi.Input<string>;
    /**
     * Teams allowed to create matching tags.
     */
    whitelistTeams?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Users allowed to create matching tags.
     */
    whitelistUsernames?: pulumi.Input<pulumi.Input<string>[]>;
}
