// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A Forgejo branch protection rule for a repository.
 */
export class RepositoryBranchProtection extends pulumi.CustomResource {
    /**
     * Get an existing RepositoryBranchProtection resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): RepositoryBranchProtection {
        return new RepositoryBranchProtection(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'forgejo:index:RepositoryBranchProtection';

    /**
     * Returns true if the given object is an instance of RepositoryBranchProtection.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RepositoryBranchProtection {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RepositoryBranchProtection.__pulumiType;
    }

    /**
     * Teams whose approvals count.
     */
    declare public readonly approvalsWhitelistTeams: pulumi.Output<string[] | undefined>;
    /**
     * Users whose approvals count.
     */
    declare public readonly approvalsWhitelistUsernames: pulumi.Output<string[] | undefined>;
    /**
     * Whether official review requests block merging.
     */
    declare public readonly blockOnOfficialReviewRequests: pulumi.Output<boolean | undefined>;
    /**
     * Whether outdated branches block merging.
     */
    declare public readonly blockOnOutdatedBranch: pulumi.Output<boolean | undefined>;
    /**
     * Whether rejected reviews block merging.
     */
    declare public readonly blockOnRejectedReviews: pulumi.Output<boolean | undefined>;
    declare public /*out*/ readonly created: pulumi.Output<string>;
    /**
     * Whether stale approvals are dismissed after new commits.
     */
    declare public readonly dismissStaleApprovals: pulumi.Output<boolean | undefined>;
    /**
     * Whether review approvals are limited to the approval whitelist.
     */
    declare public readonly enableApprovalsWhitelist: pulumi.Output<boolean | undefined>;
    /**
     * Whether merging is limited to the merge whitelist.
     */
    declare public readonly enableMergeWhitelist: pulumi.Output<boolean | undefined>;
    /**
     * Whether protected branches can be pushed to directly.
     */
    declare public readonly enablePush: pulumi.Output<boolean | undefined>;
    /**
     * Whether direct pushes are limited to the push whitelist.
     */
    declare public readonly enablePushWhitelist: pulumi.Output<boolean | undefined>;
    /**
     * Whether status checks are required before merge.
     */
    declare public readonly enableStatusCheck: pulumi.Output<boolean | undefined>;
    /**
     * Teams allowed to merge.
     */
    declare public readonly mergeWhitelistTeams: pulumi.Output<string[] | undefined>;
    /**
     * Users allowed to merge.
     */
    declare public readonly mergeWhitelistUsernames: pulumi.Output<string[] | undefined>;
    /**
     * Protected branch name or rule pattern.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Repository owner.
     */
    declare public readonly owner: pulumi.Output<string>;
    /**
     * Protected file patterns.
     */
    declare public readonly protectedFilePatterns: pulumi.Output<string | undefined>;
    /**
     * Whether deploy keys may push directly.
     */
    declare public readonly pushWhitelistDeployKeys: pulumi.Output<boolean | undefined>;
    /**
     * Teams allowed to push directly.
     */
    declare public readonly pushWhitelistTeams: pulumi.Output<string[] | undefined>;
    /**
     * Users allowed to push directly.
     */
    declare public readonly pushWhitelistUsernames: pulumi.Output<string[] | undefined>;
    /**
     * Repository name.
     */
    declare public readonly repository: pulumi.Output<string>;
    /**
     * Whether commits must be signed.
     */
    declare public readonly requireSignedCommits: pulumi.Output<boolean | undefined>;
    /**
     * Number of required approving reviews.
     */
    declare public readonly requiredApprovals: pulumi.Output<number | undefined>;
    /**
     * Required status check contexts.
     */
    declare public readonly statusCheckContexts: pulumi.Output<string[] | undefined>;
    /**
     * Unprotected file patterns.
     */
    declare public readonly unprotectedFilePatterns: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly updated: pulumi.Output<string>;

    /**
     * Create a RepositoryBranchProtection resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RepositoryBranchProtectionArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.owner === undefined && !opts.urn) {
                throw new Error("Missing required property 'owner'");
            }
            if (args?.repository === undefined && !opts.urn) {
                throw new Error("Missing required property 'repository'");
            }
            resourceInputs["approvalsWhitelistTeams"] = args?.approvalsWhitelistTeams;
            resourceInputs["approvalsWhitelistUsernames"] = args?.approvalsWhitelistUsernames;
            resourceInputs["blockOnOfficialReviewRequests"] = args?.blockOnOfficialReviewRequests;
            resourceInputs["blockOnOutdatedBranch"] = args?.blockOnOutdatedBranch;
            resourceInputs["blockOnRejectedReviews"] = args?.blockOnRejectedReviews;
            resourceInputs["dismissStaleApprovals"] = args?.dismissStaleApprovals;
            resourceInputs["enableApprovalsWhitelist"] = args?.enableApprovalsWhitelist;
            resourceInputs["enableMergeWhitelist"] = args?.enableMergeWhitelist;
            resourceInputs["enablePush"] = args?.enablePush;
            resourceInputs["enablePushWhitelist"] = args?.enablePushWhitelist;
            resourceInputs["enableStatusCheck"] = args?.enableStatusCheck;
            resourceInputs["mergeWhitelistTeams"] = args?.mergeWhitelistTeams;
            resourceInputs["mergeWhitelistUsernames"] = args?.mergeWhitelistUsernames;
            resourceInputs["name"] = args?.name;
            resourceInputs["owner"] = args?.owner;
            resourceInputs["protectedFilePatterns"] = args?.protectedFilePatterns;
            resourceInputs["pushWhitelistDeployKeys"] = args?.pushWhitelistDeployKeys;
            resourceInputs["pushWhitelistTeams"] = args?.pushWhitelistTeams;
            resourceInputs["pushWhitelistUsernames"] = args?.pushWhitelistUsernames;
            resourceInputs["repository"] = args?.repository;
            resourceInputs["requireSignedCommits"] = args?.requireSignedCommits;
            resourceInputs["requiredApprovals"] = args?.requiredApprovals;
            resourceInputs["statusCheckContexts"] = args?.statusCheckContexts;
            resourceInputs["unprotectedFilePatterns"] = args?.unprotectedFilePatterns;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["updated"] = undefined /*out*/;
        } else {
            resourceInputs["approvalsWhitelistTeams"] = undefined /*out*/;
            resourceInputs["approvalsWhitelistUsernames"] = undefined /*out*/;
            resourceInputs["blockOnOfficialReviewRequests"] = undefined /*out*/;
            resourceInputs["blockOnOutdatedBranch"] = undefined /*out*/;
            resourceInputs["blockOnRejectedReviews"] = undefined /*out*/;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["dismissStaleApprovals"] = undefined /*out*/;
            resourceInputs["enableApprovalsWhitelist"] = undefined /*out*/;
            resourceInputs["enableMergeWhitelist"] = undefined /*out*/;
            resourceInputs["enablePush"] = undefined /*out*/;
            resourceInputs["enablePushWhitelist"] = undefined /*out*/;
            resourceInputs["enableStatusCheck"] = undefined /*out*/;
            resourceInputs["mergeWhitelistTeams"] = undefined /*out*/;
            resourceInputs["mergeWhitelistUsernames"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["owner"] = undefined /*out*/;
            resourceInputs["protectedFilePatterns"] = undefined /*out*/;
            resourceInputs["pushWhitelistDeployKeys"] = undefined /*out*/;
            resourceInputs["pushWhitelistTeams"] = undefined /*out*/;
            resourceInputs["pushWhitelistUsernames"] = undefined /*out*/;
            resourceInputs["repository"] = undefined /*out*/;
            resourceInputs["requireSignedCommits"] = undefined /*out*/;
            resourceInputs["requiredApprovals"] = undefined /*out*/;
            resourceInputs["statusCheckContexts"] = undefined /*out*/;
            resourceInputs["unprotectedFilePatterns"] = undefined /*out*/;
            resourceInputs["updated"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RepositoryBranchProtection.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a RepositoryBranchProtection resource.
 */
export interface RepositoryBranchProtectionArgs {
    /**
     * Teams whose approvals count.
     */
    approvalsWhitelistTeams?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Users whose approvals count.
     */
    approvalsWhitelistUsernames?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Whether official review requests block merging.
     */
    blockOnOfficialReviewRequests?: pulumi.Input<boolean>;
    /**
     * Whether outdated branches block merging.
     */
    blockOnOutdatedBranch?: pulumi.Input<boolean>;
    /**
     * Whether rejected reviews block merging.
     */
    blockOnRejectedReviews?: pulumi.Input<boolean>;
    /**
     * Whether stale approvals are dismissed after new commits.
     */
    dismissStaleApprovals?: pulumi.Input<boolean>;
    /**
     * Whether review approvals are limited to the approval whitelist.
     */
    enableApprovalsWhitelist?: pulumi.Input<boolean>;
    /**
     * Whether merging is limited to the merge whitelist.
     */
    enableMergeWhitelist?: pulumi.Input<boolean>;
    /**
     * Whether protected branches can be pushed to directly.
     */
    enablePush?: pulumi.Input<boolean>;
    /**
     * Whether direct pushes are limited to the push whitelist.
     */
    enablePushWhitelist?: pulumi.Input<boolean>;
    /**
     * Whether status checks are required before merge.
     */
    enableStatusCheck?: pulumi.Input<boolean>;
    /**
     * Teams allowed to merge.
     */
    mergeWhitelistTeams?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Users allowed to merge.
     */
    mergeWhitelistUsernames?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Protected branch name or rule pattern.
     */
    name: pulumi.Input<string>;
    /**
     * Repository owner.
     */
    owner: pulumi.Input<string>;
    /**
     * Protected file patterns.
     */
    protectedFilePatterns?: pulumi.Input<string>;
    /**
     * Whether deploy keys may push directly.
     */
    pushWhitelistDeployKeys?: pulumi.Input<boolean>;
    /**
     * Teams allowed to push directly.
     */
    pushWhitelistTeams?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Users allowed to push directly.
     */
    pushWhitelistUsernames?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Repository name.
     */
    repository: pulumi.Input<string>;
    /**
     * Whether commits must be signed.
     */
    requireSignedCommits?: pulumi.Input<boolean>;
    /**
     * Number of required approving reviews.
     */
    requiredApprovals?: pulumi.Input<number>;
    /**
     * Required status check contexts.
     */
    statusCheckContexts?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Unprotected file patterns.
     */
    unprotectedFilePatterns?: pulumi.Input<string>;
}
