// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Settings for enabled Forgejo repository units and their wiki or issue tracker configuration.
 */
export class RepositorySettings extends pulumi.CustomResource {
    /**
     * Get an existing RepositorySettings resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): RepositorySettings {
        return new RepositorySettings(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'forgejo:index:RepositorySettings';

    /**
     * Returns true if the given object is an instance of RepositorySettings.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RepositorySettings {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RepositorySettings.__pulumiType;
    }

    /**
     * Whether the actions unit is enabled. Leave unset to avoid managing it.
     */
    declare public readonly actions: pulumi.Output<boolean | undefined>;
    /**
     * Whether fast-forward-only merges are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
     */
    declare public readonly allowFastForwardOnlyMerge: pulumi.Output<boolean | undefined>;
    /**
     * Whether merge commits are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
     */
    declare public readonly allowMergeCommits: pulumi.Output<boolean | undefined>;
    /**
     * Whether rebase merges are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
     */
    declare public readonly allowRebase: pulumi.Output<boolean | undefined>;
    /**
     * Whether rebase-merge (rebase with merge commit) is allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
     */
    declare public readonly allowRebaseMerge: pulumi.Output<boolean | undefined>;
    /**
     * Whether squash merges are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
     */
    declare public readonly allowSquashMerge: pulumi.Output<boolean | undefined>;
    /**
     * Whether the repository is archived. Leave unset to avoid managing it.
     */
    declare public readonly archived: pulumi.Output<boolean | undefined>;
    /**
     * Whether Forgejo deletes pull request branches by default after merge. Setting this also enables pull requests unless pullRequests is explicitly set.
     */
    declare public readonly defaultDeleteBranchAfterMerge: pulumi.Output<boolean | undefined>;
    /**
     * Default merge style: merge, rebase, rebase-merge, squash, or fast-forward-only. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
     */
    declare public readonly defaultMergeStyle: pulumi.Output<string | undefined>;
    /**
     * External issue tracker URL format. Forgejo supports placeholders such as {user}, {repo}, and {index}.
     */
    declare public readonly externalTrackerFormat: pulumi.Output<string | undefined>;
    /**
     * External issue tracker regular expression pattern.
     */
    declare public readonly externalTrackerRegexPattern: pulumi.Output<string | undefined>;
    /**
     * External issue tracker number style, for example numeric or alphanumeric.
     */
    declare public readonly externalTrackerStyle: pulumi.Output<string | undefined>;
    /**
     * External issue tracker URL. Setting this also enables issues unless issues is explicitly set.
     */
    declare public readonly externalTrackerUrl: pulumi.Output<string | undefined>;
    /**
     * External wiki URL. Setting this also enables the wiki unless wiki is explicitly set.
     */
    declare public readonly externalWikiUrl: pulumi.Output<string | undefined>;
    /**
     * Whether the wiki is globally editable.
     */
    declare public readonly globallyEditableWiki: pulumi.Output<boolean | undefined>;
    /**
     * Whether only contributors may track time in the internal issue tracker.
     */
    declare public readonly internalTrackerAllowOnlyContributorsToTrackTime: pulumi.Output<boolean | undefined>;
    /**
     * Whether issue dependencies are enabled in the internal issue tracker.
     */
    declare public readonly internalTrackerEnableIssueDependencies: pulumi.Output<boolean | undefined>;
    /**
     * Whether the internal issue tracker has time tracking enabled.
     */
    declare public readonly internalTrackerEnableTimeTracker: pulumi.Output<boolean | undefined>;
    /**
     * Whether the issue tracker unit is enabled. Leave unset to avoid managing it.
     */
    declare public readonly issues: pulumi.Output<boolean | undefined>;
    /**
     * Repository owner.
     */
    declare public readonly owner: pulumi.Output<string>;
    /**
     * Whether the packages unit is enabled. Leave unset to avoid managing it.
     */
    declare public readonly packages: pulumi.Output<boolean | undefined>;
    /**
     * Whether the projects unit is enabled. Leave unset to avoid managing it.
     */
    declare public readonly projects: pulumi.Output<boolean | undefined>;
    /**
     * Whether the pull request unit is enabled. Leave unset to avoid managing it.
     */
    declare public readonly pullRequests: pulumi.Output<boolean | undefined>;
    /**
     * Whether the releases unit is enabled. Leave unset to avoid managing it.
     */
    declare public readonly releases: pulumi.Output<boolean | undefined>;
    /**
     * Repository name.
     */
    declare public readonly repository: pulumi.Output<string>;
    /**
     * Whether the wiki unit is enabled. Leave unset to avoid managing it.
     */
    declare public readonly wiki: pulumi.Output<boolean | undefined>;
    /**
     * Branch used for the repository wiki.
     */
    declare public readonly wikiBranch: pulumi.Output<string | undefined>;

    /**
     * Create a RepositorySettings resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RepositorySettingsArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.owner === undefined && !opts.urn) {
                throw new Error("Missing required property 'owner'");
            }
            if (args?.repository === undefined && !opts.urn) {
                throw new Error("Missing required property 'repository'");
            }
            resourceInputs["actions"] = args?.actions;
            resourceInputs["allowFastForwardOnlyMerge"] = args?.allowFastForwardOnlyMerge;
            resourceInputs["allowMergeCommits"] = args?.allowMergeCommits;
            resourceInputs["allowRebase"] = args?.allowRebase;
            resourceInputs["allowRebaseMerge"] = args?.allowRebaseMerge;
            resourceInputs["allowSquashMerge"] = args?.allowSquashMerge;
            resourceInputs["archived"] = args?.archived;
            resourceInputs["defaultDeleteBranchAfterMerge"] = args?.defaultDeleteBranchAfterMerge;
            resourceInputs["defaultMergeStyle"] = args?.defaultMergeStyle;
            resourceInputs["externalTrackerFormat"] = args?.externalTrackerFormat;
            resourceInputs["externalTrackerRegexPattern"] = args?.externalTrackerRegexPattern;
            resourceInputs["externalTrackerStyle"] = args?.externalTrackerStyle;
            resourceInputs["externalTrackerUrl"] = args?.externalTrackerUrl;
            resourceInputs["externalWikiUrl"] = args?.externalWikiUrl;
            resourceInputs["globallyEditableWiki"] = args?.globallyEditableWiki;
            resourceInputs["internalTrackerAllowOnlyContributorsToTrackTime"] = args?.internalTrackerAllowOnlyContributorsToTrackTime;
            resourceInputs["internalTrackerEnableIssueDependencies"] = args?.internalTrackerEnableIssueDependencies;
            resourceInputs["internalTrackerEnableTimeTracker"] = args?.internalTrackerEnableTimeTracker;
            resourceInputs["issues"] = args?.issues;
            resourceInputs["owner"] = args?.owner;
            resourceInputs["packages"] = args?.packages;
            resourceInputs["projects"] = args?.projects;
            resourceInputs["pullRequests"] = args?.pullRequests;
            resourceInputs["releases"] = args?.releases;
            resourceInputs["repository"] = args?.repository;
            resourceInputs["wiki"] = args?.wiki;
            resourceInputs["wikiBranch"] = args?.wikiBranch;
        } else {
            resourceInputs["actions"] = undefined /*out*/;
            resourceInputs["allowFastForwardOnlyMerge"] = undefined /*out*/;
            resourceInputs["allowMergeCommits"] = undefined /*out*/;
            resourceInputs["allowRebase"] = undefined /*out*/;
            resourceInputs["allowRebaseMerge"] = undefined /*out*/;
            resourceInputs["allowSquashMerge"] = undefined /*out*/;
            resourceInputs["archived"] = undefined /*out*/;
            resourceInputs["defaultDeleteBranchAfterMerge"] = undefined /*out*/;
            resourceInputs["defaultMergeStyle"] = undefined /*out*/;
            resourceInputs["externalTrackerFormat"] = undefined /*out*/;
            resourceInputs["externalTrackerRegexPattern"] = undefined /*out*/;
            resourceInputs["externalTrackerStyle"] = undefined /*out*/;
            resourceInputs["externalTrackerUrl"] = undefined /*out*/;
            resourceInputs["externalWikiUrl"] = undefined /*out*/;
            resourceInputs["globallyEditableWiki"] = undefined /*out*/;
            resourceInputs["internalTrackerAllowOnlyContributorsToTrackTime"] = undefined /*out*/;
            resourceInputs["internalTrackerEnableIssueDependencies"] = undefined /*out*/;
            resourceInputs["internalTrackerEnableTimeTracker"] = undefined /*out*/;
            resourceInputs["issues"] = undefined /*out*/;
            resourceInputs["owner"] = undefined /*out*/;
            resourceInputs["packages"] = undefined /*out*/;
            resourceInputs["projects"] = undefined /*out*/;
            resourceInputs["pullRequests"] = undefined /*out*/;
            resourceInputs["releases"] = undefined /*out*/;
            resourceInputs["repository"] = undefined /*out*/;
            resourceInputs["wiki"] = undefined /*out*/;
            resourceInputs["wikiBranch"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RepositorySettings.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a RepositorySettings resource.
 */
export interface RepositorySettingsArgs {
    /**
     * Whether the actions unit is enabled. Leave unset to avoid managing it.
     */
    actions?: pulumi.Input<boolean | undefined>;
    /**
     * Whether fast-forward-only merges are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
     */
    allowFastForwardOnlyMerge?: pulumi.Input<boolean | undefined>;
    /**
     * Whether merge commits are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
     */
    allowMergeCommits?: pulumi.Input<boolean | undefined>;
    /**
     * Whether rebase merges are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
     */
    allowRebase?: pulumi.Input<boolean | undefined>;
    /**
     * Whether rebase-merge (rebase with merge commit) is allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
     */
    allowRebaseMerge?: pulumi.Input<boolean | undefined>;
    /**
     * Whether squash merges are allowed. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
     */
    allowSquashMerge?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the repository is archived. Leave unset to avoid managing it.
     */
    archived?: pulumi.Input<boolean | undefined>;
    /**
     * Whether Forgejo deletes pull request branches by default after merge. Setting this also enables pull requests unless pullRequests is explicitly set.
     */
    defaultDeleteBranchAfterMerge?: pulumi.Input<boolean | undefined>;
    /**
     * Default merge style: merge, rebase, rebase-merge, squash, or fast-forward-only. Setting any merge option also enables pull requests unless pullRequests is explicitly set.
     */
    defaultMergeStyle?: pulumi.Input<string | undefined>;
    /**
     * External issue tracker URL format. Forgejo supports placeholders such as {user}, {repo}, and {index}.
     */
    externalTrackerFormat?: pulumi.Input<string | undefined>;
    /**
     * External issue tracker regular expression pattern.
     */
    externalTrackerRegexPattern?: pulumi.Input<string | undefined>;
    /**
     * External issue tracker number style, for example numeric or alphanumeric.
     */
    externalTrackerStyle?: pulumi.Input<string | undefined>;
    /**
     * External issue tracker URL. Setting this also enables issues unless issues is explicitly set.
     */
    externalTrackerUrl?: pulumi.Input<string | undefined>;
    /**
     * External wiki URL. Setting this also enables the wiki unless wiki is explicitly set.
     */
    externalWikiUrl?: pulumi.Input<string | undefined>;
    /**
     * Whether the wiki is globally editable.
     */
    globallyEditableWiki?: pulumi.Input<boolean | undefined>;
    /**
     * Whether only contributors may track time in the internal issue tracker.
     */
    internalTrackerAllowOnlyContributorsToTrackTime?: pulumi.Input<boolean | undefined>;
    /**
     * Whether issue dependencies are enabled in the internal issue tracker.
     */
    internalTrackerEnableIssueDependencies?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the internal issue tracker has time tracking enabled.
     */
    internalTrackerEnableTimeTracker?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the issue tracker unit is enabled. Leave unset to avoid managing it.
     */
    issues?: pulumi.Input<boolean | undefined>;
    /**
     * Repository owner.
     */
    owner: pulumi.Input<string>;
    /**
     * Whether the packages unit is enabled. Leave unset to avoid managing it.
     */
    packages?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the projects unit is enabled. Leave unset to avoid managing it.
     */
    projects?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the pull request unit is enabled. Leave unset to avoid managing it.
     */
    pullRequests?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the releases unit is enabled. Leave unset to avoid managing it.
     */
    releases?: pulumi.Input<boolean | undefined>;
    /**
     * Repository name.
     */
    repository: pulumi.Input<string>;
    /**
     * Whether the wiki unit is enabled. Leave unset to avoid managing it.
     */
    wiki?: pulumi.Input<boolean | undefined>;
    /**
     * Branch used for the repository wiki.
     */
    wikiBranch?: pulumi.Input<string | undefined>;
}
