// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A Forgejo Actions variable for a repository.
 */
export class RepositoryActionVariable extends pulumi.CustomResource {
    /**
     * Get an existing RepositoryActionVariable resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): RepositoryActionVariable {
        return new RepositoryActionVariable(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'forgejo:index:RepositoryActionVariable';

    /**
     * Returns true if the given object is an instance of RepositoryActionVariable.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RepositoryActionVariable {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RepositoryActionVariable.__pulumiType;
    }

    /**
     * Actions variable name.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Repository owner.
     */
    declare public readonly owner: pulumi.Output<string>;
    declare public /*out*/ readonly ownerId: pulumi.Output<number>;
    declare public /*out*/ readonly repoId: pulumi.Output<number>;
    /**
     * Repository name.
     */
    declare public readonly repository: pulumi.Output<string>;
    /**
     * Actions variable value.
     */
    declare public readonly value: pulumi.Output<string>;

    /**
     * Create a RepositoryActionVariable resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RepositoryActionVariableArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.owner === undefined && !opts.urn) {
                throw new Error("Missing required property 'owner'");
            }
            if (args?.repository === undefined && !opts.urn) {
                throw new Error("Missing required property 'repository'");
            }
            if (args?.value === undefined && !opts.urn) {
                throw new Error("Missing required property 'value'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["owner"] = args?.owner;
            resourceInputs["repository"] = args?.repository;
            resourceInputs["value"] = args?.value;
            resourceInputs["ownerId"] = undefined /*out*/;
            resourceInputs["repoId"] = undefined /*out*/;
        } else {
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["owner"] = undefined /*out*/;
            resourceInputs["ownerId"] = undefined /*out*/;
            resourceInputs["repoId"] = undefined /*out*/;
            resourceInputs["repository"] = undefined /*out*/;
            resourceInputs["value"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RepositoryActionVariable.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a RepositoryActionVariable resource.
 */
export interface RepositoryActionVariableArgs {
    /**
     * Actions variable name.
     */
    name: pulumi.Input<string>;
    /**
     * Repository owner.
     */
    owner: pulumi.Input<string>;
    /**
     * Repository name.
     */
    repository: pulumi.Input<string>;
    /**
     * Actions variable value.
     */
    value: pulumi.Input<string>;
}
